/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Aerospace Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.event;

import org.axonframework.config.ProcessingGroup;
import org.axonframework.eventhandling.EventHandler;
import org.springframework.stereotype.Component;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.repository.*;

/**
 * ============================================================================
 * AircraftOrderEventHandler
 * ============================================================================
 *
 * Event handler for AircraftOrder as outlined for the CQRS pattern.  All reads related to AircraftOrder are invoked here
 * and dispersed as an event to be handled elsewhere.
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Aerospace Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>Metadata describing this Aerospace HCIDL document.</td></tr>
 *          <tr><td>industry</td><td>Aerospace</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * Services Used:
 *
 *      AircraftOrderRepository
 *
 * Events Handled
 *      CreatedAircraftOrderEvent
 *      UpdatedAircraftOrderEvent
 *      DeletedAircraftOrderEvent
 *
 * @author Harbormaster Dev Team
 * ============================================================================
 */
@Component("aircraftOrder-handler")
@ProcessingGroup("aircraftOrder-processing-group")
public class AircraftOrderEventHandler {
	
	// core constructor
	AircraftOrderEventHandler(EntityManager entityManager) {
        this.entityManager = entityManager;
    }	
	
    /*
     * @param	event CreateAircraftOrderEvent
     */
    @EventHandler
    public void handle( CreateAircraftOrderEvent event) {
        entityManager.persist(new AircraftOrder(event.getAircraftOrderId(), event.getOrderNumber(), event.getTotalAmount(), event.getOperator(), event.getVariant(), event.getQuote(), event.getPurchaseAgreement(), event.getStatus()));
    }

    /*
     * @param	event UpdateAircraftOrderEvent
     */
    @EventHandler
    public AircraftOrder handle( UpdateAircraftOrderEvent event) {
    	entityManager.merge(new AircraftOrder(event.getAircraftOrderId(), event.getOrderNumber(), event.getTotalAmount(), event.getOperator(), event.getVariant(), event.getQuote(), event.getPurchaseAgreement(), event.getStatus()));
    }
    
    /*
     * @param	event DeleteAircraftOrderEvent
     */
    @EventHandler
    public void on( DeleteAircraftOrderEvent event) {
    	AircraftOrder entity = new AircraftOrder();
   
    	// ------------------------------------------
    	// apply the AircraftOrderId
    	// ------------------------------------------
    	entity.setAircraftOrderId( event.getAircraftOrderId() );
    	
    	// ------------------------------------------
    	// add to an Iterable and delete
    	// ------------------------------------------
    	entityManager.remove( entity );
    }    
    
    // attributes
	private final AircraftOrderRepository aircraftOrderEntityRepository;
    private static final Logger LOGGER 			= Logger.getLogger(AircraftOrderEventHandler.class.getName());

}
