/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Healthcare Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */

package com.harbormaster.entity;

import java.util.*

import javax.persistence.*
import javax.persistence.NamedQueries
import javax.persistence.NamedQuery

import com.harbormaster.api.*;

// --------------------------------------------
// Entity Definitions
// --------------------------------------------
@Entity
class HealthSystem(
    @Id var healthSystemId: UUID? = null,
    var name: String? = null,
    var legalName: String? = null,
    var headquartersCountry: String? = null,
    var website: String? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "facilities") var facilities:  Set<Facility>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "suppliers") var suppliers:  Set<MedicalSupplier>? = null
) 

@Entity
class Facility(
    @Id var facilityId: UUID? = null,
    var name: String? = null,
    var facilityCode: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "street", column = Column(name = "address_street")),
      AttributeOverride( name = "city", column = Column(name = "address_city")),
      AttributeOverride( name = "state", column = Column(name = "address_state")),
      AttributeOverride( name = "postalCode", column = Column(name = "address_postalCode")),
      AttributeOverride( name = "country", column = Column(name = "address_country"))
    )
    var address: Address? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "healthSystem") var healthSystem: HealthSystem? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "departments") var departments:  Set<Department>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "careTeams") var careTeams:  Set<CareTeam>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "laboratories") var laboratories:  Set<Laboratory>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "imagingCenters") var imagingCenters:  Set<ImagingCenter>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "pharmacies") var pharmacies:  Set<Pharmacy>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "inventoryItems") var inventoryItems:  Set<InventoryItem>? = null,
    @Enumerated(EnumType.STRING) var facilityType: FacilityType? = null
) 

@Entity
class Department(
    @Id var departmentId: UUID? = null,
    var name: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "facility") var facility: Facility? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "careTeams") var careTeams:  Set<CareTeam>? = null,
    @Enumerated(EnumType.STRING) var departmentType: DepartmentType? = null
) 

@Entity
class CareTeam(
    @Id var careTeamId: UUID? = null,
    var name: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "department") var department: Department? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "clinicians") var clinicians:  Set<Clinician>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "patients") var patients:  Set<Patient>? = null,
    @Enumerated(EnumType.STRING) var careSetting: CareSettingType? = null
) 

@Entity
class Clinician(
    @Id var clinicianId: UUID? = null,
    var firstName: String? = null,
    var lastName: String? = null,
    var licenseNumber: String? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "careTeams") var careTeams:  Set<CareTeam>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "appointments") var appointments:  Set<Appointment>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "encounters") var encounters:  Set<Encounter>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "procedures") var procedures:  Set<Procedure>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "imagingReports") var imagingReports:  Set<ImagingReport>? = null,
    @Enumerated(EnumType.STRING) var clinicianType: ClinicianType? = null,
    @Enumerated(EnumType.STRING) var specialty: ClinicianSpecialty? = null
) 

@Entity
class Patient(
    @Id var patientId: UUID? = null,
    var firstName: String? = null,
    var lastName: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "value", column = Column(name = "mrn_value"))
    )
    var mrn: MRN? = null,
    var dateOfBirth:  Date? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "street", column = Column(name = "address_street")),
      AttributeOverride( name = "city", column = Column(name = "address_city")),
      AttributeOverride( name = "state", column = Column(name = "address_state")),
      AttributeOverride( name = "postalCode", column = Column(name = "address_postalCode")),
      AttributeOverride( name = "country", column = Column(name = "address_country"))
    )
    var address: Address? = null,
    var primaryLanguage: String? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "appointments") var appointments:  Set<Appointment>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "encounters") var encounters:  Set<Encounter>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "carePlans") var carePlans:  Set<CarePlan>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "allergies") var allergies:  Set<Allergy>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "conditions") var conditions:  Set<Condition>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "medicationOrders") var medicationOrders:  Set<MedicationOrder>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "labOrders") var labOrders:  Set<LaboratoryOrder>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "imagingOrders") var imagingOrders:  Set<ImagingOrder>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "coverages") var coverages:  Set<Coverage>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "claims") var claims:  Set<Claim>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "devices") var devices:  Set<MedicalDevice>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "observations") var observations:  Set<Observation>? = null,
    @Enumerated(EnumType.STRING) var sexAtBirth: AdministrativeSex? = null,
    @Enumerated(EnumType.STRING) var bloodType: BloodType? = null
) 

@Entity
class Appointment(
    @Id var appointmentId: UUID? = null,
    var appointmentDate:  Date? = null,
    var reason: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "clinician") var clinician: Clinician? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "facility") var facility: Facility? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "encounter") var encounter: Encounter? = null,
    @Enumerated(EnumType.STRING) var status: AppointmentStatus? = null,
    @Enumerated(EnumType.STRING) var priority: Priority? = null
) 

@Entity
class Encounter(
    @Id var encounterId: UUID? = null,
    var encounterNumber: String? = null,
    var startDateTime:  Date? = null,
    var endDateTime:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "clinician") var clinician: Clinician? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "facility") var facility: Facility? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "appointment") var appointment: Appointment? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "diagnoses") var diagnoses:  Set<Diagnosis>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "procedures") var procedures:  Set<Procedure>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "observations") var observations:  Set<Observation>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "orders") var orders:  Set<ClinicalOrder>? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "admission") var admission: Admission? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "discharge") var discharge: Discharge? = null,
    @Enumerated(EnumType.STRING) var status: EncounterStatus? = null,
    @Enumerated(EnumType.STRING) var encounterType: EncounterType? = null
) 

@Entity
class Admission(
    @Id var admissionId: UUID? = null,
    var admitDateTime:  Date? = null,
    var bed: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "encounter") var encounter: Encounter? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "facility") var facility: Facility? = null,
    @Enumerated(EnumType.STRING) var admissionType: AdmissionType? = null
) 

@Entity
class Discharge(
    @Id var dischargeId: UUID? = null,
    var dischargeDateTime:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "encounter") var encounter: Encounter? = null,
    @Enumerated(EnumType.STRING) var disposition: DischargeDisposition? = null
) 

@Entity
class ClinicalOrder(
    @Id var clinicalOrderId: UUID? = null,
    var orderNumber: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "encounter") var encounter: Encounter? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "orderingClinician") var orderingClinician: Clinician? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "medicationOrders") var medicationOrders:  Set<MedicationOrder>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "laboratoryOrders") var laboratoryOrders:  Set<LaboratoryOrder>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "imagingOrders") var imagingOrders:  Set<ImagingOrder>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "procedureOrders") var procedureOrders:  Set<ProcedureOrder>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "authorizations") var authorizations:  Set<Authorization>? = null,
    @Enumerated(EnumType.STRING) var status: OrderStatus? = null,
    @Enumerated(EnumType.STRING) var orderType: ClinicalOrderType? = null,
    @Enumerated(EnumType.STRING) var priority: Priority? = null
) 

@Entity
class MedicationOrder(
    @Id var medicationOrderId: UUID? = null,
    var medicationCode: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "dose_amount")),
      AttributeOverride( name = "unit", column = Column(name = "dose_unit"))
    )
    var dose: Dose? = null,
    var frequency: String? = null,
    var duration: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "order") var order: ClinicalOrder? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "pharmacy") var pharmacy: Pharmacy? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "dispenses") var dispenses:  Set<MedicationDispense>? = null,
    @Enumerated(EnumType.STRING) var route: RouteOfAdministration? = null
) 

@Entity
class Laboratory(
    @Id var laboratoryId: UUID? = null,
    var name: String? = null,
    var cliaNumber: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "facility") var facility: Facility? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "laboratoryOrders") var laboratoryOrders:  Set<LaboratoryOrder>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "labResults") var labResults:  Set<LabResult>? = null
) 

@Entity
class LaboratoryOrder(
    @Id var laboratoryOrderId: UUID? = null,
    var testCode: String? = null,
    var fastingRequired: Boolean? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "order") var order: ClinicalOrder? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "laboratory") var laboratory: Laboratory? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "results") var results:  Set<LabResult>? = null,
    @Enumerated(EnumType.STRING) var specimenType: SpecimenType? = null
) 

@Entity
class LabResult(
    @Id var labResultId: UUID? = null,
    var resultCode: String? = null,
    var issuedDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "laboratoryOrder") var laboratoryOrder: LaboratoryOrder? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "observations") var observations:  Set<Observation>? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "laboratory") var laboratory: Laboratory? = null,
    @Enumerated(EnumType.STRING) var status: ResultStatus? = null
) 

@Entity
class ImagingCenter(
    @Id var imagingCenterId: UUID? = null,
    var name: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "facility") var facility: Facility? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "imagingOrders") var imagingOrders:  Set<ImagingOrder>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "imagingReports") var imagingReports:  Set<ImagingReport>? = null
) 

@Entity
class ImagingOrder(
    @Id var imagingOrderId: UUID? = null,
    var bodySite: String? = null,
    var contrast: Boolean? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "order") var order: ClinicalOrder? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "imagingCenter") var imagingCenter: ImagingCenter? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "reports") var reports:  Set<ImagingReport>? = null,
    @Enumerated(EnumType.STRING) var modality: ImagingModality? = null
) 

@Entity
class ImagingReport(
    @Id var imagingReportId: UUID? = null,
    var reportNumber: String? = null,
    var impression: String? = null,
    var reportedDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "imagingOrder") var imagingOrder: ImagingOrder? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "clinician") var clinician: Clinician? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "encounter") var encounter: Encounter? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "imagingCenter") var imagingCenter: ImagingCenter? = null,
    @Enumerated(EnumType.STRING) var status: ResultStatus? = null
) 

@Entity
class ProcedureOrder(
    @Id var procedureOrderId: UUID? = null,
    var procedureCode: String? = null,
    var consentObtained: Boolean? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "order") var order: ClinicalOrder? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "facility") var facility: Facility? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "procedure") var procedure: Procedure? = null,
    @Enumerated(EnumType.STRING) var anesthesiaType: AnesthesiaType? = null
) 

@Entity
class Procedure(
    @Id var procedureId: UUID? = null,
    var procedureCode: String? = null,
    var startDateTime:  Date? = null,
    var endDateTime:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "encounter") var encounter: Encounter? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "performer") var performer: Clinician? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "procedureOrder") var procedureOrder: ProcedureOrder? = null,
    @Enumerated(EnumType.STRING) var status: ProcedureStatus? = null
) 

@Entity
class Pharmacy(
    @Id var pharmacyId: UUID? = null,
    var name: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "facility") var facility: Facility? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "medicationDispenses") var medicationDispenses:  Set<MedicationDispense>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "medicationOrders") var medicationOrders:  Set<MedicationOrder>? = null
) 

@Entity
class MedicationDispense(
    @Id var medicationDispenseId: UUID? = null,
    var dispenseNumber: String? = null,
    var quantity: java.math.BigDecimal? = null,
    var whenPrepared:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "medicationOrder") var medicationOrder: MedicationOrder? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "pharmacy") var pharmacy: Pharmacy? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @Enumerated(EnumType.STRING) var status: DispenseStatus? = null
) 

@Entity
class Diagnosis(
    @Id var diagnosisId: UUID? = null,
    var code: String? = null,
    var description: String? = null,
    var onsetDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "encounter") var encounter: Encounter? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @Enumerated(EnumType.STRING) var certainty: DiagnosisCertainty? = null
) 

@Entity
class Observation(
    @Id var observationId: UUID? = null,
    var code: String? = null,
    var value: String? = null,
    var unit: String? = null,
    var effectiveDateTime:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "encounter") var encounter: Encounter? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "device") var device: MedicalDevice? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "labResult") var labResult: LabResult? = null,
    @Enumerated(EnumType.STRING) var interpretation: ObservationInterpretation? = null
) 

@Entity
class CarePlan(
    @Id var carePlanId: UUID? = null,
    var planNumber: String? = null,
    var goalSummary: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "encounters") var encounters:  Set<Encounter>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "tasks") var tasks:  Set<CareTask>? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "careTeam") var careTeam: CareTeam? = null,
    @Enumerated(EnumType.STRING) var status: CarePlanStatus? = null
) 

@Entity
class CareTask(
    @Id var careTaskId: UUID? = null,
    var description: String? = null,
    var dueDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "carePlan") var carePlan: CarePlan? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "assignedTo") var assignedTo: Clinician? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "encounter") var encounter: Encounter? = null,
    @Enumerated(EnumType.STRING) var status: TaskStatus? = null,
    @Enumerated(EnumType.STRING) var priority: Priority? = null
) 

@Entity
class Allergy(
    @Id var allergyId: UUID? = null,
    var substance: String? = null,
    var reaction: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @Enumerated(EnumType.STRING) var severity: AllergySeverity? = null,
    @Enumerated(EnumType.STRING) var status: AllergyStatus? = null
) 

@Entity
class Condition(
    @Id var conditionId: UUID? = null,
    var code: String? = null,
    var onsetDate:  Date? = null,
    var abatementDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @Enumerated(EnumType.STRING) var clinicalStatus: ConditionStatus? = null,
    @Enumerated(EnumType.STRING) var verificationStatus: DiagnosisCertainty? = null
) 

@Entity
class InsurancePayer(
    @Id var insurancePayerId: UUID? = null,
    var name: String? = null,
    var website: String? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "plans") var plans:  Set<InsurancePlan>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "claims") var claims:  Set<Claim>? = null,
    @Enumerated(EnumType.STRING) var payerType: PayerType? = null
) 

@Entity
class InsurancePlan(
    @Id var insurancePlanId: UUID? = null,
    var name: String? = null,
    var planCode: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "payer") var payer: InsurancePayer? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "coverages") var coverages:  Set<Coverage>? = null,
    @Enumerated(EnumType.STRING) var planType: InsurancePlanType? = null
) 

@Entity
class Coverage(
    @Id var coverageId: UUID? = null,
    var memberId: String? = null,
    var groupNumber: String? = null,
    var effectiveDate:  Date? = null,
    var endDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "plan") var plan: InsurancePlan? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "claims") var claims:  Set<Claim>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "authorizations") var authorizations:  Set<Authorization>? = null,
    @Enumerated(EnumType.STRING) var coverageType: CoverageType? = null
) 

@Entity
class Claim(
    @Id var claimId: UUID? = null,
    var claimNumber: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "totalAmount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "totalAmount_currency"))
    )
    var totalAmount: Money? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "coverage") var coverage: Coverage? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "encounter") var encounter: Encounter? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "invoices") var invoices:  Set<Invoice>? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "payer") var payer: InsurancePayer? = null,
    @Enumerated(EnumType.STRING) var status: ClaimStatus? = null
) 

@Entity
class Authorization(
    @Id var authorizationId: UUID? = null,
    var authNumber: String? = null,
    var requestedService: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "coverage") var coverage: Coverage? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "order") var order: ClinicalOrder? = null,
    @Enumerated(EnumType.STRING) var status: AuthorizationStatus? = null
) 

@Entity
class Invoice(
    @Id var invoiceId: UUID? = null,
    var invoiceNumber: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "totalAmount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "totalAmount_currency"))
    )
    var totalAmount: Money? = null,
    var dueDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "claim") var claim: Claim? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "payments") var payments:  Set<Payment>? = null,
    @Enumerated(EnumType.STRING) var status: InvoiceStatus? = null
) 

@Entity
class Payment(
    @Id var paymentId: UUID? = null,
    var paymentNumber: String? = null,
     @Embedded     @AttributeOverrides(
      AttributeOverride( name = "amount", column = Column(name = "amount_amount")),
      AttributeOverride( name = "currency", column = Column(name = "amount_currency"))
    )
    var amount: Money? = null,
    var paymentDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "invoice") var invoice: Invoice? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "payer") var payer: InsurancePayer? = null,
    @Enumerated(EnumType.STRING) var method: PaymentMethod? = null
) 

@Entity
class MedicalDevice(
    @Id var medicalDeviceId: UUID? = null,
    var udi: String? = null,
    var manufacturer: String? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "patient") var patient: Patient? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "observations") var observations:  Set<Observation>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "softwareUpdates") var softwareUpdates:  Set<SoftwareUpdate>? = null,
    @Enumerated(EnumType.STRING) var deviceType: DeviceType? = null,
    @Enumerated(EnumType.STRING) var connectivityStatus: DeviceConnectivityStatus? = null
) 

@Entity
class SoftwareUpdate(
    @Id var softwareUpdateId: UUID? = null,
    var version: String? = null,
    var appliedDate:  Date? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "device") var device: MedicalDevice? = null,
    @Enumerated(EnumType.STRING) var updateType: SoftwareUpdateType? = null
) 

@Entity
class MedicalSupplier(
    @Id var medicalSupplierId: UUID? = null,
    var name: String? = null,
    var website: String? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "facilities") var facilities:  Set<Facility>? = null,
    @OneToMany(fetch = FetchType.EAGER) @JoinColumn(name = "inventoryItems") var inventoryItems:  Set<InventoryItem>? = null,
    @Enumerated(EnumType.STRING) var supplierTier: SupplierTier? = null
) 

@Entity
class InventoryItem(
    @Id var inventoryItemId: UUID? = null,
    var sku: String? = null,
    var name: String? = null,
    var quantityOnHand: Int? = null,
    var quantityReserved: Int? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "facility") var facility: Facility? = null,
    @OneToOne(fetch = FetchType.EAGER) @JoinColumn(name = "supplier") var supplier: MedicalSupplier? = null
) 


