package com.harbormaster.command;

import java.util.*;

import org.axonframework.modelling.command.Repository;

import org.axonframework.commandhandling.CommandHandler;
import org.springframework.stereotype.Component;

import com.harbormaster.aggregate.*;
import com.harbormaster.api.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;

/**
 * Command handler for SoftwareLoad as outlined for the CQRS pattern.  All creates, updates, deletes and other writes 
 * related to SoftwareLoad are handled here as external events are delegated to an associated Aggregate.
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Aerospace Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>Metadata describing this Aerospace HCIDL document.</td></tr>
 *          <tr><td>industry</td><td>Aerospace</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * Services Used
 *
 *  	Repository<SoftwareLoadAggregate>
 *
 * Produces
 *
 *      application/json
 *
 * Commands Accepted
 *
 *      CreateSoftwareLoadCommand
 *      UpdateSoftwareLoadCommand
 *      DeleteSoftwareLoadCommand
 *
 * @author Harbormaster Dev Team
 *
 */
@Component
class SoftwareLoadCommandHandler {

    public SoftwareLoadCommandHandler( Repository<SoftwareLoadAggregate> repository ) {
    	super();
    	this.aggregateRepository = repository;	
    }
    
    @CommandHandler
    public void handle(CreateSoftwareLoadCommand command) throws Exception {
    	
    	// --------------------------------------
    	// validate the create command
    	// --------------------------------------    	
		SoftwareLoadValidator.getInstance().validate( command );
		
    	// --------------------------------------
    	// delegate to the aggregate
    	// -------------------------------------- 
    	aggregateRepository.newInstance(() -> new SoftwareLoadAggregate(command));
    }


    @CommandHandler
    public void handle(UpdateSoftwareLoadCommand command) throws Exception {
    	// --------------------------------------
    	// validate the update command
    	// --------------------------------------    	
		SoftwareLoadValidator.getInstance().validate( command );

    	// --------------------------------------
    	// delegate to the aggregate
    	// --------------------------------------
    	aggregateRepository.newInstance(() -> new SoftwareLoadAggregate(command));
    }

    
    @CommandHandler
    public void handle(DeleteSoftwareLoadCommand command) throws Exception {
    	// --------------------------------------
    	// validate the delete command
    	// --------------------------------------    	
		SoftwareLoadValidator.getInstance().validate( command );    
		
    	// --------------------------------------
    	// delegate to the aggregate
    	// --------------------------------------
    	aggregateRepository.newInstance(() -> new SoftwareLoadAggregate(command));
    }
    
    // attributes
    private final Repository<SoftwareLoadAggregate> aggregateRepository;
}