/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Advertising Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>BrandSafetyPolicyEntity Projector</h2>
 * <p>
 * The BrandSafetyPolicy Entity Projector is responsible for maintaining the write model for
 * BrandSafetyPolicy entities. It subscribes to domain events published by the BrandSafetyPolicy
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/21/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Advertising Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model for advertising planning, buying, trafficking, delivery, and measurement.</td></tr>
 *          <tr><td>industry</td><td>Advertising</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>BrandSafetyPolicyRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("brandSafetyPolicy-entity-projector")
public class BrandSafetyPolicyEntityProjector implements EntityProjector<BrandSafetyPolicy>{
		
	// core constructor
	public BrandSafetyPolicyEntityProjector(ProjectorRegistry registry,
										BrandSafetyPolicyRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<BrandSafetyPolicy> getEntityClass() {
		return BrandSafetyPolicy.class;
	}

    /*
	 * Insert a BrandSafetyPolicy
	 * 
     * @param	entity BrandSafetyPolicy
     */
    public BrandSafetyPolicy create( BrandSafetyPolicy entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a BrandSafetyPolicy
	 * 
     * @param	entity BrandSafetyPolicy
     */
    public BrandSafetyPolicy update( BrandSafetyPolicy entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a BrandSafetyPolicy
	 * 
     * @param	id		UUID
     */
    public BrandSafetyPolicy delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    BrandSafetyPolicy entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    


    /*
     * Add to the TargetingProfiles
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	BrandSafetyPolicy
     */
    public BrandSafetyPolicy addToTargetingProfiles( UUID parentId, TargetingProfile addTo ) {
	    LOGGER.info("handling AssignTargetingProfilesToBrandSafetyPolicyEvent - " );
	    
	    BrandSafetyPolicy parentEntity = repository.findById(parentId).get();
	    TargetingProfile child = registry.project( TargetingProfile.class, addTo.getTargetingProfileId());
	    
	    parentEntity.getTargetingProfiles().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the TargetingProfiles
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	BrandSafetyPolicy
     */
	public BrandSafetyPolicy removeFromTargetingProfiles( UUID parentId, TargetingProfile removeFrom ) {
	    LOGGER.info("handling RemoveTargetingProfilesFromBrandSafetyPolicyEvent " );
	
	    BrandSafetyPolicy parentEntity = repository.findById(parentId).get();
	    TargetingProfile child = registry.project( TargetingProfile.class, removeFrom.getTargetingProfileId());
	    
	    parentEntity.getTargetingProfiles().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the BrandSafetyPolicy via an FindBrandSafetyPolicyQuery
     * @return 	query	FindBrandSafetyPolicyQuery
     */
    @SuppressWarnings("unused")
    public BrandSafetyPolicy find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a BrandSafetyPolicy - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all BrandSafetyPolicys
     *
     * @param	query	FindAllBrandSafetyPolicyQuery 
     * @return 	List<BrandSafetyPolicy> 
     */
    @SuppressWarnings("unused")
    public List<BrandSafetyPolicy> findAll( FindAllBrandSafetyPolicyQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all BrandSafetyPolicy - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final BrandSafetyPolicyRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(BrandSafetyPolicyEntityProjector.class.getName());

}
