/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Advertising Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>RateEntity Projector</h2>
 * <p>
 * The Rate Entity Projector is responsible for maintaining the write model for
 * Rate entities. It subscribes to domain events published by the Rate
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/21/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Advertising Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model for advertising planning, buying, trafficking, delivery, and measurement.</td></tr>
 *          <tr><td>industry</td><td>Advertising</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>RateRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("rate-entity-projector")
public class RateEntityProjector implements EntityProjector<Rate>{
		
	// core constructor
	public RateEntityProjector(ProjectorRegistry registry,
										RateRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<Rate> getEntityClass() {
		return Rate.class;
	}

    /*
	 * Insert a Rate
	 * 
     * @param	entity Rate
     */
    public Rate create( Rate entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a Rate
	 * 
     * @param	entity Rate
     */
    public Rate update( Rate entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a Rate
	 * 
     * @param	id		UUID
     */
    public Rate delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    Rate entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a RateCard
     * 
     * @param	parentId	UUID
     * @param	assignment 	RateCard 
     * @return	Rate
     */
    public Rate assignRateCard( UUID parentId, RateCard assignment ) {
	    LOGGER.info("assigning RateCard as " + assignment.toString() );

	    Rate parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( RateCard.class, assignment.getRateCardId());

	    // ------------------------------------------
		// assign the RateCard to the parent entity
		// ------------------------------------------ 
	    parentEntity.setRateCard( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the RateCard
	 * 
	 * @param	parentId		UUID
	 * @return	Rate
	 */
	public Rate unAssignRateCard( UUID parentId ) {
		Rate parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning RateCard on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the RateCard on the parent entithy
		// ------------------------------------------     
	    parentEntity.setRateCard(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a AdSlot
     * 
     * @param	parentId	UUID
     * @param	assignment 	AdSlot 
     * @return	Rate
     */
    public Rate assignAdSlot( UUID parentId, AdSlot assignment ) {
	    LOGGER.info("assigning AdSlot as " + assignment.toString() );

	    Rate parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( AdSlot.class, assignment.getAdSlotId());

	    // ------------------------------------------
		// assign the AdSlot to the parent entity
		// ------------------------------------------ 
	    parentEntity.setAdSlot( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the AdSlot
	 * 
	 * @param	parentId		UUID
	 * @return	Rate
	 */
	public Rate unAssignAdSlot( UUID parentId ) {
		Rate parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning AdSlot on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the AdSlot on the parent entithy
		// ------------------------------------------     
	    parentEntity.setAdSlot(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}




    /**
     * Method to retrieve the Rate via an FindRateQuery
     * @return 	query	FindRateQuery
     */
    @SuppressWarnings("unused")
    public Rate find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a Rate - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all Rates
     *
     * @param	query	FindAllRateQuery 
     * @return 	List<Rate> 
     */
    @SuppressWarnings("unused")
    public List<Rate> findAll( FindAllRateQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all Rate - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final RateRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(RateEntityProjector.class.getName());

}
