/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * ECommerce Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * PromotionRestController as REST API
 *
 * <p>Exposes REST endpoints for the Promotion entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>ECommerce Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core e-commerce capabilities across catalog, pricing, cart, order, payment, fulfillment, promotions, taxation, and marketplace operations.</td></tr>
 *          <tr><td>industry</td><td>ECommerce</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PromotionBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePromotionCommand</li>
 *      <li></li>UpdatePromotionCommand</li>
 *      <liDeletePromotionCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Promotion")
public class PromotionRestController extends BaseSpringRestController {

	public PromotionRestController( PromotionService service ) {
		this.service = service;
	}
	
    /**
     * Handles create a Promotion.  if not key provided, calls create, otherwise calls save
     * @param		Promotion	promotion
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreatePromotionCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = service.createPromotion( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a Promotion.  if no key provided, calls create, otherwise calls save
     * @param		Promotion promotion
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdatePromotionCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdatePromotionCommand
			// -----------------------------------------------
			completableFuture = service.updatePromotion(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "PromotionController:update() - successfully update Promotion - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a Promotion entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeletePromotionCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	PromotionService delegate = service;

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Promotion with key " + command.getPromotionId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a Promotion using a UUID
     * @param		UUID uuid 
     * @return		Promotion
     */    
    @GetMapping("/load")
    public Promotion load( @RequestParam(required=true) UUID uuid ) {    	
    	Promotion entity = null;

    	try {  
    		entity = service.getPromotion( new PromotionFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Promotion using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Promotion business objects
     * @return		Set<Promotion>
     */
    @GetMapping("/")
    public List<Promotion> loadAll() {                
    	List<Promotion> promotionList = null;
        
    	try {
            // load the Promotion
            promotionList = service.getAllPromotion();
            
            if ( promotionList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Promotions" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Promotions ", exc );
        	return null;
        }

        return promotionList;
                            
    }

    /**
     * save Merchant on Promotion
     * @param		command AssignMerchantToPromotionCommand
     */     
	@PutMapping("/assignMerchant")
	public void assignMerchant( @RequestBody AssignMerchantToPromotionCommand command ) {
		try {
			service.assignMerchant( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Merchant", exc );
        }
	}

    /**
     * unassign Merchant on Promotion
     * @param		 command UnAssignMerchantFromPromotionCommand
     */     
	@PutMapping("/unAssignMerchant")
	public void unAssignMerchant( @RequestBody(required=true)  UnAssignMerchantFromPromotionCommand command ) {
		try {
			service.unAssignMerchant( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Merchant", exc );
		}
	}
	

    /**
     * save Channels on Promotion
     * @param		command AssignChannelsToPromotionCommand
     */     
	@PutMapping("/addToChannels")
	public void addToChannels( @RequestBody(required=true) AssignChannelsToPromotionCommand command ) {
		try {
			service.addToChannels( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Channels", exc );
		}
	}

    /**
     * remove Channels on Promotion
     * @param		command RemoveChannelsFromPromotionCommand
     */     	
	@PutMapping("/removeFromChannels")
	public void removeFromChannels( 	@RequestBody(required=true) RemoveChannelsFromPromotionCommand command )
	{		
		try {
			service.removeFromChannels( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Channels", exc );
		}
	}

    /**
     * save ApplicableProducts on Promotion
     * @param		command AssignApplicableProductsToPromotionCommand
     */     
	@PutMapping("/addToApplicableProducts")
	public void addToApplicableProducts( @RequestBody(required=true) AssignApplicableProductsToPromotionCommand command ) {
		try {
			service.addToApplicableProducts( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set ApplicableProducts", exc );
		}
	}

    /**
     * remove ApplicableProducts on Promotion
     * @param		command RemoveApplicableProductsFromPromotionCommand
     */     	
	@PutMapping("/removeFromApplicableProducts")
	public void removeFromApplicableProducts( 	@RequestBody(required=true) RemoveApplicableProductsFromPromotionCommand command )
	{		
		try {
			service.removeFromApplicableProducts( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set ApplicableProducts", exc );
		}
	}

    /**
     * save ApplicableCategories on Promotion
     * @param		command AssignApplicableCategoriesToPromotionCommand
     */     
	@PutMapping("/addToApplicableCategories")
	public void addToApplicableCategories( @RequestBody(required=true) AssignApplicableCategoriesToPromotionCommand command ) {
		try {
			service.addToApplicableCategories( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set ApplicableCategories", exc );
		}
	}

    /**
     * remove ApplicableCategories on Promotion
     * @param		command RemoveApplicableCategoriesFromPromotionCommand
     */     	
	@PutMapping("/removeFromApplicableCategories")
	public void removeFromApplicableCategories( 	@RequestBody(required=true) RemoveApplicableCategoriesFromPromotionCommand command )
	{		
		try {
			service.removeFromApplicableCategories( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set ApplicableCategories", exc );
		}
	}

    /**
     * save Coupons on Promotion
     * @param		command AssignCouponsToPromotionCommand
     */     
	@PutMapping("/addToCoupons")
	public void addToCoupons( @RequestBody(required=true) AssignCouponsToPromotionCommand command ) {
		try {
			service.addToCoupons( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Coupons", exc );
		}
	}

    /**
     * remove Coupons on Promotion
     * @param		command RemoveCouponsFromPromotionCommand
     */     	
	@PutMapping("/removeFromCoupons")
	public void removeFromCoupons( 	@RequestBody(required=true) RemoveCouponsFromPromotionCommand command )
	{		
		try {
			service.removeFromCoupons( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Coupons", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Promotion promotion = null;
	protected PromotionService service = null;
	private static final Logger LOGGER = Logger.getLogger(PromotionRestController.class.getName());
    
}
