from django.urls import path
from hrOnDjango.views import EmployeeView

urlpatterns = [
    path('', EmployeeView.index, name='index'),
	path('create', EmployeeView.get, name='create'),
	path('get/<int:employeeId>/', EmployeeView.get, name='get'),
	path('save', EmployeeView.save, name='save'),
	path('getAll', EmployeeView.getAll, name='getAll'),
	path('delete/<int:employeeId>/', EmployeeView.delete, name='delete'),
	path('assignManager/<int:employeeId>/<int:ManagerId>/', EmployeeView.assignManager, name='assignManager'),
	path('unassignManager/<int:employeeId>/', EmployeeView.unassignManager, name='unassignManager'),
	path('assignDepartment/<int:employeeId>/<int:DepartmentId>/', EmployeeView.assignDepartment, name='assignDepartment'),
	path('unassignDepartment/<int:employeeId>/', EmployeeView.unassignDepartment, name='unassignDepartment'),
	path('assignPrimaryLocation/<int:employeeId>/<int:PrimaryLocationId>/', EmployeeView.assignPrimaryLocation, name='assignPrimaryLocation'),
	path('unassignPrimaryLocation/<int:employeeId>/', EmployeeView.unassignPrimaryLocation, name='unassignPrimaryLocation'),
	path('assignCostCenter/<int:employeeId>/<int:CostCenterId>/', EmployeeView.assignCostCenter, name='assignCostCenter'),
	path('unassignCostCenter/<int:employeeId>/', EmployeeView.unassignCostCenter, name='unassignCostCenter'),
	path('addDirectReports/<int:employeeId>/<DirectReportsIds>/', EmployeeView.addDirectReports, name='addDirectReports'),
	path('removeDirectReports/<int:employeeId>/<DirectReportsIds>/', EmployeeView.removeDirectReports, name='removeDirectReports'),
	path('addEmploymentAssignments/<int:employeeId>/<EmploymentAssignmentsIds>/', EmployeeView.addEmploymentAssignments, name='addEmploymentAssignments'),
	path('removeEmploymentAssignments/<int:employeeId>/<EmploymentAssignmentsIds>/', EmployeeView.removeEmploymentAssignments, name='removeEmploymentAssignments'),
	path('addContracts/<int:employeeId>/<ContractsIds>/', EmployeeView.addContracts, name='addContracts'),
	path('removeContracts/<int:employeeId>/<ContractsIds>/', EmployeeView.removeContracts, name='removeContracts'),
	path('addBenefitEnrollments/<int:employeeId>/<BenefitEnrollmentsIds>/', EmployeeView.addBenefitEnrollments, name='addBenefitEnrollments'),
	path('removeBenefitEnrollments/<int:employeeId>/<BenefitEnrollmentsIds>/', EmployeeView.removeBenefitEnrollments, name='removeBenefitEnrollments'),
	path('addTimesheets/<int:employeeId>/<TimesheetsIds>/', EmployeeView.addTimesheets, name='addTimesheets'),
	path('removeTimesheets/<int:employeeId>/<TimesheetsIds>/', EmployeeView.removeTimesheets, name='removeTimesheets'),
	path('addLeaveRequests/<int:employeeId>/<LeaveRequestsIds>/', EmployeeView.addLeaveRequests, name='addLeaveRequests'),
	path('removeLeaveRequests/<int:employeeId>/<LeaveRequestsIds>/', EmployeeView.removeLeaveRequests, name='removeLeaveRequests'),
	path('addPerformanceReviews/<int:employeeId>/<PerformanceReviewsIds>/', EmployeeView.addPerformanceReviews, name='addPerformanceReviews'),
	path('removePerformanceReviews/<int:employeeId>/<PerformanceReviewsIds>/', EmployeeView.removePerformanceReviews, name='removePerformanceReviews'),
	path('addTrainingEnrollments/<int:employeeId>/<TrainingEnrollmentsIds>/', EmployeeView.addTrainingEnrollments, name='addTrainingEnrollments'),
	path('removeTrainingEnrollments/<int:employeeId>/<TrainingEnrollmentsIds>/', EmployeeView.removeTrainingEnrollments, name='removeTrainingEnrollments'),
	path('addWorkAuthorizations/<int:employeeId>/<WorkAuthorizationsIds>/', EmployeeView.addWorkAuthorizations, name='addWorkAuthorizations'),
	path('removeWorkAuthorizations/<int:employeeId>/<WorkAuthorizationsIds>/', EmployeeView.removeWorkAuthorizations, name='removeWorkAuthorizations'),
]
