# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


5.times do |i|
  Organization.create( name:"test string for name", legalName:"test string for legalName", registrationCountry:"test string for registrationCountry", website:"test string for website" )
  Department.create( name:"test string for name", code:"test string for code" )
  Location.create( name:"test string for name", address:"test value", timezone:"test string for timezone" )
  CostCenter.create( code:"test string for code", name:"test string for name" )
  JobFamily.create( name:"test string for name", description:"test string for description" )
  JobProfile.create( title:"test string for title", jobCode:"test string for jobCode", JobLevel:0, ExemptStatus:0 )
  Competency.create( name:"test string for name", category:"test string for category" )
  Position.create( positionCode:"test string for positionCode", fte:"test value", Status:0, WorkLocationType:0 )
  Employee.create( employeeNumber:"test string for employeeNumber", name:"test value", workEmail:"test value", workPhone:"test value", dateOfHire:1.week.ago, nationalId:"test value", Status:0 )
  EmploymentAssignment.create( startDate:1.week.ago, endDate:1.week.ago, primary:true, AssignmentType:0, Status:0 )
  EmploymentContract.create( contractNumber:"test string for contractNumber", startDate:1.week.ago, endDate:1.week.ago, workHoursPerWeek:"test value", EmploymentType:0, Status:0, PayFrequency:0 )
  WorkSchedule.create( name:"test string for name", standardHoursPerWeek:"test value", ScheduleType:0 )
  WorkShift.create( startTime:1.week.ago, endTime:1.week.ago, breakMinutes:100, DayOfWeek:0 )
  ScheduleException.create( date:1.week.ago, reason:"test string for reason", hours:"test value" )
  CompensationPackage.create( effectiveFrom:1.week.ago, effectiveTo:1.week.ago, currency:"test string for currency" )
  SalaryComponent.create( amount:"test value", recurring:true, ComponentType:0 )
  BonusPlan.create( name:"test string for name", targetPercentage:"test value" )
  EquityGrant.create( grantId:"test string for grantId", grantedUnits:100, vestingStart:1.week.ago, GrantType:0 )
  BenefitPlan.create( name:"test string for name", providerName:"test string for providerName", employeeContributionRate:"test value", employerContributionRate:"test value", eligibilityRules:"test string for eligibilityRules", BenefitType:0 )
  BenefitEnrollment.create( enrollmentId:"test string for enrollmentId", effectiveFrom:1.week.ago, effectiveTo:1.week.ago, Status:0, CoverageLevel:0 )
  Dependent.create( firstName:"test string for firstName", lastName:"test string for lastName", birthDate:1.week.ago, Relationship:0 )
  PayrollCalendar.create( name:"test string for name", country:"test string for country", PayFrequency:0 )
  PayrollRun.create( runNumber:"test string for runNumber", periodStart:1.week.ago, periodEnd:1.week.ago, paymentDate:1.week.ago, Status:0 )
  PayrollItem.create( amount:"test value", taxable:true, ItemType:0 )
  TaxWithholding.create( taxId:"test value", allowances:100, additionalAmount:"test value", FilingStatus:0 )
  PaymentMethod.create( preferred:true, MethodType:0 )
  Timesheet.create( periodStart:1.week.ago, periodEnd:1.week.ago, submissionDate:1.week.ago, Status:0 )
  TimeEntry.create( entryDate:1.week.ago, hoursWorked:"test value", EntryType:0 )
  Approval.create( approverComment:"test string for approverComment", actionDate:1.week.ago, Status:0 )
  LeavePolicy.create( name:"test string for name", accrualRate:"test value", carryoverAllowed:true, maxBalance:"test value", LeaveCategory:0, AccrualUnit:0 )
  LeaveRequest.create( requestNumber:"test string for requestNumber", startDate:1.week.ago, endDate:1.week.ago, reason:"test string for reason", hours:"test value", Status:0 )
  PerformanceCycle.create( name:"test string for name", startDate:1.week.ago, endDate:1.week.ago, Status:0 )
  Goal.create( title:"test string for title", description:"test string for description", targetDate:1.week.ago, weight:"test value", Status:0 )
  PerformanceReview.create( reviewNumber:"test string for reviewNumber", reviewDate:1.week.ago, reviewerComments:"test string for reviewerComments", Rating:0, Status:0 )
  CompetencyRating.create( comment:"test string for comment", Rating:0 )
  TrainingCourse.create( code:"test string for code", title:"test string for title", durationHours:"test value", DeliveryMethod:0 )
  TrainingEnrollment.create( enrollmentNumber:"test string for enrollmentNumber", completionDate:1.week.ago, score:"test value", Status:0 )
  Certification.create( name:"test string for name", issuer:"test string for issuer", validFrom:1.week.ago, validTo:1.week.ago, credentialId:"test string for credentialId" )
  JobRequisition.create( requisitionNumber:"test string for requisitionNumber", title:"test string for title", openings:100, targetStartDate:1.week.ago, Status:0, Priority:0 )
  Candidate.create( name:"test value", email:"test value", phone:"test value", Source:0 )
  JobApplication.create( applicationNumber:"test string for applicationNumber", appliedDate:1.week.ago, resumeUrl:"test string for resumeUrl", Status:0 )
  Interview.create( interviewDate:1.week.ago, feedback:"test string for feedback", Stage:0, Result:0 )
  Screening.create( name:"test string for name", completedDate:1.week.ago, Status:0 )
  Offer.create( offerNumber:"test string for offerNumber", proposedStartDate:1.week.ago, baseSalary:"test value", signOnBonus:"test value", Status:0 )
  OnboardingTask.create( taskNumber:"test string for taskNumber", name:"test string for name", dueDate:1.week.ago, Status:0 )
  BackgroundCheck.create( checkNumber:"test string for checkNumber", provider:"test string for provider", completedDate:1.week.ago, Status:0 )
  Document.create( name:"test string for name", fileUrl:"test string for fileUrl", uploadedDate:1.week.ago, DocumentType:0 )
  Policy.create( policyNumber:"test string for policyNumber", name:"test string for name", effectiveDate:1.week.ago, description:"test string for description" )
  PolicyAcknowledgement.create( acknowledgementDate:1.week.ago, Status:0 )
  Termination.create( terminationNumber:"test string for terminationNumber", terminationDate:1.week.ago, notes:"test string for notes", eligibleForRehire:true, Reason:0, Type:0 )
  WorkAuthorization.create( country:"test string for country", expirationDate:1.week.ago, Status:0 )
  BankAccount.create( accountHolder:"test string for accountHolder", bankName:"test string for bankName", iban:"test string for iban", bic:"test string for bic", accountNumber:"test string for accountNumber", routingNumber:"test string for routingNumber" )
end
