package com.harbormaster.aggregate;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.axonframework.commandhandling.CommandHandler;
import org.axonframework.modelling.command.AggregateMember;
import org.axonframework.eventsourcing.EventSourcingHandler;
import org.axonframework.modelling.command.AggregateIdentifier;
import static org.axonframework.modelling.command.AggregateLifecycle.apply;
import org.axonframework.spring.stereotype.Aggregate;
import org.springframework.context.annotation.Profile;

/**
 * <h2>SettlementBatchAggregate</h2>
 * <p>
 * The SettlementBatch aggregate is the authoritative consistency boundary for all
 * branch-related operations. It validates incoming commands, enforces
 * business rules, maintains the integrity of the SettlementBatch domain, and emits
 * immutable domain events representing state changes.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateSettlementBatchCommand</li>
 *      <li>UpdateSettlementBatchCommand</li>
 *      <li>DeleteSettlementBatchCommand</li>
 *      </ul>
 *
 * <h3>Associations</h3>
 * <ul>
 *       <li>AssignProcessorToSettlementBatchCommand</li>
 *       <li>UnAssignProcessorFromSettlementBatchCommand</li>
 *       <li>AssignMerchantToSettlementBatchCommand</li>
 *       <li>UnAssignMerchantFromSettlementBatchCommand</li>
 *  </ul>
 *  <ul>
 *       <li>AssignPayoutsToSettlementBatchCommand</li>
 *       <li>RemovePayoutsFromSettlementBatchCommand</li>
 *   </ul>
 *
 * <p>
 * @author Harbormaster Dev Team
 * </p>
 *       <li>AssignTransactionsToSettlementBatchCommand</li>
 *       <li>RemoveTransactionsFromSettlementBatchCommand</li>
 *   </ul>
 *
 * <p>
 * @author Harbormaster Dev Team
 * </p>
 *
 *
 * <h3>Events Emitted</h3>
 *      <ul>
 *      <li>CreateSettlementBatchEvent</li>
 *      <li>UpdateSettlementBatchEvent</li>
 *      <li>DeleteSettlementBatchEvent</li>
   *       <li>AssignProcessorToSettlementBatchEvent</li>
 *       <li>UnAssignProcessorFromSettlementBatchEvent</li>
  *       <li>AssignMerchantToSettlementBatchEvent</li>
 *       <li>UnAssignMerchantFromSettlementBatchEvent</li>
   *       <li>AssignPayoutsToSettlementBatchEvent</li>
 *       <li>RemovePayoutsFromSettlementBatchEvent</li>
  *       <li>AssignTransactionsToSettlementBatchEvent</li>
 *       <li>RemoveTransactionsFromSettlementBatchEvent</li>
  *        </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Aggregate
public class SettlementBatchAggregate {  

	// -----------------------------------------
	// Axon requires an empty constructor
    // -----------------------------------------
    public SettlementBatchAggregate() {
    }

	// ----------------------------------------------
	// intrinsic command handlers
	// ----------------------------------------------
    @CommandHandler
    public SettlementBatchAggregate(CreateSettlementBatchCommand command) throws Exception {
    	LOGGER.info( "Handling command CreateSettlementBatchCommand" );
    	CreateSettlementBatchEvent event = new CreateSettlementBatchEvent(command.getSettlementBatchId(), command.getBatchId(), command.getPeriodStart(), command.getPeriodEnd(), command.getTotalVolume(), command.getTotalCount(), command.getStatus());
    	
        apply(event);
    }

    @CommandHandler
    public void handle(UpdateSettlementBatchCommand command) throws Exception {
    	LOGGER.info( "handling command UpdateSettlementBatchCommand" );
    	UpdateSettlementBatchEvent event = new UpdateSettlementBatchEvent(command.getSettlementBatchId(), command.getBatchId(), command.getPeriodStart(), command.getPeriodEnd(), command.getTotalVolume(), command.getTotalCount(), command.getProcessor(), command.getMerchant(), command.getPayouts(), command.getTransactions(), command.getStatus());        
    	
        apply(event);
    }

    @CommandHandler
    public void handle(DeleteSettlementBatchCommand command) throws Exception {
    	LOGGER.info( "Handling command DeleteSettlementBatchCommand" );
        apply(new DeleteSettlementBatchEvent(command.getSettlementBatchId()));
    }

	// ----------------------------------------------
	// association command handlers
	// ----------------------------------------------

    // single association commands
    @CommandHandler
    public void handle(AssignProcessorToSettlementBatchCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignProcessorToSettlementBatchCommand" );
    	
    	if (  processor != null && processor.getPaymentProcessorId() == command.getAssignment().getPaymentProcessorId() )
    		throw new ProcessingException( "Processor already assigned with id " + command.getAssignment().getPaymentProcessorId() );  
    		
        apply(new AssignProcessorToSettlementBatchEvent(command.getSettlementBatchId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignProcessorFromSettlementBatchCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignProcessorFromSettlementBatchCommand" );

    	if (  processor == null )
    		throw new ProcessingException( "Processor already has nothing assigned." );  

    	apply(new UnAssignProcessorFromSettlementBatchEvent(command.getSettlementBatchId()));
    }
    @CommandHandler
    public void handle(AssignMerchantToSettlementBatchCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignMerchantToSettlementBatchCommand" );
    	
    	if (  merchant != null && merchant.getMerchantId() == command.getAssignment().getMerchantId() )
    		throw new ProcessingException( "Merchant already assigned with id " + command.getAssignment().getMerchantId() );  
    		
        apply(new AssignMerchantToSettlementBatchEvent(command.getSettlementBatchId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignMerchantFromSettlementBatchCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignMerchantFromSettlementBatchCommand" );

    	if (  merchant == null )
    		throw new ProcessingException( "Merchant already has nothing assigned." );  

    	apply(new UnAssignMerchantFromSettlementBatchEvent(command.getSettlementBatchId()));
    }

    // multiple association commands
    @CommandHandler
    public void handle(AssignPayoutsToSettlementBatchCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignPayoutsToSettlementBatchCommand" );
    	
    	if ( payouts.contains( command.getAddTo() ) )
    		throw new ProcessingException( "Payouts already contains an entity with id " + command.getAddTo().getPayoutId() );

    	apply(new AssignPayoutsToSettlementBatchEvent(command.getSettlementBatchId(), command.getAddTo()));
    }

    @CommandHandler
    public void handle(RemovePayoutsFromSettlementBatchCommand command) throws Exception {
    	LOGGER.info( "Handling command RemovePayoutsFromSettlementBatchCommand" );
    	
    	if ( !payouts.contains( command.getRemoveFrom() ) )
    		throw new ProcessingException( "Payouts does not contain an entity with id " + command.getRemoveFrom().getPayoutId() );

        apply(new RemovePayoutsFromSettlementBatchEvent(command.getSettlementBatchId(), command.getRemoveFrom()));
    }
    @CommandHandler
    public void handle(AssignTransactionsToSettlementBatchCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignTransactionsToSettlementBatchCommand" );
    	
    	if ( transactions.contains( command.getAddTo() ) )
    		throw new ProcessingException( "Transactions already contains an entity with id " + command.getAddTo().getTransactionId() );

    	apply(new AssignTransactionsToSettlementBatchEvent(command.getSettlementBatchId(), command.getAddTo()));
    }

    @CommandHandler
    public void handle(RemoveTransactionsFromSettlementBatchCommand command) throws Exception {
    	LOGGER.info( "Handling command RemoveTransactionsFromSettlementBatchCommand" );
    	
    	if ( !transactions.contains( command.getRemoveFrom() ) )
    		throw new ProcessingException( "Transactions does not contain an entity with id " + command.getRemoveFrom().getTransactionId() );

        apply(new RemoveTransactionsFromSettlementBatchEvent(command.getSettlementBatchId(), command.getRemoveFrom()));
    }

	// ----------------------------------------------
	// intrinsic event source handlers
	// ----------------------------------------------
    @EventSourcingHandler
    void on(CreateSettlementBatchEvent event) {	
    	LOGGER.info( "Event sourcing CreateSettlementBatchEvent" );
    	this.settlementBatchId = event.getSettlementBatchId();
        this.batchId = event.getBatchId();
        this.periodStart = event.getPeriodStart();
        this.periodEnd = event.getPeriodEnd();
        this.totalVolume = event.getTotalVolume();
        this.totalCount = event.getTotalCount();
        this.status = event.getStatus();
    }
    
    @EventSourcingHandler
    void on(UpdateSettlementBatchEvent event) {
    	LOGGER.info( "Event sourcing classObject.getUpdateEventAlias()}" );
        this.batchId = event.getBatchId();
        this.periodStart = event.getPeriodStart();
        this.periodEnd = event.getPeriodEnd();
        this.totalVolume = event.getTotalVolume();
        this.totalCount = event.getTotalCount();
        this.processor = event.getProcessor();
        this.merchant = event.getMerchant();
        this.payouts = event.getPayouts();
        this.transactions = event.getTransactions();
        this.status = event.getStatus();
    }   

	// ----------------------------------------------
	// association event source handlers
	// ----------------------------------------------
	// single associations
    @EventSourcingHandler
    void on(AssignProcessorToSettlementBatchEvent event ) {	
    	LOGGER.info( "Event sourcing AssignProcessorToSettlementBatchEvent" );
    	this.processor = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignProcessorFromSettlementBatchEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignProcessorFromSettlementBatchEvent" );
		this.processor = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignMerchantToSettlementBatchEvent event ) {	
    	LOGGER.info( "Event sourcing AssignMerchantToSettlementBatchEvent" );
    	this.merchant = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignMerchantFromSettlementBatchEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignMerchantFromSettlementBatchEvent" );
		this.merchant = null;
	}

	// multiple associations
    @EventSourcingHandler
    void on(AssignPayoutsToSettlementBatchEvent event ) {
    	LOGGER.info( "Event sourcing AssignPayoutsToSettlementBatchEvent" );
    	this.payouts.add( event.getAddTo() );
    }

	@EventSourcingHandler
	void on(RemovePayoutsFromSettlementBatchEvent event ) {	
		LOGGER.info( "Event sourcing RemovePayoutsFromSettlementBatchEvent" );
		this.payouts.remove( event.getRemoveFrom() );
	}
	
	// multiple associations
    @EventSourcingHandler
    void on(AssignTransactionsToSettlementBatchEvent event ) {
    	LOGGER.info( "Event sourcing AssignTransactionsToSettlementBatchEvent" );
    	this.transactions.add( event.getAddTo() );
    }

	@EventSourcingHandler
	void on(RemoveTransactionsFromSettlementBatchEvent event ) {	
		LOGGER.info( "Event sourcing RemoveTransactionsFromSettlementBatchEvent" );
		this.transactions.remove( event.getRemoveFrom() );
	}
	

    // ------------------------------------------
    // attributes
    // ------------------------------------------
	
    @AggregateIdentifier
    private UUID settlementBatchId;
    
    private String batchId;
    private DateTime periodStart;
    private DateTime periodEnd;
    private Money totalVolume;
    private int totalCount;
    private SettlementStatus status;
    private PaymentProcessor processor = null;
    private Merchant merchant = null;
    private Set<Payout> payouts = new HashSet<>();
    private Set<Transaction> transactions = new HashSet<>();

    private static final Logger LOGGER 	= Logger.getLogger(SettlementBatchAggregate.class.getName());
}
