/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Healthcare Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;

import org.axonframework.commandhandling.gateway.CommandGateway;
import org.axonframework.queryhandling.QueryGateway;
import org.axonframework.queryhandling.QueryUpdateEmitter;
import org.axonframework.messaging.responsetypes.ResponseTypes;
import org.springframework.stereotype.Service;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.validator.*;

/**
 *
 * <h2>Patient business service</h2>
 *
 * <p>
 * This class implements the Service design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Patient related services in the case of a Patient business related service failing.</li>
 * <li>Exposes a simpler, uniform Patient interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Patient business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Healthcare Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core provider, patient, clinical, diagnostics, pharmacy, financial, and device-management capabilities.</td></tr>
 *          <tr><td>industry</td><td>Healthcare</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class PatientService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public PatientService()  {
	}

	@Override
	public void setApplicationContext(ApplicationContext ctx) throws BeansException {
		super.setApplicationContext(ctx);

		queryGateway 		= ctx.getBean(QueryGateway.class);
		commandGateway 		= ctx.getBean(CommandGateway.class);
		queryUpdateEmitter  = ctx.getBean(QueryUpdateEmitter.class);
		validator			= ctx.getBean(PatientValidator.class);
	}


   /**
	* Patient Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	PatientService
	*/
	public static PatientService getPatientInstance() {
		return( new PatientService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		CompletableFuture<UUID>
    */
	public CompletableFuture<UUID> createPatient( CreatePatientCommand command )
    throws ProcessingException, IllegalArgumentException {

		CompletableFuture<UUID> completableFuture = null;
				
		try {
			// --------------------------------------
        	// assign identity now if none
        	// -------------------------------------- 
			if ( command.getPatientId() == null )
				command.setPatientId( UUID.randomUUID() );
				
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    

    		// ---------------------------------------
    		// issue the CreatePatientCommand - by convention the future return value for a create command
        	// that is handled by the constructor of an aggregate will return the UUID 
    		// ---------------------------------------
        	completableFuture = commandGateway.send( command );
        	
			LOGGER.log( Level.INFO, "return from Command Gateway for CreatePatientCommand of Patient is " + command );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create Patient - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return completableFuture;
    }

   /**
    * Update the provided command.
    * @param		command UpdatePatientCommand
    * @return		CompletableFuture<Void>
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    */
    public CompletableFuture<Void> updatePatient( UpdatePatientCommand command ) 
    throws ProcessingException, IllegalArgumentException {
    	CompletableFuture<Void> completableFuture = null;
    	
    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	validator.validate( command );    

        	// --------------------------------------
        	// issue the UpdatePatientCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save Patient - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        
    	return completableFuture;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeletePatientCommand
    * @return		CompletableFuture<Void>
    * @exception 	ProcessingException
    */
    public CompletableFuture<Void> delete( DeletePatientCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
    	
    	CompletableFuture<Void> completableFuture = null;
    	
        try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    
        	
        	// --------------------------------------
        	// issue the DeletePatientCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete Patient using Id = "  + command.getPatientId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
        
        return completableFuture;
    }

    /**
     * Method to retrieve the Patient via PatientFetchOneSummary
     * @param 	summary PatientFetchOneSummary 
     * @return 	PatientFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public Patient getPatient( PatientFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "PatientFetchOneSummary arg cannot be null" );
    	
    	Patient entity = null;
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	validator.validate( summary );    
        	
        	// --------------------------------------
        	// use queryGateway to send request to Find a Patient
        	// --------------------------------------
        	CompletableFuture<Patient> futureEntity = queryGateway.query(new FindPatientQuery( new LoadPatientFilter( summary.getPatientId() ) ), ResponseTypes.instanceOf(Patient.class));
        	
        	entity = futureEntity.get();
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate Patient with id " + summary.getPatientId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all Patients
     *
     * @return 	List<Patient> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<Patient> getAllPatient() 
    throws ProcessingException {
        List<Patient> list = null;

        try {
        	CompletableFuture<List<Patient>> futureList = queryGateway.query(new FindAllPatientQuery(), ResponseTypes.multipleInstancesOf(Patient.class));
        	
        	list = futureList.get();
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all Patient";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }


    /**
     * add Appointment to Appointments 
     * @param		command AssignAppointmentsToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToAppointments( AssignAppointmentsToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		AppointmentService childDelegate 	= AppointmentService.getAppointmentInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getAppointmentId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Appointment as Appointments to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Appointment from Appointments
     * @param		command RemoveAppointmentsFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromAppointments( RemoveAppointmentsFromPatientCommand command ) throws ProcessingException {		
		
		AppointmentService childDelegate 	= AppointmentService.getAppointmentInstance();
		UUID childId = command.getRemoveFrom().getAppointmentId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Encounter to Encounters 
     * @param		command AssignEncountersToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToEncounters( AssignEncountersToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		EncounterService childDelegate 	= EncounterService.getEncounterInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getEncounterId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Encounter as Encounters to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Encounter from Encounters
     * @param		command RemoveEncountersFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromEncounters( RemoveEncountersFromPatientCommand command ) throws ProcessingException {		
		
		EncounterService childDelegate 	= EncounterService.getEncounterInstance();
		UUID childId = command.getRemoveFrom().getEncounterId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add CarePlan to CarePlans 
     * @param		command AssignCarePlansToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToCarePlans( AssignCarePlansToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		CarePlanService childDelegate 	= CarePlanService.getCarePlanInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getCarePlanId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a CarePlan as CarePlans to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove CarePlan from CarePlans
     * @param		command RemoveCarePlansFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromCarePlans( RemoveCarePlansFromPatientCommand command ) throws ProcessingException {		
		
		CarePlanService childDelegate 	= CarePlanService.getCarePlanInstance();
		UUID childId = command.getRemoveFrom().getCarePlanId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Allergy to Allergies 
     * @param		command AssignAllergiesToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToAllergies( AssignAllergiesToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		AllergyService childDelegate 	= AllergyService.getAllergyInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getAllergyId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Allergy as Allergies to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Allergy from Allergies
     * @param		command RemoveAllergiesFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromAllergies( RemoveAllergiesFromPatientCommand command ) throws ProcessingException {		
		
		AllergyService childDelegate 	= AllergyService.getAllergyInstance();
		UUID childId = command.getRemoveFrom().getAllergyId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Condition to Conditions 
     * @param		command AssignConditionsToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToConditions( AssignConditionsToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		ConditionService childDelegate 	= ConditionService.getConditionInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getConditionId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Condition as Conditions to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Condition from Conditions
     * @param		command RemoveConditionsFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromConditions( RemoveConditionsFromPatientCommand command ) throws ProcessingException {		
		
		ConditionService childDelegate 	= ConditionService.getConditionInstance();
		UUID childId = command.getRemoveFrom().getConditionId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add MedicationOrder to MedicationOrders 
     * @param		command AssignMedicationOrdersToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToMedicationOrders( AssignMedicationOrdersToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		MedicationOrderService childDelegate 	= MedicationOrderService.getMedicationOrderInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getMedicationOrderId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a MedicationOrder as MedicationOrders to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove MedicationOrder from MedicationOrders
     * @param		command RemoveMedicationOrdersFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromMedicationOrders( RemoveMedicationOrdersFromPatientCommand command ) throws ProcessingException {		
		
		MedicationOrderService childDelegate 	= MedicationOrderService.getMedicationOrderInstance();
		UUID childId = command.getRemoveFrom().getMedicationOrderId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add LaboratoryOrder to LabOrders 
     * @param		command AssignLabOrdersToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToLabOrders( AssignLabOrdersToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		LaboratoryOrderService childDelegate 	= LaboratoryOrderService.getLaboratoryOrderInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getLaboratoryOrderId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a LaboratoryOrder as LabOrders to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove LaboratoryOrder from LabOrders
     * @param		command RemoveLabOrdersFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromLabOrders( RemoveLabOrdersFromPatientCommand command ) throws ProcessingException {		
		
		LaboratoryOrderService childDelegate 	= LaboratoryOrderService.getLaboratoryOrderInstance();
		UUID childId = command.getRemoveFrom().getLaboratoryOrderId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add ImagingOrder to ImagingOrders 
     * @param		command AssignImagingOrdersToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToImagingOrders( AssignImagingOrdersToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		ImagingOrderService childDelegate 	= ImagingOrderService.getImagingOrderInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getImagingOrderId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a ImagingOrder as ImagingOrders to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove ImagingOrder from ImagingOrders
     * @param		command RemoveImagingOrdersFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromImagingOrders( RemoveImagingOrdersFromPatientCommand command ) throws ProcessingException {		
		
		ImagingOrderService childDelegate 	= ImagingOrderService.getImagingOrderInstance();
		UUID childId = command.getRemoveFrom().getImagingOrderId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Coverage to Coverages 
     * @param		command AssignCoveragesToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToCoverages( AssignCoveragesToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		CoverageService childDelegate 	= CoverageService.getCoverageInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getCoverageId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Coverage as Coverages to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Coverage from Coverages
     * @param		command RemoveCoveragesFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromCoverages( RemoveCoveragesFromPatientCommand command ) throws ProcessingException {		
		
		CoverageService childDelegate 	= CoverageService.getCoverageInstance();
		UUID childId = command.getRemoveFrom().getCoverageId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Claim to Claims 
     * @param		command AssignClaimsToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToClaims( AssignClaimsToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		ClaimService childDelegate 	= ClaimService.getClaimInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getClaimId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Claim as Claims to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Claim from Claims
     * @param		command RemoveClaimsFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromClaims( RemoveClaimsFromPatientCommand command ) throws ProcessingException {		
		
		ClaimService childDelegate 	= ClaimService.getClaimInstance();
		UUID childId = command.getRemoveFrom().getClaimId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add MedicalDevice to Devices 
     * @param		command AssignDevicesToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToDevices( AssignDevicesToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		MedicalDeviceService childDelegate 	= MedicalDeviceService.getMedicalDeviceInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getMedicalDeviceId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a MedicalDevice as Devices to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove MedicalDevice from Devices
     * @param		command RemoveDevicesFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDevices( RemoveDevicesFromPatientCommand command ) throws ProcessingException {		
		
		MedicalDeviceService childDelegate 	= MedicalDeviceService.getMedicalDeviceInstance();
		UUID childId = command.getRemoveFrom().getMedicalDeviceId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add Observation to Observations 
     * @param		command AssignObservationsToPatientCommand
     * @exception	ProcessingException
     */     
	public void addToObservations( AssignObservationsToPatientCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getPatientId() );

		ObservationService childDelegate 	= ObservationService.getObservationInstance();
		PatientService parentDelegate = PatientService.getPatientInstance();		
		UUID childId = command.getAddTo().getObservationId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Observation as Observations to Patient" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Observation from Observations
     * @param		command RemoveObservationsFromPatientCommand
     * @exception	ProcessingException
     */     	
	public void removeFromObservations( RemoveObservationsFromPatientCommand command ) throws ProcessingException {		
		
		ObservationService childDelegate 	= ObservationService.getObservationInstance();
		UUID childId = command.getRemoveFrom().getObservationId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}



	/**
	 * Internal helper method to load the root 
	 * 
	 * @param		id	UUID
	 * @return		Patient
	 */
	protected Patient load( UUID id ) throws ProcessingException {
		patient = PatientService.getPatientInstance().getPatient( new PatientFetchOneSummary(id) );	
		return patient;
	}


//************************************************************************
// Attributes
//************************************************************************
	private QueryGateway queryGateway;
	private CommandGateway commandGateway;
	private QueryUpdateEmitter queryUpdateEmitter;
	private PatientValidator validator;
	private Patient patient 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(PatientService.class.getName());
    
}
