/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Aerospace Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * RegistrationRestController as REST API
 *
 * <p>Exposes REST endpoints for the Registration entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Aerospace Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>Metadata describing this Aerospace HCIDL document.</td></tr>
 *          <tr><td>industry</td><td>Aerospace</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	RegistrationBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateRegistrationCommand</li>
 *      <li></li>UpdateRegistrationCommand</li>
 *      <liDeleteRegistrationCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Registration")
public class RegistrationRestController extends BaseSpringRestController {

	public RegistrationRestController( RegistrationService service ) {
		this.service = service;
	}
	
    /**
     * Handles create a Registration.  if not key provided, calls create, otherwise calls save
     * @param		Registration	registration
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateRegistrationCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = service.createRegistration( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a Registration.  if no key provided, calls create, otherwise calls save
     * @param		Registration registration
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateRegistrationCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateRegistrationCommand
			// -----------------------------------------------
			completableFuture = service.updateRegistration(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "RegistrationController:update() - successfully update Registration - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a Registration entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteRegistrationCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	RegistrationService delegate = service;

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Registration with key " + command.getRegistrationId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a Registration using a UUID
     * @param		UUID uuid 
     * @return		Registration
     */    
    @GetMapping("/load")
    public Registration load( @RequestParam(required=true) UUID uuid ) {    	
    	Registration entity = null;

    	try {  
    		entity = service.getRegistration( new RegistrationFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Registration using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Registration business objects
     * @return		Set<Registration>
     */
    @GetMapping("/")
    public List<Registration> loadAll() {                
    	List<Registration> registrationList = null;
        
    	try {
            // load the Registration
            registrationList = service.getAllRegistration();
            
            if ( registrationList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Registrations" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Registrations ", exc );
        	return null;
        }

        return registrationList;
                            
    }

    /**
     * save Aircraft on Registration
     * @param		command AssignAircraftToRegistrationCommand
     */     
	@PutMapping("/assignAircraft")
	public void assignAircraft( @RequestBody AssignAircraftToRegistrationCommand command ) {
		try {
			service.assignAircraft( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Aircraft", exc );
        }
	}

    /**
     * unassign Aircraft on Registration
     * @param		 command UnAssignAircraftFromRegistrationCommand
     */     
	@PutMapping("/unAssignAircraft")
	public void unAssignAircraft( @RequestBody(required=true)  UnAssignAircraftFromRegistrationCommand command ) {
		try {
			service.unAssignAircraft( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Aircraft", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Registration registration = null;
	protected RegistrationService service = null;
	private static final Logger LOGGER = Logger.getLogger(RegistrationRestController.class.getName());
    
}
