/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * CRM Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.springframework.util.Assert.state;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;
import com.harbormaster.subscriber.*;

/**
 * <h2>CampaignMemberTest</h2>
 * <p>
 * Junit test class for entity CampaignMember.  Handle the full lifecycle as it relates to persistence. Leverages
 * the CampaignMemberService and a CampaignMemberSubscriber to test everything under a MVC framework which includes the
 * CampaignMemberAggregate and related commands, queries, and events.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>CRM Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core CRM capabilities across accounts, contacts, leads, opportunities, pricing, quotes, orders, service cases, activities, and campaigns.</td></tr>
 *          <tr><td>industry</td><td>CRM</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 * 		CampaignMemberService
 * 	    CampaignMemberSubscriber
 *
 * <h3>Methods</h3>
 *      <ul>
 *      <li>read</li>
 *      <li>update</li>
 *      <li>delete</li>
 *      </ul>
 *
 * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class CampaignMemberTest {

    // ------------------------------------
	// default constructor
    // ------------------------------------
	public CampaignMemberTest() {
		subscriber = new CampaignMemberSubscriber();
	}

	// test methods
	@Test
	/*
	 * Initiate CampaignMemberTest.
	 */
	public void startTest() throws Throwable {
		try {
			LOGGER.info("**********************************************************");
			LOGGER.info("Beginning test on CampaignMember...");
			LOGGER.info("**********************************************************\n");
			
			// ---------------------------------------------
			// jumpstart process
			// ---------------------------------------------
			jumpStart();
			
		} catch (Throwable e) {
			throw e;
		} finally {
		}
	}

	/** 
	 * jumpstart the process by instantiating2 CampaignMember
	 */
	protected void jumpStart() throws Throwable {
		LOGGER.info( "\n======== create instances to get the ball rolling  ======== ");

		campaignMemberId = CampaignMemberService.getCampaignMemberInstance()
		.createCampaignMember( generateNewCommand() )
		.get();

		// ---------------------------------------------
		// set up query subscriptions after the 1st create
		// ---------------------------------------------
		testingStep = "create";
		setUpQuerySubscriptions();

		CampaignMemberService.getCampaignMemberInstance()
				.createCampaignMember( generateNewCommand() )
				.get();

	}

	/** 
	 * Set up query subscriptions
	 */
	protected void setUpQuerySubscriptions() throws Throwable {
		LOGGER.info( "\n======== Setting Up Query Subscriptions ======== ");
			
		try {            
			subscriber.campaignMemberSubscribe().updates().subscribe(
					  successValue -> {
						  LOGGER.info(successValue.toString());
						  try {
							  LOGGER.info("GetAll update received for CampaignMember : " + successValue.getCampaignMemberId());
							  if (successValue.getCampaignMemberId().equals(campaignMemberId)) {
								  if (testingStep.equals("create")) {
									  testingStep = "update";
									  update();
								  } else if (testingStep.equals("delete")) {
									  testingStep = "complete";
									  state( getAll().size() == sizeOfCampaignMemberList - 1 , "value not deleted from list");
									  LOGGER.info("**********************************************************");
									  LOGGER.info("CampaignMember test completed successfully...");
									  LOGGER.info("**********************************************************\n");
								  }
							  }
						  } catch( Throwable exc ) {
							  LOGGER.warning( exc.getMessage() );
						  }
					  },
					  error -> LOGGER.warning(error.getMessage()),
					  () -> LOGGER.info("Subscription on campaignMember consumed")
					);
			subscriber.campaignMemberSubscribe( campaignMemberId ).updates().subscribe(
					  successValue -> {
						  LOGGER.info(successValue.toString());
						  try {
							  LOGGER.info("GetOne update received for CampaignMember : " + successValue.getCampaignMemberId() + " in step " + testingStep);
							  testingStep = "delete";
							  sizeOfCampaignMemberList = getAll().size();
							  delete();
						  } catch( Throwable exc ) {
							  LOGGER.warning( exc.getMessage() );
						  }
					  },
					  error -> LOGGER.warning(error.getMessage()),
					  () -> LOGGER.info("Subscription on campaignMember for campaignMemberId consumed")

					);
			

			}
			catch (Exception e) {
				LOGGER.warning( e.getMessage() );
				throw e;
			}
		}
		
		/** 
	 * read a CampaignMember. 
	 */
	protected CampaignMember read() throws Throwable {
		LOGGER.info( "\n======== READ ======== ");
		LOGGER.info( "-- Reading a previously created CampaignMember" );

		CampaignMember entity = null;
		StringBuilder msg = new StringBuilder( "-- Failed to read CampaignMember with primary key" );
		msg.append( campaignMemberId );
		
		CampaignMemberFetchOneSummary fetchOneSummary = new CampaignMemberFetchOneSummary( campaignMemberId );

		try {
			entity = CampaignMemberService.getCampaignMemberInstance().getCampaignMember( fetchOneSummary );

			assertNotNull( entity,msg.toString() );

			LOGGER.info( "-- Successfully found CampaignMember " + entity.toString() );
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : " + e );

			throw e;
		}
		
		return entity;
	}

	/** 
	 * updating a CampaignMember.
	 */
	protected void update() throws Throwable {
		LOGGER.info( "\n======== UPDATE ======== ");
		LOGGER.info( "-- Attempting to update a CampaignMember." );

		StringBuilder msg = new StringBuilder( "Failed to update a CampaignMember : " );        
		CampaignMember entity = read();
		UpdateCampaignMemberCommand command = generateUpdateCommand();
		command.setCampaignMemberId(entity.getCampaignMemberId());

		try {            
			assertNotNull( entity, msg.toString() );

			LOGGER.info( "-- Now updating the created CampaignMember." );

			// for use later on...
			campaignMemberId = entity.getCampaignMemberId();

			CampaignMemberService proxy = CampaignMemberService.getCampaignMemberInstance();  

			proxy.updateCampaignMember( command ).get();

			LOGGER.info( "-- Successfully saved CampaignMember - " + entity.toString() );
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : primarykey = " + campaignMemberId + " : command -" +  command + " : " + e );

			throw e;
		}
	}

	/** 
	 * delete a CampaignMember.
	 */
	protected void delete() throws Throwable {
		LOGGER.info( "\n======== DELETE ======== ");
		LOGGER.info( "-- Deleting a previously created CampaignMember." );

		CampaignMember entity = null;
		
		try{
		    entity = read(); 
			LOGGER.info( "-- Successfully read CampaignMember with id " + campaignMemberId );            
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( "-- Failed to read CampaignMember with id " + campaignMemberId );

			throw e;
		}

		try{
			CampaignMemberService.getCampaignMemberInstance().delete( new DeleteCampaignMemberCommand( entity.getCampaignMemberId() ) ).get();
			LOGGER.info( "-- Successfully deleted CampaignMember with id " + campaignMemberId );            
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( "-- Failed to delete CampaignMember with id " + campaignMemberId );

			throw e;
		}
	}

	/**
	 * get all CampaignMembers.
	 */
	protected List<CampaignMember> getAll() throws Throwable {    
		LOGGER.info( "======== GETALL ======== ");
		LOGGER.info( "-- Retrieving Collection of CampaignMembers:" );

		StringBuilder msg = new StringBuilder( "-- Failed to get all CampaignMember : " );        
		List<CampaignMember> collection  = new ArrayList<>();

		try {
			// call the static get method on the CampaignMemberService
			collection = CampaignMemberService.getCampaignMemberInstance().getAllCampaignMember();
			assertNotNull( collection, "An Empty collection of CampaignMember was incorrectly returned.");
			
			// Now print out the values
			CampaignMember entity = null;            
			Iterator<CampaignMember> iter = collection.iterator();
			int index = 1;

			while( iter.hasNext() ) {
				// Retrieve the entity   
				entity = iter.next();

				assertNotNull( entity,"-- null entity in Collection." );
				assertNotNull( entity.getCampaignMemberId(), "-- entity in Collection has a null primary key" );        

				LOGGER.info( " - " + String.valueOf(index) + ". " + entity.toString() );
				index++;
			}
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : " + e );

			throw e;
		}
		
		return collection;			
	}

	/**
	 * Assigns a common log handler for each test class in the suite 
	 * in the event log output needs to go elsewhere
	 * 
	 * @param		handler	Handler
	 * @return		CampaignMemberTest
	 */
	protected CampaignMemberTest setHandler(Handler handler) {
		if ( handler != null )
			LOGGER.addHandler(handler); 
		return this;
	}

	/**
	 * Returns a new populated CampaignMember
	 * 
	 * @return CreateCampaignMemberCommand alias
	 */
	protected CreateCampaignMemberCommand generateNewCommand() {
        CreateCampaignMemberCommand command = new CreateCampaignMemberCommand( null,  new Boolean(true),  CampaignMemberStatus.values()[0],  CampaignMemberType.values()[0] );
		
		return( command );
	}

		/**
		 * Returns a new populated CampaignMember
		 * 
		 * @return UpdateCampaignMemberCommand alias
		 */
	protected UpdateCampaignMemberCommand generateUpdateCommand() {
	        UpdateCampaignMemberCommand command = new UpdateCampaignMemberCommand( null,  new Boolean(true),  null,  null,  null,  CampaignMemberStatus.values()[0],  CampaignMemberType.values()[0] );
			
			return( command );
		}
	//-----------------------------------------------------
	// attributes 
	//-----------------------------------------------------
	protected UUID campaignMemberId = null;
	protected CampaignMemberSubscriber subscriber = null;
	private final String unexpectedErrorMsg = ":::::::::::::: Unexpected Error :::::::::::::::::";
	private final Logger LOGGER = Logger.getLogger(CampaignMemberTest.class.getName());
	private String testingStep = "";
	private Integer sizeOfCampaignMemberList = 0;
}
