#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.aerospaceOnDjango
requirements.txt=.aerospaceOnDjango
admin.py=.aerospaceOnDjango
apps.py=.aerospaceOnDjango
appUrls.py=.aerospaceOnDjango
setup.py=.aerospaceOnDjango
README.rst=.aerospaceOnDjango
LICENSE=.aerospaceOnDjango
Dockerfile=.aerospaceOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.aerospaceOnDjango.mainsite
wsgi.py=.aerospaceOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.aerospaceOnDjango.models
__classes__Delegate.py=.aerospaceOnDjango.delegates
__classes__Test.py=.aerospaceOnDjango.tests
__classes__View.py=.aerospaceOnDjango.views
__classes__Urls.py=.aerospaceOnDjango.urls
__enums__.py=.aerospaceOnDjango.models
Exceptions.py=.aerospaceOnDjango.exceptions
empty.doc=.aerospaceOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.aerospaceOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.aerospaceOnDjango.mainsite,.aerospaceOnDjango.models,.aerospaceOnDjango.delegates,.aerospaceOnDjango.tests,.aerospaceOnDjango.views,.aerospaceOnDjango.urls,.aerospaceOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json