#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.ecommerceOnDjango
requirements.txt=.ecommerceOnDjango
admin.py=.ecommerceOnDjango
apps.py=.ecommerceOnDjango
appUrls.py=.ecommerceOnDjango
setup.py=.ecommerceOnDjango
README.rst=.ecommerceOnDjango
LICENSE=.ecommerceOnDjango
Dockerfile=.ecommerceOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.ecommerceOnDjango.mainsite
wsgi.py=.ecommerceOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.ecommerceOnDjango.models
__classes__Delegate.py=.ecommerceOnDjango.delegates
__classes__Test.py=.ecommerceOnDjango.tests
__classes__View.py=.ecommerceOnDjango.views
__classes__Urls.py=.ecommerceOnDjango.urls
__enums__.py=.ecommerceOnDjango.models
Exceptions.py=.ecommerceOnDjango.exceptions
empty.doc=.ecommerceOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.ecommerceOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.ecommerceOnDjango.mainsite,.ecommerceOnDjango.models,.ecommerceOnDjango.delegates,.ecommerceOnDjango.tests,.ecommerceOnDjango.views,.ecommerceOnDjango.urls,.ecommerceOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json