/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Analytics Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * RecommendationScenarioRestController as REST API
 *
 * <p>Exposes REST endpoints for the RecommendationScenario entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	RecommendationScenarioBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateRecommendationScenarioCommand</li>
 *      <li></li>UpdateRecommendationScenarioCommand</li>
 *      <liDeleteRecommendationScenarioCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/RecommendationScenario")
public class RecommendationScenarioRestController extends BaseSpringRestController {

	public RecommendationScenarioRestController( RecommendationScenarioService service ) {
		this.service = service;
	}
	
    /**
     * Handles create a RecommendationScenario.  if not key provided, calls create, otherwise calls save
     * @param		RecommendationScenario	recommendationScenario
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateRecommendationScenarioCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = service.createRecommendationScenario( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a RecommendationScenario.  if no key provided, calls create, otherwise calls save
     * @param		RecommendationScenario recommendationScenario
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateRecommendationScenarioCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateRecommendationScenarioCommand
			// -----------------------------------------------
			completableFuture = service.updateRecommendationScenario(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "RecommendationScenarioController:update() - successfully update RecommendationScenario - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a RecommendationScenario entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteRecommendationScenarioCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	RecommendationScenarioService delegate = service;

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted RecommendationScenario with key " + command.getRecommendationScenarioId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a RecommendationScenario using a UUID
     * @param		UUID uuid 
     * @return		RecommendationScenario
     */    
    @GetMapping("/load")
    public RecommendationScenario load( @RequestParam(required=true) UUID uuid ) {    	
    	RecommendationScenario entity = null;

    	try {  
    		entity = service.getRecommendationScenario( new RecommendationScenarioFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load RecommendationScenario using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all RecommendationScenario business objects
     * @return		Set<RecommendationScenario>
     */
    @GetMapping("/")
    public List<RecommendationScenario> loadAll() {                
    	List<RecommendationScenario> recommendationScenarioList = null;
        
    	try {
            // load the RecommendationScenario
            recommendationScenarioList = service.getAllRecommendationScenario();
            
            if ( recommendationScenarioList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all RecommendationScenarios" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all RecommendationScenarios ", exc );
        	return null;
        }

        return recommendationScenarioList;
                            
    }


    /**
     * save Models on RecommendationScenario
     * @param		command AssignModelsToRecommendationScenarioCommand
     */     
	@PutMapping("/addToModels")
	public void addToModels( @RequestBody(required=true) AssignModelsToRecommendationScenarioCommand command ) {
		try {
			service.addToModels( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Models", exc );
		}
	}

    /**
     * remove Models on RecommendationScenario
     * @param		command RemoveModelsFromRecommendationScenarioCommand
     */     	
	@PutMapping("/removeFromModels")
	public void removeFromModels( 	@RequestBody(required=true) RemoveModelsFromRecommendationScenarioCommand command )
	{		
		try {
			service.removeFromModels( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Models", exc );
		}
	}

    /**
     * save Datasets on RecommendationScenario
     * @param		command AssignDatasetsToRecommendationScenarioCommand
     */     
	@PutMapping("/addToDatasets")
	public void addToDatasets( @RequestBody(required=true) AssignDatasetsToRecommendationScenarioCommand command ) {
		try {
			service.addToDatasets( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Datasets", exc );
		}
	}

    /**
     * remove Datasets on RecommendationScenario
     * @param		command RemoveDatasetsFromRecommendationScenarioCommand
     */     	
	@PutMapping("/removeFromDatasets")
	public void removeFromDatasets( 	@RequestBody(required=true) RemoveDatasetsFromRecommendationScenarioCommand command )
	{		
		try {
			service.removeFromDatasets( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Datasets", exc );
		}
	}

    /**
     * save Experiments on RecommendationScenario
     * @param		command AssignExperimentsToRecommendationScenarioCommand
     */     
	@PutMapping("/addToExperiments")
	public void addToExperiments( @RequestBody(required=true) AssignExperimentsToRecommendationScenarioCommand command ) {
		try {
			service.addToExperiments( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Experiments", exc );
		}
	}

    /**
     * remove Experiments on RecommendationScenario
     * @param		command RemoveExperimentsFromRecommendationScenarioCommand
     */     	
	@PutMapping("/removeFromExperiments")
	public void removeFromExperiments( 	@RequestBody(required=true) RemoveExperimentsFromRecommendationScenarioCommand command )
	{		
		try {
			service.removeFromExperiments( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Experiments", exc );
		}
	}

    /**
     * save Alerts on RecommendationScenario
     * @param		command AssignAlertsToRecommendationScenarioCommand
     */     
	@PutMapping("/addToAlerts")
	public void addToAlerts( @RequestBody(required=true) AssignAlertsToRecommendationScenarioCommand command ) {
		try {
			service.addToAlerts( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Alerts", exc );
		}
	}

    /**
     * remove Alerts on RecommendationScenario
     * @param		command RemoveAlertsFromRecommendationScenarioCommand
     */     	
	@PutMapping("/removeFromAlerts")
	public void removeFromAlerts( 	@RequestBody(required=true) RemoveAlertsFromRecommendationScenarioCommand command )
	{		
		try {
			service.removeFromAlerts( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Alerts", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected RecommendationScenario recommendationScenario = null;
	protected RecommendationScenarioService service = null;
	private static final Logger LOGGER = Logger.getLogger(RecommendationScenarioRestController.class.getName());
    
}
