#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.hrOnDjango
requirements.txt=.hrOnDjango
admin.py=.hrOnDjango
apps.py=.hrOnDjango
appUrls.py=.hrOnDjango
setup.py=.hrOnDjango
README.rst=.hrOnDjango
LICENSE=.hrOnDjango
Dockerfile=.hrOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.hrOnDjango.mainsite
wsgi.py=.hrOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.hrOnDjango.models
__classes__Delegate.py=.hrOnDjango.delegates
__classes__Test.py=.hrOnDjango.tests
__classes__View.py=.hrOnDjango.views
__classes__Urls.py=.hrOnDjango.urls
__enums__.py=.hrOnDjango.models
Exceptions.py=.hrOnDjango.exceptions
empty.doc=.hrOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.hrOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.hrOnDjango.mainsite,.hrOnDjango.models,.hrOnDjango.delegates,.hrOnDjango.tests,.hrOnDjango.views,.hrOnDjango.urls,.hrOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json