package com.harbormaster.command;

import java.util.*;

import org.axonframework.modelling.command.Repository;

import org.axonframework.commandhandling.CommandHandler;
import org.springframework.stereotype.Component;

import com.harbormaster.aggregate.*;
import com.harbormaster.api.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;

/**
 * Command handler for AudienceSegment as outlined for the CQRS pattern.  All creates, updates, deletes and other writes 
 * related to AudienceSegment are handled here as external events are delegated to an associated Aggregate.
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Advertising Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model for advertising planning, buying, trafficking, delivery, and measurement.</td></tr>
 *          <tr><td>industry</td><td>Advertising</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * Services Used
 *
 *  	Repository<AudienceSegmentAggregate>
 *
 * Produces
 *
 *      application/json
 *
 * Commands Accepted
 *
 *      CreateAudienceSegmentCommand
 *      UpdateAudienceSegmentCommand
 *      DeleteAudienceSegmentCommand
 *
 * @author Harbormaster Dev Team
 *
 */
@Component
class AudienceSegmentCommandHandler {

    public AudienceSegmentCommandHandler( Repository<AudienceSegmentAggregate> repository ) {
    	super();
    	this.aggregateRepository = repository;	
    }
    
    @CommandHandler
    public void handle(CreateAudienceSegmentCommand command) throws Exception {
    	
    	// --------------------------------------
    	// validate the create command
    	// --------------------------------------    	
		AudienceSegmentValidator.getInstance().validate( command );
		
    	// --------------------------------------
    	// delegate to the aggregate
    	// -------------------------------------- 
    	aggregateRepository.newInstance(() -> new AudienceSegmentAggregate(command));
    }


    @CommandHandler
    public void handle(UpdateAudienceSegmentCommand command) throws Exception {
    	// --------------------------------------
    	// validate the update command
    	// --------------------------------------    	
		AudienceSegmentValidator.getInstance().validate( command );

    	// --------------------------------------
    	// delegate to the aggregate
    	// --------------------------------------
    	aggregateRepository.newInstance(() -> new AudienceSegmentAggregate(command));
    }

    
    @CommandHandler
    public void handle(DeleteAudienceSegmentCommand command) throws Exception {
    	// --------------------------------------
    	// validate the delete command
    	// --------------------------------------    	
		AudienceSegmentValidator.getInstance().validate( command );    
		
    	// --------------------------------------
    	// delegate to the aggregate
    	// --------------------------------------
    	aggregateRepository.newInstance(() -> new AudienceSegmentAggregate(command));
    }
    
    // attributes
    private final Repository<AudienceSegmentAggregate> aggregateRepository;
}