/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Advertising Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.springframework.util.Assert.state;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;
import com.harbormaster.subscriber.*;

/**
 * <h2>LineItemTest</h2>
 * <p>
 * Junit test class for entity LineItem.  Handle the full lifecycle as it relates to persistence. Leverages
 * the LineItemService and a LineItemSubscriber to test everything under a MVC framework which includes the
 * LineItemAggregate and related commands, queries, and events.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Advertising Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model for advertising planning, buying, trafficking, delivery, and measurement.</td></tr>
 *          <tr><td>industry</td><td>Advertising</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 * 		LineItemService
 * 	    LineItemSubscriber
 *
 * <h3>Methods</h3>
 *      <ul>
 *      <li>read</li>
 *      <li>update</li>
 *      <li>delete</li>
 *      </ul>
 *
 * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class LineItemTest {

    // ------------------------------------
	// default constructor
    // ------------------------------------
	public LineItemTest() {
		subscriber = new LineItemSubscriber();
	}

	// test methods
	@Test
	/*
	 * Initiate LineItemTest.
	 */
	public void startTest() throws Throwable {
		try {
			LOGGER.info("**********************************************************");
			LOGGER.info("Beginning test on LineItem...");
			LOGGER.info("**********************************************************\n");
			
			// ---------------------------------------------
			// jumpstart process
			// ---------------------------------------------
			jumpStart();
			
		} catch (Throwable e) {
			throw e;
		} finally {
		}
	}

	/** 
	 * jumpstart the process by instantiating2 LineItem
	 */
	protected void jumpStart() throws Throwable {
		LOGGER.info( "\n======== create instances to get the ball rolling  ======== ");

		lineItemId = LineItemService.getLineItemInstance()
		.createLineItem( generateNewCommand() )
		.get();

		// ---------------------------------------------
		// set up query subscriptions after the 1st create
		// ---------------------------------------------
		testingStep = "create";
		setUpQuerySubscriptions();

		LineItemService.getLineItemInstance()
				.createLineItem( generateNewCommand() )
				.get();

	}

	/** 
	 * Set up query subscriptions
	 */
	protected void setUpQuerySubscriptions() throws Throwable {
		LOGGER.info( "\n======== Setting Up Query Subscriptions ======== ");
			
		try {            
			subscriber.lineItemSubscribe().updates().subscribe(
					  successValue -> {
						  LOGGER.info(successValue.toString());
						  try {
							  LOGGER.info("GetAll update received for LineItem : " + successValue.getLineItemId());
							  if (successValue.getLineItemId().equals(lineItemId)) {
								  if (testingStep.equals("create")) {
									  testingStep = "update";
									  update();
								  } else if (testingStep.equals("delete")) {
									  testingStep = "complete";
									  state( getAll().size() == sizeOfLineItemList - 1 , "value not deleted from list");
									  LOGGER.info("**********************************************************");
									  LOGGER.info("LineItem test completed successfully...");
									  LOGGER.info("**********************************************************\n");
								  }
							  }
						  } catch( Throwable exc ) {
							  LOGGER.warning( exc.getMessage() );
						  }
					  },
					  error -> LOGGER.warning(error.getMessage()),
					  () -> LOGGER.info("Subscription on lineItem consumed")
					);
			subscriber.lineItemSubscribe( lineItemId ).updates().subscribe(
					  successValue -> {
						  LOGGER.info(successValue.toString());
						  try {
							  LOGGER.info("GetOne update received for LineItem : " + successValue.getLineItemId() + " in step " + testingStep);
							  testingStep = "delete";
							  sizeOfLineItemList = getAll().size();
							  delete();
						  } catch( Throwable exc ) {
							  LOGGER.warning( exc.getMessage() );
						  }
					  },
					  error -> LOGGER.warning(error.getMessage()),
					  () -> LOGGER.info("Subscription on lineItem for lineItemId consumed")

					);
			

			}
			catch (Exception e) {
				LOGGER.warning( e.getMessage() );
				throw e;
			}
		}
		
		/** 
	 * read a LineItem. 
	 */
	protected LineItem read() throws Throwable {
		LOGGER.info( "\n======== READ ======== ");
		LOGGER.info( "-- Reading a previously created LineItem" );

		LineItem entity = null;
		StringBuilder msg = new StringBuilder( "-- Failed to read LineItem with primary key" );
		msg.append( lineItemId );
		
		LineItemFetchOneSummary fetchOneSummary = new LineItemFetchOneSummary( lineItemId );

		try {
			entity = LineItemService.getLineItemInstance().getLineItem( fetchOneSummary );

			assertNotNull( entity,msg.toString() );

			LOGGER.info( "-- Successfully found LineItem " + entity.toString() );
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : " + e );

			throw e;
		}
		
		return entity;
	}

	/** 
	 * updating a LineItem.
	 */
	protected void update() throws Throwable {
		LOGGER.info( "\n======== UPDATE ======== ");
		LOGGER.info( "-- Attempting to update a LineItem." );

		StringBuilder msg = new StringBuilder( "Failed to update a LineItem : " );        
		LineItem entity = read();
		UpdateLineItemCommand command = generateUpdateCommand();
		command.setLineItemId(entity.getLineItemId());

		try {            
			assertNotNull( entity, msg.toString() );

			LOGGER.info( "-- Now updating the created LineItem." );

			// for use later on...
			lineItemId = entity.getLineItemId();

			LineItemService proxy = LineItemService.getLineItemInstance();  

			proxy.updateLineItem( command ).get();

			LOGGER.info( "-- Successfully saved LineItem - " + entity.toString() );
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : primarykey = " + lineItemId + " : command -" +  command + " : " + e );

			throw e;
		}
	}

	/** 
	 * delete a LineItem.
	 */
	protected void delete() throws Throwable {
		LOGGER.info( "\n======== DELETE ======== ");
		LOGGER.info( "-- Deleting a previously created LineItem." );

		LineItem entity = null;
		
		try{
		    entity = read(); 
			LOGGER.info( "-- Successfully read LineItem with id " + lineItemId );            
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( "-- Failed to read LineItem with id " + lineItemId );

			throw e;
		}

		try{
			LineItemService.getLineItemInstance().delete( new DeleteLineItemCommand( entity.getLineItemId() ) ).get();
			LOGGER.info( "-- Successfully deleted LineItem with id " + lineItemId );            
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( "-- Failed to delete LineItem with id " + lineItemId );

			throw e;
		}
	}

	/**
	 * get all LineItems.
	 */
	protected List<LineItem> getAll() throws Throwable {    
		LOGGER.info( "======== GETALL ======== ");
		LOGGER.info( "-- Retrieving Collection of LineItems:" );

		StringBuilder msg = new StringBuilder( "-- Failed to get all LineItem : " );        
		List<LineItem> collection  = new ArrayList<>();

		try {
			// call the static get method on the LineItemService
			collection = LineItemService.getLineItemInstance().getAllLineItem();
			assertNotNull( collection, "An Empty collection of LineItem was incorrectly returned.");
			
			// Now print out the values
			LineItem entity = null;            
			Iterator<LineItem> iter = collection.iterator();
			int index = 1;

			while( iter.hasNext() ) {
				// Retrieve the entity   
				entity = iter.next();

				assertNotNull( entity,"-- null entity in Collection." );
				assertNotNull( entity.getLineItemId(), "-- entity in Collection has a null primary key" );        

				LOGGER.info( " - " + String.valueOf(index) + ". " + entity.toString() );
				index++;
			}
		}
		catch ( Throwable e ) {
			LOGGER.warning( unexpectedErrorMsg );
			LOGGER.warning( msg.toString() + " : " + e );

			throw e;
		}
		
		return collection;			
	}

	/**
	 * Assigns a common log handler for each test class in the suite 
	 * in the event log output needs to go elsewhere
	 * 
	 * @param		handler	Handler
	 * @return		LineItemTest
	 */
	protected LineItemTest setHandler(Handler handler) {
		if ( handler != null )
			LOGGER.addHandler(handler); 
		return this;
	}

	/**
	 * Returns a new populated LineItem
	 * 
	 * @return CreateLineItemCommand alias
	 */
	protected CreateLineItemCommand generateNewCommand() {
        CreateLineItemCommand command = new CreateLineItemCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  new Money(),  new Money(),  new FrequencyCap(),  LineItemStatus.values()[0],  PricingModel.values()[0],  BidStrategyType.values()[0],  PacingType.values()[0] );
		
		return( command );
	}

		/**
		 * Returns a new populated LineItem
		 * 
		 * @return UpdateLineItemCommand alias
		 */
	protected UpdateLineItemCommand generateUpdateCommand() {
	        UpdateLineItemCommand command = new UpdateLineItemCommand( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  new Money(),  new Money(),  new FrequencyCap(),  null,  new HashSet<>(),  null,  null,  new HashSet<>(),  new HashSet<>(),  LineItemStatus.values()[0],  PricingModel.values()[0],  BidStrategyType.values()[0],  PacingType.values()[0] );
			
			return( command );
		}
	//-----------------------------------------------------
	// attributes 
	//-----------------------------------------------------
	protected UUID lineItemId = null;
	protected LineItemSubscriber subscriber = null;
	private final String unexpectedErrorMsg = ":::::::::::::: Unexpected Error :::::::::::::::::";
	private final Logger LOGGER = Logger.getLogger(LineItemTest.class.getName());
	private String testingStep = "";
	private Integer sizeOfLineItemList = 0;
}
