/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * HCIDL Governance Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>RecordsRepositoryEntity Projector</h2>
 * <p>
 * The RecordsRepository Entity Projector is responsible for maintaining the write model for
 * RecordsRepository entities. It subscribes to domain events published by the RecordsRepository
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/21/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>HCIDL Governance Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical capabilities model for enterprise governance spanning compliance, risk, policy, audit, privacy, records, data retention, and legal hold functions.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry GRC</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>RecordsRepositoryRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("recordsRepository-entity-projector")
public class RecordsRepositoryEntityProjector implements EntityProjector<RecordsRepository>{
		
	// core constructor
	public RecordsRepositoryEntityProjector(ProjectorRegistry registry,
										RecordsRepositoryRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<RecordsRepository> getEntityClass() {
		return RecordsRepository.class;
	}

    /*
	 * Insert a RecordsRepository
	 * 
     * @param	entity RecordsRepository
     */
    public RecordsRepository create( RecordsRepository entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a RecordsRepository
	 * 
     * @param	entity RecordsRepository
     */
    public RecordsRepository update( RecordsRepository entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a RecordsRepository
	 * 
     * @param	id		UUID
     */
    public RecordsRepository delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    RecordsRepository entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Organization
     * 
     * @param	parentId	UUID
     * @param	assignment 	Organization 
     * @return	RecordsRepository
     */
    public RecordsRepository assignOrganization( UUID parentId, Organization assignment ) {
	    LOGGER.info("assigning Organization as " + assignment.toString() );

	    RecordsRepository parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Organization.class, assignment.getOrganizationId());

	    // ------------------------------------------
		// assign the Organization to the parent entity
		// ------------------------------------------ 
	    parentEntity.setOrganization( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Organization
	 * 
	 * @param	parentId		UUID
	 * @return	RecordsRepository
	 */
	public RecordsRepository unAssignOrganization( UUID parentId ) {
		RecordsRepository parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Organization on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Organization on the parent entithy
		// ------------------------------------------     
	    parentEntity.setOrganization(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the Records
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	RecordsRepository
     */
    public RecordsRepository addToRecords( UUID parentId, Record_ addTo ) {
	    LOGGER.info("handling AssignRecordsToRecordsRepositoryEvent - " );
	    
	    RecordsRepository parentEntity = repository.findById(parentId).get();
	    Record_ child = registry.project( Record_.class, addTo.getRecord_Id());
	    
	    parentEntity.getRecords().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Records
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	RecordsRepository
     */
	public RecordsRepository removeFromRecords( UUID parentId, Record_ removeFrom ) {
	    LOGGER.info("handling RemoveRecordsFromRecordsRepositoryEvent " );
	
	    RecordsRepository parentEntity = repository.findById(parentId).get();
	    Record_ child = registry.project( Record_.class, removeFrom.getRecord_Id());
	    
	    parentEntity.getRecords().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Systems
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	RecordsRepository
     */
    public RecordsRepository addToSystems( UUID parentId, System_ addTo ) {
	    LOGGER.info("handling AssignSystemsToRecordsRepositoryEvent - " );
	    
	    RecordsRepository parentEntity = repository.findById(parentId).get();
	    System_ child = registry.project( System_.class, addTo.getSystem_Id());
	    
	    parentEntity.getSystems().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Systems
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	RecordsRepository
     */
	public RecordsRepository removeFromSystems( UUID parentId, System_ removeFrom ) {
	    LOGGER.info("handling RemoveSystemsFromRecordsRepositoryEvent " );
	
	    RecordsRepository parentEntity = repository.findById(parentId).get();
	    System_ child = registry.project( System_.class, removeFrom.getSystem_Id());
	    
	    parentEntity.getSystems().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the RetentionSchedules
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	RecordsRepository
     */
    public RecordsRepository addToRetentionSchedules( UUID parentId, RetentionSchedule addTo ) {
	    LOGGER.info("handling AssignRetentionSchedulesToRecordsRepositoryEvent - " );
	    
	    RecordsRepository parentEntity = repository.findById(parentId).get();
	    RetentionSchedule child = registry.project( RetentionSchedule.class, addTo.getRetentionScheduleId());
	    
	    parentEntity.getRetentionSchedules().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the RetentionSchedules
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	RecordsRepository
     */
	public RecordsRepository removeFromRetentionSchedules( UUID parentId, RetentionSchedule removeFrom ) {
	    LOGGER.info("handling RemoveRetentionSchedulesFromRecordsRepositoryEvent " );
	
	    RecordsRepository parentEntity = repository.findById(parentId).get();
	    RetentionSchedule child = registry.project( RetentionSchedule.class, removeFrom.getRetentionScheduleId());
	    
	    parentEntity.getRetentionSchedules().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the LegalHolds
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	RecordsRepository
     */
    public RecordsRepository addToLegalHolds( UUID parentId, LegalHold addTo ) {
	    LOGGER.info("handling AssignLegalHoldsToRecordsRepositoryEvent - " );
	    
	    RecordsRepository parentEntity = repository.findById(parentId).get();
	    LegalHold child = registry.project( LegalHold.class, addTo.getLegalHoldId());
	    
	    parentEntity.getLegalHolds().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the LegalHolds
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	RecordsRepository
     */
	public RecordsRepository removeFromLegalHolds( UUID parentId, LegalHold removeFrom ) {
	    LOGGER.info("handling RemoveLegalHoldsFromRecordsRepositoryEvent " );
	
	    RecordsRepository parentEntity = repository.findById(parentId).get();
	    LegalHold child = registry.project( LegalHold.class, removeFrom.getLegalHoldId());
	    
	    parentEntity.getLegalHolds().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the RecordsRepository via an FindRecordsRepositoryQuery
     * @return 	query	FindRecordsRepositoryQuery
     */
    @SuppressWarnings("unused")
    public RecordsRepository find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a RecordsRepository - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all RecordsRepositorys
     *
     * @param	query	FindAllRecordsRepositoryQuery 
     * @return 	List<RecordsRepository> 
     */
    @SuppressWarnings("unused")
    public List<RecordsRepository> findAll( FindAllRecordsRepositoryQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all RecordsRepository - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final RecordsRepositoryRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(RecordsRepositoryEntityProjector.class.getName());

}
