# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


5.times do |i|
  FinancialInstitution.create( name:"test string for name", legalName:"test string for legalName", countryOfIncorporation:"test string for countryOfIncorporation", bic:"test value", website:"test string for website" )
  Branch.create( name:"test string for name", branchCode:"test string for branchCode", address:"test value" )
  ProductOffering.create( name:"test string for name", productCode:"test string for productCode", Category:0 )
  PricingPlan.create( name:"test string for name", planCode:"test string for planCode", baseCurrency:"test string for baseCurrency", Status:0 )
  FeeSchedule.create( name:"test string for name", amount:"test value", percentage:"test value", minimum:"test value", maximum:"test value", FeeType:0, CalculationMethod:0 )
  UsageLimit.create( name:"test string for name", amount:"test value", count:100, Scope:0, Period:0 )
  Customer.create( firstName:"test string for firstName", lastName:"test string for lastName", dateOfBirth:1.week.ago, email:"test value", phone:"test value", address:"test value", taxId:"test value", riskScore:"test value", CustomerType:0 )
  KYCProfile.create( profileId:"test string for profileId", createdAt:1.week.ago, Status:0, VerificationLevel:0 )
  KYCDocument.create( reference:"test value", issuedCountry:"test string for issuedCountry", expirationDate:1.week.ago, DocumentType:0, Status:0 )
  Screening.create( score:"test value", screenedAt:1.week.ago, ScreeningType:0, Status:0 )
  VerifiedAddress.create( address:"test value", verifiedAt:1.week.ago, VerificationStatus:0 )
  CompliancePolicy.create( name:"test string for name", policyCode:"test string for policyCode", description:"test string for description", Status:0 )
  ComplianceAlert.create( alertCode:"test string for alertCode", raisedAt:1.week.ago, notes:"test string for notes", Severity:0, Status:0 )
  Consent.create( grantedAt:1.week.ago, expiresAt:1.week.ago, scope:"test string for scope", ConsentType:0, Status:0 )
  APIClient.create( name:"test string for name", clientId:"test string for clientId", redirectUri:"test string for redirectUri", ClientType:0 )
  Agreement.create( agreementNumber:"test string for agreementNumber", effectiveDate:1.week.ago, AgreementType:0, Status:0 )
  Account.create( accountNumber:"test value", iban:"test value", bic:"test value", openedDate:1.week.ago, currency:"test string for currency", balance:"test value", availableBalance:"test value", AccountType:0, Status:0 )
  Wallet.create( currency:"test string for currency", balance:"test value", Status:0 )
  PaymentCard.create( cardToken:"test value", maskedPan:"test string for maskedPan", expiryMonth:100, expiryYear:100, cardholderName:"test string for cardholderName", Scheme:0, Status:0 )
  CardTokenization.create( tokenReference:"test string for tokenReference", createdAt:1.week.ago, WalletProvider:0, Status:0 )
  Merchant.create( name:"test string for name", mcc:"test string for mcc", url:"test string for url", country:"test string for country", settlementCurrency:"test string for settlementCurrency" )
  Terminal.create( location:"test value", Type:0, Status:0 )
  PaymentContract.create( contractNumber:"test string for contractNumber", pricingPlanCode:"test string for pricingPlanCode", Status:0 )
  PaymentProcessor.create( name:"test string for name", processorCode:"test string for processorCode", networkSupport:"test string for networkSupport" )
  Transaction.create( amount:"test value", fee:"test value", exchangeRate:"test value", createdAt:1.week.ago, completedAt:1.week.ago, narrative:"test string for narrative", TransactionType:0, Status:0 )
  PaymentOrder.create( orderReference:"test string for orderReference", requestedExecutionDate:1.week.ago, purpose:"test string for purpose", PaymentMethod:0, Status:0, Priority:0 )
  Beneficiary.create( name:"test string for name", accountIdentifier:"test value", iban:"test value", bic:"test value", address:"test value" )
  AppliedFee.create( amount:"test value", description:"test string for description", FeeType:0 )
  FXQuote.create( baseCurrency:"test string for baseCurrency", quoteCurrency:"test string for quoteCurrency", rate:"test value", quotedAt:1.week.ago, expiresAt:1.week.ago, PriceType:0 )
  FXDeal.create( dealReference:"test string for dealReference", baseCurrency:"test string for baseCurrency", quoteCurrency:"test string for quoteCurrency", rate:"test value", amount:"test value", settlementDate:1.week.ago, Status:0 )
  SettlementBatch.create( batchId:"test string for batchId", periodStart:1.week.ago, periodEnd:1.week.ago, totalVolume:"test value", totalCount:100, Status:0 )
  Payout.create( payoutReference:"test string for payoutReference", amount:"test value", currency:"test string for currency", scheduledDate:1.week.ago, paidDate:1.week.ago, Status:0 )
  Dispute.create( disputeReference:"test string for disputeReference", openedAt:1.week.ago, closedAt:1.week.ago, Reason:0, Status:0 )
  Chargeback.create( chargebackReference:"test string for chargebackReference", amount:"test value", postedAt:1.week.ago, Stage:0, Status:0 )
  Invoice.create( invoiceNumber:"test string for invoiceNumber", issueDate:1.week.ago, dueDate:1.week.ago, total:"test value", currency:"test string for currency", Status:0 )
  AccountStatement.create( statementNumber:"test string for statementNumber", periodStart:1.week.ago, periodEnd:1.week.ago, openingBalance:"test value", closingBalance:"test value", generatedAt:1.week.ago )
  DirectDebitMandate.create( mandateId:"test string for mandateId", signedAt:1.week.ago, Scheme:0, Status:0 )
  Creditor.create( name:"test string for name", bic:"test value", address:"test value" )
  LoanApplication.create( applicationNumber:"test string for applicationNumber", amountRequested:"test value", termMonths:100, submittedAt:1.week.ago, Product:0, Purpose:0, Status:0 )
  RiskAssessment.create( score:"test value", assessedAt:1.week.ago, modelVersion:"test string for modelVersion", notes:"test string for notes", Decision:0 )
  Loan.create( loanNumber:"test string for loanNumber", principal:"test value", interestRate:"test value", originationDate:1.week.ago, maturityDate:1.week.ago, RateType:0, Status:0 )
  RepaymentSchedule.create( installmentNumber:100, dueDate:1.week.ago, amountDue:"test value", principalDue:"test value", interestDue:"test value", Status:0 )
  Collateral.create( description:"test string for description", value:"test value", CollateralType:0 )
  LoanTransaction.create( transactionId:"test value", amount:"test value", postingDate:1.week.ago, Type:0, Status:0 )
  InvestmentPortfolio.create( portfolioCode:"test string for portfolioCode", baseCurrency:"test string for baseCurrency", createdAt:1.week.ago, Status:0 )
  InvestmentAccount.create( accountNumber:"test value", baseCurrency:"test string for baseCurrency", balance:"test value", AccountType:0, Status:0 )
  Security.create( symbol:"test string for symbol", isin:"test string for isin", cusip:"test string for cusip", currency:"test string for currency", SecurityType:0 )
  Position.create( quantity:"test value", averageCost:"test value", marketValue:"test value" )
  TradeOrder.create( orderId:"test string for orderId", quantity:"test value", limitPrice:"test value", placedAt:1.week.ago, Side:0, Type:0, Status:0, TimeInForce:0 )
  Trade.create( executedAt:1.week.ago, quantity:"test value", price:"test value", fees:"test value", settlementDate:1.week.ago )
  ExchangeRate.create( baseCurrency:"test string for baseCurrency", quoteCurrency:"test string for quoteCurrency", rate:"test value", asOf:1.week.ago, source:"test string for source" )
end
