/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * CRM Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import org.axonframework.config.ProcessingGroup;
import org.axonframework.eventhandling.EventHandler;
import org.axonframework.queryhandling.QueryHandler;
import org.axonframework.queryhandling.QueryUpdateEmitter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>ProductProjector</h2>
 * <p>
 * The Product Projector is responsible for maintaining the read model for
 * Product entities. It subscribes to domain events published by the Product
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>CRM Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core CRM capabilities across accounts, contacts, leads, opportunities, pricing, quotes, orders, service cases, activities, and campaigns.</td></tr>
 *          <tr><td>industry</td><td>CRM</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul><li>QueryGateway</li></ul>
 *
 * <h3>Queries Handled</h3>
 *		<ul>
 *      <li>FindProductQuery</li>
 *      <li>FindAllProductQuery</li>
 *		</ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
//@ProcessingGroup("product")
@Component("product-projector")
public class ProductProjector extends ProductEntityProjector {
		
	// core constructor
	public ProductProjector(ProjectorRegistry registry,
									ProductRepository repository,
									QueryUpdateEmitter queryUpdateEmitter ) {
        super(registry, repository);
        this.queryUpdateEmitter = queryUpdateEmitter;
    }	

	/*
     * @param	event CreateProductEvent
     */
    @EventHandler( payloadType=CreateProductEvent.class )
    public void handle( CreateProductEvent event) {
	    LOGGER.info("handling CreateProductEvent - " + event );
	    Product entity = new Product();
            entity.setProductId( event.getProductId() );
            entity.setSku( event.getSku() );
            entity.setName( event.getName() );
            entity.setAsActive( event.getAsActive() );
            entity.setStandardPrice( event.getStandardPrice() );
            entity.setDescription( event.getDescription() );
            entity.setProductType( event.getProductType() );
            entity.setUom( event.getUom() );
	    
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    create(entity);
        
        // ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllProduct( entity );
    }

    /*
     * @param	event UpdateProductEvent
     */
    @EventHandler( payloadType=UpdateProductEvent.class )
    public void handle( UpdateProductEvent event) {
    	LOGGER.info("handling UpdateProductEvent - " + event );
    	
	    Product entity = new Product();
            entity.setProductId( event.getProductId() );
            entity.setSku( event.getSku() );
            entity.setName( event.getName() );
            entity.setAsActive( event.getAsActive() );
            entity.setStandardPrice( event.getStandardPrice() );
            entity.setDescription( event.getDescription() );
            entity.setOrganization( event.getOrganization() );
            entity.setPriceBookEntries( event.getPriceBookEntries() );
            entity.setOpportunityLineItems( event.getOpportunityLineItems() );
            entity.setQuoteLineItems( event.getQuoteLineItems() );
            entity.setOrderItems( event.getOrderItems() );
            entity.setProductType( event.getProductType() );
            entity.setUom( event.getUom() );
 
    	// ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		update(entity);

    	// ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindProduct( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllProduct( entity );        
    }
    
    /*
     * @param	event DeleteProductEvent
     */
    @EventHandler( payloadType=DeleteProductEvent.class )
    public void handle( DeleteProductEvent event) {
    	LOGGER.info("handling DeleteProductEvent - " + event );
    	
    	// ------------------------------------------
    	// delete delegation
    	// ------------------------------------------
    	Product entity = delete( event.getProductId() );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllProduct( entity );

    }    

    /*
     * @param	event AssignOrganizationToProductEvent
     */
    @EventHandler( payloadType=AssignOrganizationToProductEvent.class)
    public void handle( AssignOrganizationToProductEvent event) {
	    LOGGER.info("handling AssignOrganizationToProductEvent - " + event );

	    // ------------------------------------------
	    // delegate to assignTo
	    // ------------------------------------------
	    Product entity = assignOrganization( event.getProductId(), event.getAssignment() );

	    // ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindProduct( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllProduct( entity );
    }
    

	/*
	 * @param	event UnAssignOrganizationFromProductEvent
	 */
	@EventHandler( payloadType=UnAssignOrganizationFromProductEvent.class)
	public void handle( UnAssignOrganizationFromProductEvent event) {
	    LOGGER.info("handling UnAssignOrganizationFromProductEvent - " + event );

	    // ------------------------------------------
	    // delegate to unAssignFrom
	    // ------------------------------------------
	    Product entity = unAssignOrganization( event.getProductId() );

		// ------------------------------------------
		// emit to subscribers that find one
		// ------------------------------------------    	
	    emitFindProduct( entity );
	
		// ------------------------------------------
		// emit to subscribers that find all
		// ------------------------------------------    	
	    emitFindAllProduct( entity );
	}


    /*
     * @param	event AssignPriceBookEntriesToProductEvent
     */
    @EventHandler( payloadType=AssignPriceBookEntriesToProductEvent.class)
    public void handle( AssignPriceBookEntriesToProductEvent event) {
	    LOGGER.info("handling AssignPriceBookEntriesToProductEvent - " + event );
	    
	    // ------------------------------------------
    	// delegate to addTo 
    	// ------------------------------------------ 
	    Product entity = addToPriceBookEntries(event.getProductId(), event.getAddTo() );
        
    	// ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindProduct( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllProduct( entity );
    }
    

/*
 * @param	event RemovePriceBookEntriesFromProductEvent
 */
@EventHandler( payloadType=RemovePriceBookEntriesFromProductEvent.class)
public void handle( RemovePriceBookEntriesFromProductEvent event) {
    LOGGER.info("handling RemovePriceBookEntriesFromProductEvent - " + event );

    Product entity = removeFromPriceBookEntries(event.getProductId(), event.getRemoveFrom() );
    
	// ------------------------------------------
	// emit to subscribers that find one
	// ------------------------------------------    	
    emitFindProduct( entity );

	// ------------------------------------------
	// emit to subscribers that find all
	// ------------------------------------------    	
    emitFindAllProduct( entity );
}

    /*
     * @param	event AssignOpportunityLineItemsToProductEvent
     */
    @EventHandler( payloadType=AssignOpportunityLineItemsToProductEvent.class)
    public void handle( AssignOpportunityLineItemsToProductEvent event) {
	    LOGGER.info("handling AssignOpportunityLineItemsToProductEvent - " + event );
	    
	    // ------------------------------------------
    	// delegate to addTo 
    	// ------------------------------------------ 
	    Product entity = addToOpportunityLineItems(event.getProductId(), event.getAddTo() );
        
    	// ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindProduct( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllProduct( entity );
    }
    

/*
 * @param	event RemoveOpportunityLineItemsFromProductEvent
 */
@EventHandler( payloadType=RemoveOpportunityLineItemsFromProductEvent.class)
public void handle( RemoveOpportunityLineItemsFromProductEvent event) {
    LOGGER.info("handling RemoveOpportunityLineItemsFromProductEvent - " + event );

    Product entity = removeFromOpportunityLineItems(event.getProductId(), event.getRemoveFrom() );
    
	// ------------------------------------------
	// emit to subscribers that find one
	// ------------------------------------------    	
    emitFindProduct( entity );

	// ------------------------------------------
	// emit to subscribers that find all
	// ------------------------------------------    	
    emitFindAllProduct( entity );
}

    /*
     * @param	event AssignQuoteLineItemsToProductEvent
     */
    @EventHandler( payloadType=AssignQuoteLineItemsToProductEvent.class)
    public void handle( AssignQuoteLineItemsToProductEvent event) {
	    LOGGER.info("handling AssignQuoteLineItemsToProductEvent - " + event );
	    
	    // ------------------------------------------
    	// delegate to addTo 
    	// ------------------------------------------ 
	    Product entity = addToQuoteLineItems(event.getProductId(), event.getAddTo() );
        
    	// ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindProduct( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllProduct( entity );
    }
    

/*
 * @param	event RemoveQuoteLineItemsFromProductEvent
 */
@EventHandler( payloadType=RemoveQuoteLineItemsFromProductEvent.class)
public void handle( RemoveQuoteLineItemsFromProductEvent event) {
    LOGGER.info("handling RemoveQuoteLineItemsFromProductEvent - " + event );

    Product entity = removeFromQuoteLineItems(event.getProductId(), event.getRemoveFrom() );
    
	// ------------------------------------------
	// emit to subscribers that find one
	// ------------------------------------------    	
    emitFindProduct( entity );

	// ------------------------------------------
	// emit to subscribers that find all
	// ------------------------------------------    	
    emitFindAllProduct( entity );
}

    /*
     * @param	event AssignOrderItemsToProductEvent
     */
    @EventHandler( payloadType=AssignOrderItemsToProductEvent.class)
    public void handle( AssignOrderItemsToProductEvent event) {
	    LOGGER.info("handling AssignOrderItemsToProductEvent - " + event );
	    
	    // ------------------------------------------
    	// delegate to addTo 
    	// ------------------------------------------ 
	    Product entity = addToOrderItems(event.getProductId(), event.getAddTo() );
        
    	// ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindProduct( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllProduct( entity );
    }
    

/*
 * @param	event RemoveOrderItemsFromProductEvent
 */
@EventHandler( payloadType=RemoveOrderItemsFromProductEvent.class)
public void handle( RemoveOrderItemsFromProductEvent event) {
    LOGGER.info("handling RemoveOrderItemsFromProductEvent - " + event );

    Product entity = removeFromOrderItems(event.getProductId(), event.getRemoveFrom() );
    
	// ------------------------------------------
	// emit to subscribers that find one
	// ------------------------------------------    	
    emitFindProduct( entity );

	// ------------------------------------------
	// emit to subscribers that find all
	// ------------------------------------------    	
    emitFindAllProduct( entity );
}



    /**
     * Method to retrieve the Product via an ProductPrimaryKey.
     * @param 	id Long
     * @return 	Product
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    @SuppressWarnings("unused")
    @QueryHandler
    public Product handle( FindProductQuery query ) 
    throws ProcessingException, IllegalArgumentException {
    	return find( query.getFilter().getProductId() );
    }
    
    /**
     * Method to retrieve a collection of all Products
     *
     * @param	query	FindAllProductQuery 
     * @return 	List<Product> 
     * @exception ProcessingException Thrown if any problems
     */
    @SuppressWarnings("unused")
    @QueryHandler
    public List<Product> handle( FindAllProductQuery query ) throws ProcessingException {
    	return findAll( query );
    }



/**
 * emit to subscription queries of type FindProduct,
 * but only if the id matches
 *
 * @param		entity	Product
 */
	protected void emitFindProduct( Product entity ) {
		LOGGER.info("handling emitFindProduct" );
		
	    queryUpdateEmitter.emit(FindProductQuery.class,
	                            query -> query.getFilter().getProductId().equals(entity.getProductId()),
	                            entity);
	}
	
	/**
	 * unconditionally emit to subscription queries of type FindAllProduct
	 * 
	 * @param		entity	Product
	 */
	protected void emitFindAllProduct( Product entity ) {
		LOGGER.info("handling emitFindAllProduct" );
		
	    queryUpdateEmitter.emit(FindAllProductQuery.class,
	                            query -> true,
	                            entity);
	}

	//--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
	private final QueryUpdateEmitter queryUpdateEmitter;
    private static final Logger LOGGER 	= Logger.getLogger(ProductProjector.class.getName());

}
