/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * CRM Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import org.axonframework.config.ProcessingGroup;
import org.axonframework.eventhandling.EventHandler;
import org.axonframework.queryhandling.QueryHandler;
import org.axonframework.queryhandling.QueryUpdateEmitter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>TerritoryProjector</h2>
 * <p>
 * The Territory Projector is responsible for maintaining the read model for
 * Territory entities. It subscribes to domain events published by the Territory
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>CRM Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core CRM capabilities across accounts, contacts, leads, opportunities, pricing, quotes, orders, service cases, activities, and campaigns.</td></tr>
 *          <tr><td>industry</td><td>CRM</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul><li>QueryGateway</li></ul>
 *
 * <h3>Queries Handled</h3>
 *		<ul>
 *      <li>FindTerritoryQuery</li>
 *      <li>FindAllTerritoryQuery</li>
 *		</ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
//@ProcessingGroup("territory")
@Component("territory-projector")
public class TerritoryProjector extends TerritoryEntityProjector {
		
	// core constructor
	public TerritoryProjector(ProjectorRegistry registry,
									TerritoryRepository repository,
									QueryUpdateEmitter queryUpdateEmitter ) {
        super(registry, repository);
        this.queryUpdateEmitter = queryUpdateEmitter;
    }	

	/*
     * @param	event CreateTerritoryEvent
     */
    @EventHandler( payloadType=CreateTerritoryEvent.class )
    public void handle( CreateTerritoryEvent event) {
	    LOGGER.info("handling CreateTerritoryEvent - " + event );
	    Territory entity = new Territory();
            entity.setTerritoryId( event.getTerritoryId() );
            entity.setName( event.getName() );
            entity.setRegion( event.getRegion() );
            entity.setTerritoryType( event.getTerritoryType() );
	    
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    create(entity);
        
        // ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllTerritory( entity );
    }

    /*
     * @param	event UpdateTerritoryEvent
     */
    @EventHandler( payloadType=UpdateTerritoryEvent.class )
    public void handle( UpdateTerritoryEvent event) {
    	LOGGER.info("handling UpdateTerritoryEvent - " + event );
    	
	    Territory entity = new Territory();
            entity.setTerritoryId( event.getTerritoryId() );
            entity.setName( event.getName() );
            entity.setRegion( event.getRegion() );
            entity.setOrganization( event.getOrganization() );
            entity.setAccounts( event.getAccounts() );
            entity.setUsers( event.getUsers() );
            entity.setTerritoryType( event.getTerritoryType() );
 
    	// ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		update(entity);

    	// ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindTerritory( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllTerritory( entity );        
    }
    
    /*
     * @param	event DeleteTerritoryEvent
     */
    @EventHandler( payloadType=DeleteTerritoryEvent.class )
    public void handle( DeleteTerritoryEvent event) {
    	LOGGER.info("handling DeleteTerritoryEvent - " + event );
    	
    	// ------------------------------------------
    	// delete delegation
    	// ------------------------------------------
    	Territory entity = delete( event.getTerritoryId() );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllTerritory( entity );

    }    

    /*
     * @param	event AssignOrganizationToTerritoryEvent
     */
    @EventHandler( payloadType=AssignOrganizationToTerritoryEvent.class)
    public void handle( AssignOrganizationToTerritoryEvent event) {
	    LOGGER.info("handling AssignOrganizationToTerritoryEvent - " + event );

	    // ------------------------------------------
	    // delegate to assignTo
	    // ------------------------------------------
	    Territory entity = assignOrganization( event.getTerritoryId(), event.getAssignment() );

	    // ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindTerritory( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllTerritory( entity );
    }
    

	/*
	 * @param	event UnAssignOrganizationFromTerritoryEvent
	 */
	@EventHandler( payloadType=UnAssignOrganizationFromTerritoryEvent.class)
	public void handle( UnAssignOrganizationFromTerritoryEvent event) {
	    LOGGER.info("handling UnAssignOrganizationFromTerritoryEvent - " + event );

	    // ------------------------------------------
	    // delegate to unAssignFrom
	    // ------------------------------------------
	    Territory entity = unAssignOrganization( event.getTerritoryId() );

		// ------------------------------------------
		// emit to subscribers that find one
		// ------------------------------------------    	
	    emitFindTerritory( entity );
	
		// ------------------------------------------
		// emit to subscribers that find all
		// ------------------------------------------    	
	    emitFindAllTerritory( entity );
	}


    /*
     * @param	event AssignAccountsToTerritoryEvent
     */
    @EventHandler( payloadType=AssignAccountsToTerritoryEvent.class)
    public void handle( AssignAccountsToTerritoryEvent event) {
	    LOGGER.info("handling AssignAccountsToTerritoryEvent - " + event );
	    
	    // ------------------------------------------
    	// delegate to addTo 
    	// ------------------------------------------ 
	    Territory entity = addToAccounts(event.getTerritoryId(), event.getAddTo() );
        
    	// ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindTerritory( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllTerritory( entity );
    }
    

/*
 * @param	event RemoveAccountsFromTerritoryEvent
 */
@EventHandler( payloadType=RemoveAccountsFromTerritoryEvent.class)
public void handle( RemoveAccountsFromTerritoryEvent event) {
    LOGGER.info("handling RemoveAccountsFromTerritoryEvent - " + event );

    Territory entity = removeFromAccounts(event.getTerritoryId(), event.getRemoveFrom() );
    
	// ------------------------------------------
	// emit to subscribers that find one
	// ------------------------------------------    	
    emitFindTerritory( entity );

	// ------------------------------------------
	// emit to subscribers that find all
	// ------------------------------------------    	
    emitFindAllTerritory( entity );
}

    /*
     * @param	event AssignUsersToTerritoryEvent
     */
    @EventHandler( payloadType=AssignUsersToTerritoryEvent.class)
    public void handle( AssignUsersToTerritoryEvent event) {
	    LOGGER.info("handling AssignUsersToTerritoryEvent - " + event );
	    
	    // ------------------------------------------
    	// delegate to addTo 
    	// ------------------------------------------ 
	    Territory entity = addToUsers(event.getTerritoryId(), event.getAddTo() );
        
    	// ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindTerritory( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllTerritory( entity );
    }
    

/*
 * @param	event RemoveUsersFromTerritoryEvent
 */
@EventHandler( payloadType=RemoveUsersFromTerritoryEvent.class)
public void handle( RemoveUsersFromTerritoryEvent event) {
    LOGGER.info("handling RemoveUsersFromTerritoryEvent - " + event );

    Territory entity = removeFromUsers(event.getTerritoryId(), event.getRemoveFrom() );
    
	// ------------------------------------------
	// emit to subscribers that find one
	// ------------------------------------------    	
    emitFindTerritory( entity );

	// ------------------------------------------
	// emit to subscribers that find all
	// ------------------------------------------    	
    emitFindAllTerritory( entity );
}



    /**
     * Method to retrieve the Territory via an TerritoryPrimaryKey.
     * @param 	id Long
     * @return 	Territory
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    @SuppressWarnings("unused")
    @QueryHandler
    public Territory handle( FindTerritoryQuery query ) 
    throws ProcessingException, IllegalArgumentException {
    	return find( query.getFilter().getTerritoryId() );
    }
    
    /**
     * Method to retrieve a collection of all Territorys
     *
     * @param	query	FindAllTerritoryQuery 
     * @return 	List<Territory> 
     * @exception ProcessingException Thrown if any problems
     */
    @SuppressWarnings("unused")
    @QueryHandler
    public List<Territory> handle( FindAllTerritoryQuery query ) throws ProcessingException {
    	return findAll( query );
    }



/**
 * emit to subscription queries of type FindTerritory,
 * but only if the id matches
 *
 * @param		entity	Territory
 */
	protected void emitFindTerritory( Territory entity ) {
		LOGGER.info("handling emitFindTerritory" );
		
	    queryUpdateEmitter.emit(FindTerritoryQuery.class,
	                            query -> query.getFilter().getTerritoryId().equals(entity.getTerritoryId()),
	                            entity);
	}
	
	/**
	 * unconditionally emit to subscription queries of type FindAllTerritory
	 * 
	 * @param		entity	Territory
	 */
	protected void emitFindAllTerritory( Territory entity ) {
		LOGGER.info("handling emitFindAllTerritory" );
		
	    queryUpdateEmitter.emit(FindAllTerritoryQuery.class,
	                            query -> true,
	                            entity);
	}

	//--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
	private final QueryUpdateEmitter queryUpdateEmitter;
    private static final Logger LOGGER 	= Logger.getLogger(TerritoryProjector.class.getName());

}
