from django.urls import path
from ecommerceOnDjango.views import OrderView

urlpatterns = [
    path('', OrderView.index, name='index'),
	path('create', OrderView.get, name='create'),
	path('get/<int:orderId>/', OrderView.get, name='get'),
	path('save', OrderView.save, name='save'),
	path('getAll', OrderView.getAll, name='getAll'),
	path('delete/<int:orderId>/', OrderView.delete, name='delete'),
	path('assignCustomer/<int:orderId>/<int:CustomerId>/', OrderView.assignCustomer, name='assignCustomer'),
	path('unassignCustomer/<int:orderId>/', OrderView.unassignCustomer, name='unassignCustomer'),
	path('assignChannel/<int:orderId>/<int:ChannelId>/', OrderView.assignChannel, name='assignChannel'),
	path('unassignChannel/<int:orderId>/', OrderView.unassignChannel, name='unassignChannel'),
	path('assignSeller/<int:orderId>/<int:SellerId>/', OrderView.assignSeller, name='assignSeller'),
	path('unassignSeller/<int:orderId>/', OrderView.unassignSeller, name='unassignSeller'),
	path('assignInvoice/<int:orderId>/<int:InvoiceId>/', OrderView.assignInvoice, name='assignInvoice'),
	path('unassignInvoice/<int:orderId>/', OrderView.unassignInvoice, name='unassignInvoice'),
	path('addOrderLines/<int:orderId>/<OrderLinesIds>/', OrderView.addOrderLines, name='addOrderLines'),
	path('removeOrderLines/<int:orderId>/<OrderLinesIds>/', OrderView.removeOrderLines, name='removeOrderLines'),
	path('addPayments/<int:orderId>/<PaymentsIds>/', OrderView.addPayments, name='addPayments'),
	path('removePayments/<int:orderId>/<PaymentsIds>/', OrderView.removePayments, name='removePayments'),
	path('addShipments/<int:orderId>/<ShipmentsIds>/', OrderView.addShipments, name='addShipments'),
	path('removeShipments/<int:orderId>/<ShipmentsIds>/', OrderView.removeShipments, name='removeShipments'),
	path('addRefunds/<int:orderId>/<RefundsIds>/', OrderView.addRefunds, name='addRefunds'),
	path('removeRefunds/<int:orderId>/<RefundsIds>/', OrderView.removeRefunds, name='removeRefunds'),
	path('addAppliedPromotions/<int:orderId>/<AppliedPromotionsIds>/', OrderView.addAppliedPromotions, name='addAppliedPromotions'),
	path('removeAppliedPromotions/<int:orderId>/<AppliedPromotionsIds>/', OrderView.removeAppliedPromotions, name='removeAppliedPromotions'),
	path('addGiftCardRedemptions/<int:orderId>/<GiftCardRedemptionsIds>/', OrderView.addGiftCardRedemptions, name='addGiftCardRedemptions'),
	path('removeGiftCardRedemptions/<int:orderId>/<GiftCardRedemptionsIds>/', OrderView.removeGiftCardRedemptions, name='removeGiftCardRedemptions'),
	path('addCouponRedemptions/<int:orderId>/<CouponRedemptionsIds>/', OrderView.addCouponRedemptions, name='addCouponRedemptions'),
	path('removeCouponRedemptions/<int:orderId>/<CouponRedemptionsIds>/', OrderView.removeCouponRedemptions, name='removeCouponRedemptions'),
	path('addReturnRequests/<int:orderId>/<ReturnRequestsIds>/', OrderView.addReturnRequests, name='addReturnRequests'),
	path('removeReturnRequests/<int:orderId>/<ReturnRequestsIds>/', OrderView.removeReturnRequests, name='removeReturnRequests'),
]
