/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller.query;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.projector.*;

import com.harbormaster.controller.*;
/**
 * <h2>ProductOfferingQueryRestController as REST API</h2>
 * <p>
 * Implements Spring Controller query CQRS processing for entity ProductOffering.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ProductOfferingService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateProductOfferingCommand</li>
 *      <li></li>UpdateProductOfferingCommand</li>
 *      <liDeleteProductOfferingCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@CrossOrigin
@RestController
@RequestMapping("/ProductOfferingQuery")
public class ProductOfferingQueryRestController extends BaseSpringRestController {
	
	public ProductOfferingQueryRestController( ProductOfferingService service ) {
        this.service = service;
    }
    
    /**
     * Handles loading a ProductOffering using a UUID
     * @param		UUID productOfferingId
     * @return		ProductOffering
     */    
    @GetMapping("/load")
    public ProductOffering load( @RequestParam(required=true) UUID productOfferingId ) {
    	ProductOffering entity = null;

    	try {  
    		entity = service.getProductOffering( new ProductOfferingFetchOneSummary( productOfferingId ) );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load ProductOffering using Id " + productOfferingId );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all ProductOffering business objects
     * @return		Set<ProductOffering>
     */
    @GetMapping("/")
    public List<ProductOffering> loadAll() {                
    	List<ProductOffering> productOfferingList = null;
        
    	try {
            // load the ProductOffering
            productOfferingList = service.getAllProductOffering();
            
            if ( productOfferingList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all ProductOfferings" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all ProductOfferings ", exc );
        	return null;
        }

        return productOfferingList;
                            
    }



//************************************************************************    
// Attributes
//************************************************************************
    protected ProductOffering productOffering = null;
    protected ProductOfferingService service = null;
    private static final Logger LOGGER = Logger.getLogger(ProductOfferingQueryRestController.class.getName());
    
}
