from django.urls import path
from healthcareOnDjango.views import PatientView

urlpatterns = [
    path('', PatientView.index, name='index'),
	path('create', PatientView.get, name='create'),
	path('get/<int:patientId>/', PatientView.get, name='get'),
	path('save', PatientView.save, name='save'),
	path('getAll', PatientView.getAll, name='getAll'),
	path('delete/<int:patientId>/', PatientView.delete, name='delete'),
	path('addAppointments/<int:patientId>/<AppointmentsIds>/', PatientView.addAppointments, name='addAppointments'),
	path('removeAppointments/<int:patientId>/<AppointmentsIds>/', PatientView.removeAppointments, name='removeAppointments'),
	path('addEncounters/<int:patientId>/<EncountersIds>/', PatientView.addEncounters, name='addEncounters'),
	path('removeEncounters/<int:patientId>/<EncountersIds>/', PatientView.removeEncounters, name='removeEncounters'),
	path('addCarePlans/<int:patientId>/<CarePlansIds>/', PatientView.addCarePlans, name='addCarePlans'),
	path('removeCarePlans/<int:patientId>/<CarePlansIds>/', PatientView.removeCarePlans, name='removeCarePlans'),
	path('addAllergies/<int:patientId>/<AllergiesIds>/', PatientView.addAllergies, name='addAllergies'),
	path('removeAllergies/<int:patientId>/<AllergiesIds>/', PatientView.removeAllergies, name='removeAllergies'),
	path('addConditions/<int:patientId>/<ConditionsIds>/', PatientView.addConditions, name='addConditions'),
	path('removeConditions/<int:patientId>/<ConditionsIds>/', PatientView.removeConditions, name='removeConditions'),
	path('addMedicationOrders/<int:patientId>/<MedicationOrdersIds>/', PatientView.addMedicationOrders, name='addMedicationOrders'),
	path('removeMedicationOrders/<int:patientId>/<MedicationOrdersIds>/', PatientView.removeMedicationOrders, name='removeMedicationOrders'),
	path('addLabOrders/<int:patientId>/<LabOrdersIds>/', PatientView.addLabOrders, name='addLabOrders'),
	path('removeLabOrders/<int:patientId>/<LabOrdersIds>/', PatientView.removeLabOrders, name='removeLabOrders'),
	path('addImagingOrders/<int:patientId>/<ImagingOrdersIds>/', PatientView.addImagingOrders, name='addImagingOrders'),
	path('removeImagingOrders/<int:patientId>/<ImagingOrdersIds>/', PatientView.removeImagingOrders, name='removeImagingOrders'),
	path('addCoverages/<int:patientId>/<CoveragesIds>/', PatientView.addCoverages, name='addCoverages'),
	path('removeCoverages/<int:patientId>/<CoveragesIds>/', PatientView.removeCoverages, name='removeCoverages'),
	path('addClaims/<int:patientId>/<ClaimsIds>/', PatientView.addClaims, name='addClaims'),
	path('removeClaims/<int:patientId>/<ClaimsIds>/', PatientView.removeClaims, name='removeClaims'),
	path('addDevices/<int:patientId>/<DevicesIds>/', PatientView.addDevices, name='addDevices'),
	path('removeDevices/<int:patientId>/<DevicesIds>/', PatientView.removeDevices, name='removeDevices'),
	path('addObservations/<int:patientId>/<ObservationsIds>/', PatientView.addObservations, name='addObservations'),
	path('removeObservations/<int:patientId>/<ObservationsIds>/', PatientView.removeObservations, name='removeObservations'),
]
