package com.harbormaster.aggregate;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.axonframework.commandhandling.CommandHandler;
import org.axonframework.modelling.command.AggregateMember;
import org.axonframework.eventsourcing.EventSourcingHandler;
import org.axonframework.modelling.command.AggregateIdentifier;
import static org.axonframework.modelling.command.AggregateLifecycle.apply;
import org.axonframework.spring.stereotype.Aggregate;
import org.springframework.context.annotation.Profile;

/**
 * <h2>ClaimAggregate</h2>
 * <p>
 * The Claim aggregate is the authoritative consistency boundary for all
 * branch-related operations. It validates incoming commands, enforces
 * business rules, maintains the integrity of the Claim domain, and emits
 * immutable domain events representing state changes.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Healthcare Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core provider, patient, clinical, diagnostics, pharmacy, financial, and device-management capabilities.</td></tr>
 *          <tr><td>industry</td><td>Healthcare</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateClaimCommand</li>
 *      <li>UpdateClaimCommand</li>
 *      <li>DeleteClaimCommand</li>
 *      </ul>
 *
 * <h3>Associations</h3>
 * <ul>
 *       <li>AssignPatientToClaimCommand</li>
 *       <li>UnAssignPatientFromClaimCommand</li>
 *       <li>AssignCoverageToClaimCommand</li>
 *       <li>UnAssignCoverageFromClaimCommand</li>
 *       <li>AssignEncounterToClaimCommand</li>
 *       <li>UnAssignEncounterFromClaimCommand</li>
 *       <li>AssignPayerToClaimCommand</li>
 *       <li>UnAssignPayerFromClaimCommand</li>
 *  </ul>
 *  <ul>
 *       <li>AssignInvoicesToClaimCommand</li>
 *       <li>RemoveInvoicesFromClaimCommand</li>
 *   </ul>
 *
 * <p>
 * @author Harbormaster Dev Team
 * </p>
 *
 *
 * <h3>Events Emitted</h3>
 *      <ul>
 *      <li>CreateClaimEvent</li>
 *      <li>UpdateClaimEvent</li>
 *      <li>DeleteClaimEvent</li>
   *       <li>AssignPatientToClaimEvent</li>
 *       <li>UnAssignPatientFromClaimEvent</li>
  *       <li>AssignCoverageToClaimEvent</li>
 *       <li>UnAssignCoverageFromClaimEvent</li>
  *       <li>AssignEncounterToClaimEvent</li>
 *       <li>UnAssignEncounterFromClaimEvent</li>
  *       <li>AssignPayerToClaimEvent</li>
 *       <li>UnAssignPayerFromClaimEvent</li>
   *       <li>AssignInvoicesToClaimEvent</li>
 *       <li>RemoveInvoicesFromClaimEvent</li>
  *        </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Aggregate
public class ClaimAggregate {  

	// -----------------------------------------
	// Axon requires an empty constructor
    // -----------------------------------------
    public ClaimAggregate() {
    }

	// ----------------------------------------------
	// intrinsic command handlers
	// ----------------------------------------------
    @CommandHandler
    public ClaimAggregate(CreateClaimCommand command) throws Exception {
    	LOGGER.info( "Handling command CreateClaimCommand" );
    	CreateClaimEvent event = new CreateClaimEvent(command.getClaimId(), command.getClaimNumber(), command.getTotalAmount(), command.getStatus());
    	
        apply(event);
    }

    @CommandHandler
    public void handle(UpdateClaimCommand command) throws Exception {
    	LOGGER.info( "handling command UpdateClaimCommand" );
    	UpdateClaimEvent event = new UpdateClaimEvent(command.getClaimId(), command.getClaimNumber(), command.getTotalAmount(), command.getPatient(), command.getCoverage(), command.getEncounter(), command.getInvoices(), command.getPayer(), command.getStatus());        
    	
        apply(event);
    }

    @CommandHandler
    public void handle(DeleteClaimCommand command) throws Exception {
    	LOGGER.info( "Handling command DeleteClaimCommand" );
        apply(new DeleteClaimEvent(command.getClaimId()));
    }

	// ----------------------------------------------
	// association command handlers
	// ----------------------------------------------

    // single association commands
    @CommandHandler
    public void handle(AssignPatientToClaimCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignPatientToClaimCommand" );
    	
    	if (  patient != null && patient.getPatientId() == command.getAssignment().getPatientId() )
    		throw new ProcessingException( "Patient already assigned with id " + command.getAssignment().getPatientId() );  
    		
        apply(new AssignPatientToClaimEvent(command.getClaimId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignPatientFromClaimCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignPatientFromClaimCommand" );

    	if (  patient == null )
    		throw new ProcessingException( "Patient already has nothing assigned." );  

    	apply(new UnAssignPatientFromClaimEvent(command.getClaimId()));
    }
    @CommandHandler
    public void handle(AssignCoverageToClaimCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignCoverageToClaimCommand" );
    	
    	if (  coverage != null && coverage.getCoverageId() == command.getAssignment().getCoverageId() )
    		throw new ProcessingException( "Coverage already assigned with id " + command.getAssignment().getCoverageId() );  
    		
        apply(new AssignCoverageToClaimEvent(command.getClaimId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignCoverageFromClaimCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignCoverageFromClaimCommand" );

    	if (  coverage == null )
    		throw new ProcessingException( "Coverage already has nothing assigned." );  

    	apply(new UnAssignCoverageFromClaimEvent(command.getClaimId()));
    }
    @CommandHandler
    public void handle(AssignEncounterToClaimCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignEncounterToClaimCommand" );
    	
    	if (  encounter != null && encounter.getEncounterId() == command.getAssignment().getEncounterId() )
    		throw new ProcessingException( "Encounter already assigned with id " + command.getAssignment().getEncounterId() );  
    		
        apply(new AssignEncounterToClaimEvent(command.getClaimId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignEncounterFromClaimCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignEncounterFromClaimCommand" );

    	if (  encounter == null )
    		throw new ProcessingException( "Encounter already has nothing assigned." );  

    	apply(new UnAssignEncounterFromClaimEvent(command.getClaimId()));
    }
    @CommandHandler
    public void handle(AssignPayerToClaimCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignPayerToClaimCommand" );
    	
    	if (  payer != null && payer.getInsurancePayerId() == command.getAssignment().getInsurancePayerId() )
    		throw new ProcessingException( "Payer already assigned with id " + command.getAssignment().getInsurancePayerId() );  
    		
        apply(new AssignPayerToClaimEvent(command.getClaimId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignPayerFromClaimCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignPayerFromClaimCommand" );

    	if (  payer == null )
    		throw new ProcessingException( "Payer already has nothing assigned." );  

    	apply(new UnAssignPayerFromClaimEvent(command.getClaimId()));
    }

    // multiple association commands
    @CommandHandler
    public void handle(AssignInvoicesToClaimCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignInvoicesToClaimCommand" );
    	
    	if ( invoices.contains( command.getAddTo() ) )
    		throw new ProcessingException( "Invoices already contains an entity with id " + command.getAddTo().getInvoiceId() );

    	apply(new AssignInvoicesToClaimEvent(command.getClaimId(), command.getAddTo()));
    }

    @CommandHandler
    public void handle(RemoveInvoicesFromClaimCommand command) throws Exception {
    	LOGGER.info( "Handling command RemoveInvoicesFromClaimCommand" );
    	
    	if ( !invoices.contains( command.getRemoveFrom() ) )
    		throw new ProcessingException( "Invoices does not contain an entity with id " + command.getRemoveFrom().getInvoiceId() );

        apply(new RemoveInvoicesFromClaimEvent(command.getClaimId(), command.getRemoveFrom()));
    }

	// ----------------------------------------------
	// intrinsic event source handlers
	// ----------------------------------------------
    @EventSourcingHandler
    void on(CreateClaimEvent event) {	
    	LOGGER.info( "Event sourcing CreateClaimEvent" );
    	this.claimId = event.getClaimId();
        this.claimNumber = event.getClaimNumber();
        this.totalAmount = event.getTotalAmount();
        this.status = event.getStatus();
    }
    
    @EventSourcingHandler
    void on(UpdateClaimEvent event) {
    	LOGGER.info( "Event sourcing classObject.getUpdateEventAlias()}" );
        this.claimNumber = event.getClaimNumber();
        this.totalAmount = event.getTotalAmount();
        this.patient = event.getPatient();
        this.coverage = event.getCoverage();
        this.encounter = event.getEncounter();
        this.invoices = event.getInvoices();
        this.payer = event.getPayer();
        this.status = event.getStatus();
    }   

	// ----------------------------------------------
	// association event source handlers
	// ----------------------------------------------
	// single associations
    @EventSourcingHandler
    void on(AssignPatientToClaimEvent event ) {	
    	LOGGER.info( "Event sourcing AssignPatientToClaimEvent" );
    	this.patient = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignPatientFromClaimEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignPatientFromClaimEvent" );
		this.patient = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignCoverageToClaimEvent event ) {	
    	LOGGER.info( "Event sourcing AssignCoverageToClaimEvent" );
    	this.coverage = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignCoverageFromClaimEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignCoverageFromClaimEvent" );
		this.coverage = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignEncounterToClaimEvent event ) {	
    	LOGGER.info( "Event sourcing AssignEncounterToClaimEvent" );
    	this.encounter = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignEncounterFromClaimEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignEncounterFromClaimEvent" );
		this.encounter = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignPayerToClaimEvent event ) {	
    	LOGGER.info( "Event sourcing AssignPayerToClaimEvent" );
    	this.payer = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignPayerFromClaimEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignPayerFromClaimEvent" );
		this.payer = null;
	}

	// multiple associations
    @EventSourcingHandler
    void on(AssignInvoicesToClaimEvent event ) {
    	LOGGER.info( "Event sourcing AssignInvoicesToClaimEvent" );
    	this.invoices.add( event.getAddTo() );
    }

	@EventSourcingHandler
	void on(RemoveInvoicesFromClaimEvent event ) {	
		LOGGER.info( "Event sourcing RemoveInvoicesFromClaimEvent" );
		this.invoices.remove( event.getRemoveFrom() );
	}
	

    // ------------------------------------------
    // attributes
    // ------------------------------------------
	
    @AggregateIdentifier
    private UUID claimId;
    
    private String claimNumber;
    private Money totalAmount;
    private ClaimStatus status;
    private Patient patient = null;
    private Coverage coverage = null;
    private Encounter encounter = null;
    private Set<Invoice> invoices = new HashSet<>();
    private InsurancePayer payer = null;

    private static final Logger LOGGER 	= Logger.getLogger(ClaimAggregate.class.getName());
}
