/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * CRM Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>TeamEntity Projector</h2>
 * <p>
 * The Team Entity Projector is responsible for maintaining the write model for
 * Team entities. It subscribes to domain events published by the Team
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/21/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>CRM Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core CRM capabilities across accounts, contacts, leads, opportunities, pricing, quotes, orders, service cases, activities, and campaigns.</td></tr>
 *          <tr><td>industry</td><td>CRM</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>TeamRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("team-entity-projector")
public class TeamEntityProjector implements EntityProjector<Team>{
		
	// core constructor
	public TeamEntityProjector(ProjectorRegistry registry,
										TeamRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<Team> getEntityClass() {
		return Team.class;
	}

    /*
	 * Insert a Team
	 * 
     * @param	entity Team
     */
    public Team create( Team entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a Team
	 * 
     * @param	entity Team
     */
    public Team update( Team entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a Team
	 * 
     * @param	id		UUID
     */
    public Team delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    Team entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Organization
     * 
     * @param	parentId	UUID
     * @param	assignment 	Organization 
     * @return	Team
     */
    public Team assignOrganization( UUID parentId, Organization assignment ) {
	    LOGGER.info("assigning Organization as " + assignment.toString() );

	    Team parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Organization.class, assignment.getOrganizationId());

	    // ------------------------------------------
		// assign the Organization to the parent entity
		// ------------------------------------------ 
	    parentEntity.setOrganization( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Organization
	 * 
	 * @param	parentId		UUID
	 * @return	Team
	 */
	public Team unAssignOrganization( UUID parentId ) {
		Team parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Organization on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Organization on the parent entithy
		// ------------------------------------------     
	    parentEntity.setOrganization(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the Users
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Team
     */
    public Team addToUsers( UUID parentId, User addTo ) {
	    LOGGER.info("handling AssignUsersToTeamEvent - " );
	    
	    Team parentEntity = repository.findById(parentId).get();
	    User child = registry.project( User.class, addTo.getUserId());
	    
	    parentEntity.getUsers().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Users
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Team
     */
	public Team removeFromUsers( UUID parentId, User removeFrom ) {
	    LOGGER.info("handling RemoveUsersFromTeamEvent " );
	
	    Team parentEntity = repository.findById(parentId).get();
	    User child = registry.project( User.class, removeFrom.getUserId());
	    
	    parentEntity.getUsers().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Accounts
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Team
     */
    public Team addToAccounts( UUID parentId, Account addTo ) {
	    LOGGER.info("handling AssignAccountsToTeamEvent - " );
	    
	    Team parentEntity = repository.findById(parentId).get();
	    Account child = registry.project( Account.class, addTo.getAccountId());
	    
	    parentEntity.getAccounts().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Accounts
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Team
     */
	public Team removeFromAccounts( UUID parentId, Account removeFrom ) {
	    LOGGER.info("handling RemoveAccountsFromTeamEvent " );
	
	    Team parentEntity = repository.findById(parentId).get();
	    Account child = registry.project( Account.class, removeFrom.getAccountId());
	    
	    parentEntity.getAccounts().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Opportunities
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Team
     */
    public Team addToOpportunities( UUID parentId, Opportunity addTo ) {
	    LOGGER.info("handling AssignOpportunitiesToTeamEvent - " );
	    
	    Team parentEntity = repository.findById(parentId).get();
	    Opportunity child = registry.project( Opportunity.class, addTo.getOpportunityId());
	    
	    parentEntity.getOpportunities().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Opportunities
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Team
     */
	public Team removeFromOpportunities( UUID parentId, Opportunity removeFrom ) {
	    LOGGER.info("handling RemoveOpportunitiesFromTeamEvent " );
	
	    Team parentEntity = repository.findById(parentId).get();
	    Opportunity child = registry.project( Opportunity.class, removeFrom.getOpportunityId());
	    
	    parentEntity.getOpportunities().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Cases
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Team
     */
    public Team addToCases( UUID parentId, Case_ addTo ) {
	    LOGGER.info("handling AssignCasesToTeamEvent - " );
	    
	    Team parentEntity = repository.findById(parentId).get();
	    Case_ child = registry.project( Case_.class, addTo.getCase_Id());
	    
	    parentEntity.getCases().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Cases
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Team
     */
	public Team removeFromCases( UUID parentId, Case_ removeFrom ) {
	    LOGGER.info("handling RemoveCasesFromTeamEvent " );
	
	    Team parentEntity = repository.findById(parentId).get();
	    Case_ child = registry.project( Case_.class, removeFrom.getCase_Id());
	    
	    parentEntity.getCases().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Campaigns
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Team
     */
    public Team addToCampaigns( UUID parentId, Campaign addTo ) {
	    LOGGER.info("handling AssignCampaignsToTeamEvent - " );
	    
	    Team parentEntity = repository.findById(parentId).get();
	    Campaign child = registry.project( Campaign.class, addTo.getCampaignId());
	    
	    parentEntity.getCampaigns().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Campaigns
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Team
     */
	public Team removeFromCampaigns( UUID parentId, Campaign removeFrom ) {
	    LOGGER.info("handling RemoveCampaignsFromTeamEvent " );
	
	    Team parentEntity = repository.findById(parentId).get();
	    Campaign child = registry.project( Campaign.class, removeFrom.getCampaignId());
	    
	    parentEntity.getCampaigns().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the Team via an FindTeamQuery
     * @return 	query	FindTeamQuery
     */
    @SuppressWarnings("unused")
    public Team find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a Team - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all Teams
     *
     * @param	query	FindAllTeamQuery 
     * @return 	List<Team> 
     */
    @SuppressWarnings("unused")
    public List<Team> findAll( FindAllTeamQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all Team - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final TeamRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(TeamEntityProjector.class.getName());

}
