#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.analyticsOnDjango
requirements.txt=.analyticsOnDjango
admin.py=.analyticsOnDjango
apps.py=.analyticsOnDjango
appUrls.py=.analyticsOnDjango
setup.py=.analyticsOnDjango
README.rst=.analyticsOnDjango
LICENSE=.analyticsOnDjango
Dockerfile=.analyticsOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.analyticsOnDjango.mainsite
wsgi.py=.analyticsOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.analyticsOnDjango.models
__classes__Delegate.py=.analyticsOnDjango.delegates
__classes__Test.py=.analyticsOnDjango.tests
__classes__View.py=.analyticsOnDjango.views
__classes__Urls.py=.analyticsOnDjango.urls
__enums__.py=.analyticsOnDjango.models
Exceptions.py=.analyticsOnDjango.exceptions
empty.doc=.analyticsOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.analyticsOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.analyticsOnDjango.mainsite,.analyticsOnDjango.models,.analyticsOnDjango.delegates,.analyticsOnDjango.tests,.analyticsOnDjango.views,.analyticsOnDjango.urls,.analyticsOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json