/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Advertising Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;

/**
 * Test AdSlot class.
 *
 * @author Harbormaster Dev Team
 */
public class AdSlotTest{

        // ------------------------------------
		// default constructor
	    // ------------------------------------
		public AdSlotTest() {
			LOGGER.setUseParentHandlers(false);	// only want to output to the provided LogHandler
		}

		// test methods
		@Test
		/**
		 * Full Create-Read-Update-Delete of a AdSlot, through a
		 * AdSlotTest.
		 */
		public void testCRUD() throws Throwable {
			try {
				LOGGER.info("**********************************************************");
				LOGGER.info("Beginning full CRUD test on AdSlot...");

				testCreate();
//				testRead();
//				testUpdate();
				testGetAll();
//				testDelete();

				LOGGER.info("Successfully ran a full test on AdSlotTest...");
				LOGGER.info("**********************************************************");
				LOGGER.info("");
			} catch (Throwable e) {
				throw e;
			} finally {
				if (handler != null) {
					handler.flush();
					LOGGER.removeHandler(handler);
				}
			}
		}

		/** 
		 * Tests creating a new AdSlot.
		 */
		public void testCreate() throws Throwable {
			LOGGER.info( "\n======== CREATE ======== ");
			LOGGER.info( "-- Attempting to create a AdSlot");

			StringBuilder msg = new StringBuilder( "-- Failed to create a AdSlot" );

			try {            
				AdSlot entity = AdSlotService.getAdSlotInstance().createAdSlot( generateNewEntity() );
				thePrimaryKey = entity.getAdSlotId();
				LOGGER.info( "-- Successfully created a AdSlot with primary key" + thePrimaryKey );
			}
			catch (Exception e) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests reading a AdSlot. 
		 */
		public AdSlot testRead() throws Throwable {
			LOGGER.info( "\n======== READ ======== ");
			LOGGER.info( "-- Reading a previously created AdSlot" );

			AdSlot entity = null;
			StringBuilder msg = new StringBuilder( "-- Failed to read AdSlot with primary key" );
			msg.append( thePrimaryKey );
			
			AdSlotFetchOneSummary fetchOneSummary = new AdSlotFetchOneSummary( thePrimaryKey );

			try {
				entity = AdSlotService.getAdSlotInstance().getAdSlot( fetchOneSummary );

				assertNotNull( entity,msg.toString() );

				LOGGER.info( "-- Successfully found AdSlot " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
			
			return entity;
		}

		/** 
		 * Tests updating a AdSlot.
		 */
		public void testUpdate() throws Throwable {
			LOGGER.info( "\n======== UPDATE ======== ");
			LOGGER.info( "-- Attempting to update a AdSlot." );

			StringBuilder msg = new StringBuilder( "Failed to update a AdSlot : " );        
			AdSlot entity = null;

			try {            
				entity = testRead();

				assertNotNull( entity, msg.toString() );

				LOGGER.info( "-- Now updating the created AdSlot." );

				// for use later on...
				thePrimaryKey = entity.getAdSlotId();

				AdSlotService proxy = AdSlotService.getAdSlotInstance();            
				proxy.updateAdSlot( entity );   

				LOGGER.info( "-- Successfully saved AdSlot - " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : primarykey = " + thePrimaryKey + " : entity-" +  entity + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests deleting a AdSlot.
		 */
		public void testDelete() throws Throwable {
			LOGGER.info( "\n======== DELETE ======== ");
			LOGGER.info( "-- Deleting a previously created AdSlot." );

			try{
			    AdSlot entity = testRead(); 
				AdSlotService.getAdSlotInstance().delete( entity );

				LOGGER.info( "-- Successfully deleted AdSlot with primary key " + thePrimaryKey );            
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( "-- Failed to delete AdSlot with primary key " + thePrimaryKey );

				throw e;
			}
		}

		/**
		 * Tests getting all AdSlots.
		 */
		public void testGetAll() throws Throwable {    
			LOGGER.info( "======== GETALL ======== ");
			LOGGER.info( "-- Retrieving Collection of AdSlots:" );

			StringBuilder msg = new StringBuilder( "-- Failed to get all AdSlot : " );        
			List<AdSlot> collection  = null;

			try {
				// call the static get method on the AdSlotService
				collection = AdSlotService.getAdSlotInstance().getAllAdSlot();

				if ( collection == null || collection.size() == 0 ) {
					LOGGER.warning( unexpectedErrorMsg );
					LOGGER.warning( msg.toString() + " Empty collection returned."  );
				}
				else {
					// Now print out the values
					AdSlot entity = null;            
					Iterator<AdSlot> iter = collection.iterator();
					int index = 1;

					while( iter.hasNext() ) {
						// Retrieve the entity   
						entity = iter.next();

						assertNotNull( entity,"-- null entity in Collection." );
						assertNotNull( entity.getAdSlotId(), "-- entity in Collection has a null primary key" );        

						LOGGER.info( " - " + String.valueOf(index) + ". " + entity.toString() );
						index++;
					}
				}
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/**
		 * Assigns a common log handler for each test class in the suite
		 * @param		handler	Handler
		 * @return		AdSlotTest
		 */
		public AdSlotTest setHandler(Handler handler) {
			this.handler = handler;
			LOGGER.addHandler(handler); // assign so the LOGGER can only output results to the Handler
			return this;
		}

		/**
		 * Returns a new populated AdSlot
		 * 
		 * @return AdSlot
		 */
		protected AdSlot generateNewEntity() {
			AdSlot entity = new AdSlot( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  0,  0,  new Money(),  null,  new HashSet<>(),  new HashSet<>(),  AdFormat.values()[0] );
			
			return( entity );
		}

		//-----------------------------------------------------
		// attributes 
		//-----------------------------------------------------
		protected UUID thePrimaryKey 						= null;
		private final Logger LOGGER 						= Logger.getLogger(AdSlotTest.class.getName());
		private Handler handler 							= null;
		private String unexpectedErrorMsg 					= ":::::::::::::: Unexpected Error :::::::::::::::::";
	}
