/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Aerospace Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>BuildScheduleValidation</h2>
 * <p>
 * The BuildSchedule Validation  handles state validation of a BuildSchedule include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/21/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Aerospace Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>Metadata describing this Aerospace HCIDL document.</td></tr>
 *          <tr><td>industry</td><td>Aerospace</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateBuildScheduleCommand</li>
 *      <li>UpdateBuildScheduleCommand</li>
 *      <li>DeleteBuildScheduleCommand</li>
 *set( false = false )
   *       <li>AssignProductionOrdersToBuildScheduleCommand</li>
 *       <li>RemoveProductionOrdersFromBuildScheduleCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class BuildScheduleValidator {

	/**
	 * default constructor
	 */
	protected BuildScheduleValidator() {
	}


	/**
	 * handles creation validation for a BuildSchedule
	 */
	public void validate( CreateBuildScheduleCommand buildSchedule )throws ValidationException {
		if ( buildSchedule == null )
		throw new ValidationException( "BuildSchedule", "validating CreateBuildScheduleCommand" );
		if ( buildSchedule.getScheduleNumber() == null )
		throw new ValidationException( "BuildSchedule", "validating access on getScheduleNumber" );
	}

	/**
	 * handles update validation for a BuildSchedule
	 */
	public void validate( UpdateBuildScheduleCommand buildSchedule ) throws ValidationException {
		if ( buildSchedule == null )
		throw new ValidationException( "BuildSchedule", "validating UpdateBuildScheduleCommand" );
		if ( buildSchedule.getScheduleNumber() == null )
		throw new ValidationException( "BuildSchedule", "validating method getScheduleNumber" );
	}

/**
 * handles delete validation for a BuildSchedule
 */
	public void validate( DeleteBuildScheduleCommand buildSchedule ) throws ValidationException {
		if ( buildSchedule == null )
			throw new ValidationException( "BuildSchedule", "validating DeleteBuildScheduleCommand" );
	}

/**
 * handles fetchOne validation for a BuildSchedule
 */
	public void validate( BuildScheduleFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "BuildSchedule", "validating summary" );
	}


	/**
	 * handles add to ProductionOrders validation for a BuildSchedule
	 *
	 * @param	command AssignProductionOrdersToBuildScheduleCommand
	 */
	public void validate( AssignProductionOrdersToBuildScheduleCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "BuildSchedule", "validating AssignProductionOrdersToBuildScheduleCommand" );

		if ( command.getBuildScheduleId() == null )
		throw new ValidationException( "BuildSchedule", "validating identity on AssignProductionOrdersToBuildScheduleCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "BuildSchedule", "validating addTo attribute on AssignProductionOrdersToBuildScheduleCommand" );

	}

	/**
	 * handles remove from ProductionOrders validation for a BuildSchedule
	 *
	 * @param	command RemoveProductionOrdersFromBuildScheduleCommand
	 */
	public void validate( RemoveProductionOrdersFromBuildScheduleCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("BuildSchedule", "validating RemoveProductionOrdersFromBuildScheduleCommand" );

		if( command.getBuildScheduleId() == null )
			throw new ValidationException("BuildSchedule", "validating id on RemoveProductionOrdersFromBuildScheduleCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("BuildSchedule", "validating remove from RemoveProductionOrdersFromBuildScheduleCommand" );

		if( command.getRemoveFrom().getProductionOrderId() == null )
			throw new ValidationException("BuildSchedule", "validating id on remove from RemoveProductionOrdersFromBuildScheduleCommand" );
	}


}
