package com.harbormaster.aggregate;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.axonframework.commandhandling.CommandHandler;
import org.axonframework.modelling.command.AggregateMember;
import org.axonframework.eventsourcing.EventSourcingHandler;
import org.axonframework.modelling.command.AggregateIdentifier;
import static org.axonframework.modelling.command.AggregateLifecycle.apply;
import org.axonframework.spring.stereotype.Aggregate;
import org.springframework.context.annotation.Profile;

/**
 * <h2>ProductPricingAggregate</h2>
 * <p>
 * The ProductPricing aggregate is the authoritative consistency boundary for all
 * branch-related operations. It validates incoming commands, enforces
 * business rules, maintains the integrity of the ProductPricing domain, and emits
 * immutable domain events representing state changes.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>ECommerce Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core e-commerce capabilities across catalog, pricing, cart, order, payment, fulfillment, promotions, taxation, and marketplace operations.</td></tr>
 *          <tr><td>industry</td><td>ECommerce</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateProductPricingCommand</li>
 *      <li>UpdateProductPricingCommand</li>
 *      <li>DeleteProductPricingCommand</li>
 *      </ul>
 *
 * <h3>Associations</h3>
 * <ul>
 *       <li>AssignVariantToProductPricingCommand</li>
 *       <li>UnAssignVariantFromProductPricingCommand</li>
 *       <li>AssignChannelToProductPricingCommand</li>
 *       <li>UnAssignChannelFromProductPricingCommand</li>
 *  </ul>
 *  <ul>
 *
 *
 * <h3>Events Emitted</h3>
 *      <ul>
 *      <li>CreateProductPricingEvent</li>
 *      <li>UpdateProductPricingEvent</li>
 *      <li>DeleteProductPricingEvent</li>
   *       <li>AssignVariantToProductPricingEvent</li>
 *       <li>UnAssignVariantFromProductPricingEvent</li>
  *       <li>AssignChannelToProductPricingEvent</li>
 *       <li>UnAssignChannelFromProductPricingEvent</li>
   *        </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Aggregate
public class ProductPricingAggregate {  

	// -----------------------------------------
	// Axon requires an empty constructor
    // -----------------------------------------
    public ProductPricingAggregate() {
    }

	// ----------------------------------------------
	// intrinsic command handlers
	// ----------------------------------------------
    @CommandHandler
    public ProductPricingAggregate(CreateProductPricingCommand command) throws Exception {
    	LOGGER.info( "Handling command CreateProductPricingCommand" );
    	CreateProductPricingEvent event = new CreateProductPricingEvent(command.getProductPricingId(), command.getListPrice(), command.getSalePrice(), command.getValidFrom(), command.getValidTo());
    	
        apply(event);
    }

    @CommandHandler
    public void handle(UpdateProductPricingCommand command) throws Exception {
    	LOGGER.info( "handling command UpdateProductPricingCommand" );
    	UpdateProductPricingEvent event = new UpdateProductPricingEvent(command.getProductPricingId(), command.getListPrice(), command.getSalePrice(), command.getValidFrom(), command.getValidTo(), command.getVariant(), command.getChannel());        
    	
        apply(event);
    }

    @CommandHandler
    public void handle(DeleteProductPricingCommand command) throws Exception {
    	LOGGER.info( "Handling command DeleteProductPricingCommand" );
        apply(new DeleteProductPricingEvent(command.getProductPricingId()));
    }

	// ----------------------------------------------
	// association command handlers
	// ----------------------------------------------

    // single association commands
    @CommandHandler
    public void handle(AssignVariantToProductPricingCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignVariantToProductPricingCommand" );
    	
    	if (  variant != null && variant.getProductVariantId() == command.getAssignment().getProductVariantId() )
    		throw new ProcessingException( "Variant already assigned with id " + command.getAssignment().getProductVariantId() );  
    		
        apply(new AssignVariantToProductPricingEvent(command.getProductPricingId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignVariantFromProductPricingCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignVariantFromProductPricingCommand" );

    	if (  variant == null )
    		throw new ProcessingException( "Variant already has nothing assigned." );  

    	apply(new UnAssignVariantFromProductPricingEvent(command.getProductPricingId()));
    }
    @CommandHandler
    public void handle(AssignChannelToProductPricingCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignChannelToProductPricingCommand" );
    	
    	if (  channel != null && channel.getChannelId() == command.getAssignment().getChannelId() )
    		throw new ProcessingException( "Channel already assigned with id " + command.getAssignment().getChannelId() );  
    		
        apply(new AssignChannelToProductPricingEvent(command.getProductPricingId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignChannelFromProductPricingCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignChannelFromProductPricingCommand" );

    	if (  channel == null )
    		throw new ProcessingException( "Channel already has nothing assigned." );  

    	apply(new UnAssignChannelFromProductPricingEvent(command.getProductPricingId()));
    }

    // multiple association commands

	// ----------------------------------------------
	// intrinsic event source handlers
	// ----------------------------------------------
    @EventSourcingHandler
    void on(CreateProductPricingEvent event) {	
    	LOGGER.info( "Event sourcing CreateProductPricingEvent" );
    	this.productPricingId = event.getProductPricingId();
        this.listPrice = event.getListPrice();
        this.salePrice = event.getSalePrice();
        this.validFrom = event.getValidFrom();
        this.validTo = event.getValidTo();
    }
    
    @EventSourcingHandler
    void on(UpdateProductPricingEvent event) {
    	LOGGER.info( "Event sourcing classObject.getUpdateEventAlias()}" );
        this.listPrice = event.getListPrice();
        this.salePrice = event.getSalePrice();
        this.validFrom = event.getValidFrom();
        this.validTo = event.getValidTo();
        this.variant = event.getVariant();
        this.channel = event.getChannel();
    }   

	// ----------------------------------------------
	// association event source handlers
	// ----------------------------------------------
	// single associations
    @EventSourcingHandler
    void on(AssignVariantToProductPricingEvent event ) {	
    	LOGGER.info( "Event sourcing AssignVariantToProductPricingEvent" );
    	this.variant = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignVariantFromProductPricingEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignVariantFromProductPricingEvent" );
		this.variant = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignChannelToProductPricingEvent event ) {	
    	LOGGER.info( "Event sourcing AssignChannelToProductPricingEvent" );
    	this.channel = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignChannelFromProductPricingEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignChannelFromProductPricingEvent" );
		this.channel = null;
	}


    // ------------------------------------------
    // attributes
    // ------------------------------------------
	
    @AggregateIdentifier
    private UUID productPricingId;
    
    private Money listPrice;
    private Money salePrice;
    private  Date validFrom;
    private  Date validTo;
    private ProductVariant variant = null;
    private Channel channel = null;

    private static final Logger LOGGER 	= Logger.getLogger(ProductPricingAggregate.class.getName());
}
