#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.insuranceOnDjango
requirements.txt=.insuranceOnDjango
admin.py=.insuranceOnDjango
apps.py=.insuranceOnDjango
appUrls.py=.insuranceOnDjango
setup.py=.insuranceOnDjango
README.rst=.insuranceOnDjango
LICENSE=.insuranceOnDjango
Dockerfile=.insuranceOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.insuranceOnDjango.mainsite
wsgi.py=.insuranceOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.insuranceOnDjango.models
__classes__Delegate.py=.insuranceOnDjango.delegates
__classes__Test.py=.insuranceOnDjango.tests
__classes__View.py=.insuranceOnDjango.views
__classes__Urls.py=.insuranceOnDjango.urls
__enums__.py=.insuranceOnDjango.models
Exceptions.py=.insuranceOnDjango.exceptions
empty.doc=.insuranceOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.insuranceOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.insuranceOnDjango.mainsite,.insuranceOnDjango.models,.insuranceOnDjango.delegates,.insuranceOnDjango.tests,.insuranceOnDjango.views,.insuranceOnDjango.urls,.insuranceOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json