/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Healthcare Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.api;

import java.util.*;

import jakarta.persistence.*

//-----------------------------------------------------------
// Query definitions
//-----------------------------------------------------------

// -----------------------------------------
// HealthSystem Queries 
// -----------------------------------------

data class LoadHealthSystemFilter(val healthSystemId :  UUID? = null )

class FindHealthSystemQuery(val filter: LoadHealthSystemFilter = LoadHealthSystemFilter()) {
    override fun toString(): String = "LoadHealthSystemQuery"
}

class FindAllHealthSystemQuery() {
    override fun toString(): String = "LoadAllHealthSystemQuery"
}

data class HealthSystemFetchOneSummary(@Id var healthSystemId : UUID? = null) {
}





// -----------------------------------------
// Facility Queries 
// -----------------------------------------

data class LoadFacilityFilter(val facilityId :  UUID? = null )

class FindFacilityQuery(val filter: LoadFacilityFilter = LoadFacilityFilter()) {
    override fun toString(): String = "LoadFacilityQuery"
}

class FindAllFacilityQuery() {
    override fun toString(): String = "LoadAllFacilityQuery"
}

data class FacilityFetchOneSummary(@Id var facilityId : UUID? = null) {
}





// -----------------------------------------
// Department Queries 
// -----------------------------------------

data class LoadDepartmentFilter(val departmentId :  UUID? = null )

class FindDepartmentQuery(val filter: LoadDepartmentFilter = LoadDepartmentFilter()) {
    override fun toString(): String = "LoadDepartmentQuery"
}

class FindAllDepartmentQuery() {
    override fun toString(): String = "LoadAllDepartmentQuery"
}

data class DepartmentFetchOneSummary(@Id var departmentId : UUID? = null) {
}





// -----------------------------------------
// CareTeam Queries 
// -----------------------------------------

data class LoadCareTeamFilter(val careTeamId :  UUID? = null )

class FindCareTeamQuery(val filter: LoadCareTeamFilter = LoadCareTeamFilter()) {
    override fun toString(): String = "LoadCareTeamQuery"
}

class FindAllCareTeamQuery() {
    override fun toString(): String = "LoadAllCareTeamQuery"
}

data class CareTeamFetchOneSummary(@Id var careTeamId : UUID? = null) {
}





// -----------------------------------------
// Clinician Queries 
// -----------------------------------------

data class LoadClinicianFilter(val clinicianId :  UUID? = null )

class FindClinicianQuery(val filter: LoadClinicianFilter = LoadClinicianFilter()) {
    override fun toString(): String = "LoadClinicianQuery"
}

class FindAllClinicianQuery() {
    override fun toString(): String = "LoadAllClinicianQuery"
}

data class ClinicianFetchOneSummary(@Id var clinicianId : UUID? = null) {
}





// -----------------------------------------
// Patient Queries 
// -----------------------------------------

data class LoadPatientFilter(val patientId :  UUID? = null )

class FindPatientQuery(val filter: LoadPatientFilter = LoadPatientFilter()) {
    override fun toString(): String = "LoadPatientQuery"
}

class FindAllPatientQuery() {
    override fun toString(): String = "LoadAllPatientQuery"
}

data class PatientFetchOneSummary(@Id var patientId : UUID? = null) {
}





// -----------------------------------------
// Appointment Queries 
// -----------------------------------------

data class LoadAppointmentFilter(val appointmentId :  UUID? = null )

class FindAppointmentQuery(val filter: LoadAppointmentFilter = LoadAppointmentFilter()) {
    override fun toString(): String = "LoadAppointmentQuery"
}

class FindAllAppointmentQuery() {
    override fun toString(): String = "LoadAllAppointmentQuery"
}

data class AppointmentFetchOneSummary(@Id var appointmentId : UUID? = null) {
}





// -----------------------------------------
// Encounter Queries 
// -----------------------------------------

data class LoadEncounterFilter(val encounterId :  UUID? = null )

class FindEncounterQuery(val filter: LoadEncounterFilter = LoadEncounterFilter()) {
    override fun toString(): String = "LoadEncounterQuery"
}

class FindAllEncounterQuery() {
    override fun toString(): String = "LoadAllEncounterQuery"
}

data class EncounterFetchOneSummary(@Id var encounterId : UUID? = null) {
}





// -----------------------------------------
// Admission Queries 
// -----------------------------------------

data class LoadAdmissionFilter(val admissionId :  UUID? = null )

class FindAdmissionQuery(val filter: LoadAdmissionFilter = LoadAdmissionFilter()) {
    override fun toString(): String = "LoadAdmissionQuery"
}

class FindAllAdmissionQuery() {
    override fun toString(): String = "LoadAllAdmissionQuery"
}

data class AdmissionFetchOneSummary(@Id var admissionId : UUID? = null) {
}





// -----------------------------------------
// Discharge Queries 
// -----------------------------------------

data class LoadDischargeFilter(val dischargeId :  UUID? = null )

class FindDischargeQuery(val filter: LoadDischargeFilter = LoadDischargeFilter()) {
    override fun toString(): String = "LoadDischargeQuery"
}

class FindAllDischargeQuery() {
    override fun toString(): String = "LoadAllDischargeQuery"
}

data class DischargeFetchOneSummary(@Id var dischargeId : UUID? = null) {
}





// -----------------------------------------
// ClinicalOrder Queries 
// -----------------------------------------

data class LoadClinicalOrderFilter(val clinicalOrderId :  UUID? = null )

class FindClinicalOrderQuery(val filter: LoadClinicalOrderFilter = LoadClinicalOrderFilter()) {
    override fun toString(): String = "LoadClinicalOrderQuery"
}

class FindAllClinicalOrderQuery() {
    override fun toString(): String = "LoadAllClinicalOrderQuery"
}

data class ClinicalOrderFetchOneSummary(@Id var clinicalOrderId : UUID? = null) {
}





// -----------------------------------------
// MedicationOrder Queries 
// -----------------------------------------

data class LoadMedicationOrderFilter(val medicationOrderId :  UUID? = null )

class FindMedicationOrderQuery(val filter: LoadMedicationOrderFilter = LoadMedicationOrderFilter()) {
    override fun toString(): String = "LoadMedicationOrderQuery"
}

class FindAllMedicationOrderQuery() {
    override fun toString(): String = "LoadAllMedicationOrderQuery"
}

data class MedicationOrderFetchOneSummary(@Id var medicationOrderId : UUID? = null) {
}





// -----------------------------------------
// Laboratory Queries 
// -----------------------------------------

data class LoadLaboratoryFilter(val laboratoryId :  UUID? = null )

class FindLaboratoryQuery(val filter: LoadLaboratoryFilter = LoadLaboratoryFilter()) {
    override fun toString(): String = "LoadLaboratoryQuery"
}

class FindAllLaboratoryQuery() {
    override fun toString(): String = "LoadAllLaboratoryQuery"
}

data class LaboratoryFetchOneSummary(@Id var laboratoryId : UUID? = null) {
}





// -----------------------------------------
// LaboratoryOrder Queries 
// -----------------------------------------

data class LoadLaboratoryOrderFilter(val laboratoryOrderId :  UUID? = null )

class FindLaboratoryOrderQuery(val filter: LoadLaboratoryOrderFilter = LoadLaboratoryOrderFilter()) {
    override fun toString(): String = "LoadLaboratoryOrderQuery"
}

class FindAllLaboratoryOrderQuery() {
    override fun toString(): String = "LoadAllLaboratoryOrderQuery"
}

data class LaboratoryOrderFetchOneSummary(@Id var laboratoryOrderId : UUID? = null) {
}





// -----------------------------------------
// LabResult Queries 
// -----------------------------------------

data class LoadLabResultFilter(val labResultId :  UUID? = null )

class FindLabResultQuery(val filter: LoadLabResultFilter = LoadLabResultFilter()) {
    override fun toString(): String = "LoadLabResultQuery"
}

class FindAllLabResultQuery() {
    override fun toString(): String = "LoadAllLabResultQuery"
}

data class LabResultFetchOneSummary(@Id var labResultId : UUID? = null) {
}





// -----------------------------------------
// ImagingCenter Queries 
// -----------------------------------------

data class LoadImagingCenterFilter(val imagingCenterId :  UUID? = null )

class FindImagingCenterQuery(val filter: LoadImagingCenterFilter = LoadImagingCenterFilter()) {
    override fun toString(): String = "LoadImagingCenterQuery"
}

class FindAllImagingCenterQuery() {
    override fun toString(): String = "LoadAllImagingCenterQuery"
}

data class ImagingCenterFetchOneSummary(@Id var imagingCenterId : UUID? = null) {
}





// -----------------------------------------
// ImagingOrder Queries 
// -----------------------------------------

data class LoadImagingOrderFilter(val imagingOrderId :  UUID? = null )

class FindImagingOrderQuery(val filter: LoadImagingOrderFilter = LoadImagingOrderFilter()) {
    override fun toString(): String = "LoadImagingOrderQuery"
}

class FindAllImagingOrderQuery() {
    override fun toString(): String = "LoadAllImagingOrderQuery"
}

data class ImagingOrderFetchOneSummary(@Id var imagingOrderId : UUID? = null) {
}





// -----------------------------------------
// ImagingReport Queries 
// -----------------------------------------

data class LoadImagingReportFilter(val imagingReportId :  UUID? = null )

class FindImagingReportQuery(val filter: LoadImagingReportFilter = LoadImagingReportFilter()) {
    override fun toString(): String = "LoadImagingReportQuery"
}

class FindAllImagingReportQuery() {
    override fun toString(): String = "LoadAllImagingReportQuery"
}

data class ImagingReportFetchOneSummary(@Id var imagingReportId : UUID? = null) {
}





// -----------------------------------------
// ProcedureOrder Queries 
// -----------------------------------------

data class LoadProcedureOrderFilter(val procedureOrderId :  UUID? = null )

class FindProcedureOrderQuery(val filter: LoadProcedureOrderFilter = LoadProcedureOrderFilter()) {
    override fun toString(): String = "LoadProcedureOrderQuery"
}

class FindAllProcedureOrderQuery() {
    override fun toString(): String = "LoadAllProcedureOrderQuery"
}

data class ProcedureOrderFetchOneSummary(@Id var procedureOrderId : UUID? = null) {
}





// -----------------------------------------
// Procedure Queries 
// -----------------------------------------

data class LoadProcedureFilter(val procedureId :  UUID? = null )

class FindProcedureQuery(val filter: LoadProcedureFilter = LoadProcedureFilter()) {
    override fun toString(): String = "LoadProcedureQuery"
}

class FindAllProcedureQuery() {
    override fun toString(): String = "LoadAllProcedureQuery"
}

data class ProcedureFetchOneSummary(@Id var procedureId : UUID? = null) {
}





// -----------------------------------------
// Pharmacy Queries 
// -----------------------------------------

data class LoadPharmacyFilter(val pharmacyId :  UUID? = null )

class FindPharmacyQuery(val filter: LoadPharmacyFilter = LoadPharmacyFilter()) {
    override fun toString(): String = "LoadPharmacyQuery"
}

class FindAllPharmacyQuery() {
    override fun toString(): String = "LoadAllPharmacyQuery"
}

data class PharmacyFetchOneSummary(@Id var pharmacyId : UUID? = null) {
}





// -----------------------------------------
// MedicationDispense Queries 
// -----------------------------------------

data class LoadMedicationDispenseFilter(val medicationDispenseId :  UUID? = null )

class FindMedicationDispenseQuery(val filter: LoadMedicationDispenseFilter = LoadMedicationDispenseFilter()) {
    override fun toString(): String = "LoadMedicationDispenseQuery"
}

class FindAllMedicationDispenseQuery() {
    override fun toString(): String = "LoadAllMedicationDispenseQuery"
}

data class MedicationDispenseFetchOneSummary(@Id var medicationDispenseId : UUID? = null) {
}





// -----------------------------------------
// Diagnosis Queries 
// -----------------------------------------

data class LoadDiagnosisFilter(val diagnosisId :  UUID? = null )

class FindDiagnosisQuery(val filter: LoadDiagnosisFilter = LoadDiagnosisFilter()) {
    override fun toString(): String = "LoadDiagnosisQuery"
}

class FindAllDiagnosisQuery() {
    override fun toString(): String = "LoadAllDiagnosisQuery"
}

data class DiagnosisFetchOneSummary(@Id var diagnosisId : UUID? = null) {
}





// -----------------------------------------
// Observation Queries 
// -----------------------------------------

data class LoadObservationFilter(val observationId :  UUID? = null )

class FindObservationQuery(val filter: LoadObservationFilter = LoadObservationFilter()) {
    override fun toString(): String = "LoadObservationQuery"
}

class FindAllObservationQuery() {
    override fun toString(): String = "LoadAllObservationQuery"
}

data class ObservationFetchOneSummary(@Id var observationId : UUID? = null) {
}





// -----------------------------------------
// CarePlan Queries 
// -----------------------------------------

data class LoadCarePlanFilter(val carePlanId :  UUID? = null )

class FindCarePlanQuery(val filter: LoadCarePlanFilter = LoadCarePlanFilter()) {
    override fun toString(): String = "LoadCarePlanQuery"
}

class FindAllCarePlanQuery() {
    override fun toString(): String = "LoadAllCarePlanQuery"
}

data class CarePlanFetchOneSummary(@Id var carePlanId : UUID? = null) {
}





// -----------------------------------------
// CareTask Queries 
// -----------------------------------------

data class LoadCareTaskFilter(val careTaskId :  UUID? = null )

class FindCareTaskQuery(val filter: LoadCareTaskFilter = LoadCareTaskFilter()) {
    override fun toString(): String = "LoadCareTaskQuery"
}

class FindAllCareTaskQuery() {
    override fun toString(): String = "LoadAllCareTaskQuery"
}

data class CareTaskFetchOneSummary(@Id var careTaskId : UUID? = null) {
}





// -----------------------------------------
// Allergy Queries 
// -----------------------------------------

data class LoadAllergyFilter(val allergyId :  UUID? = null )

class FindAllergyQuery(val filter: LoadAllergyFilter = LoadAllergyFilter()) {
    override fun toString(): String = "LoadAllergyQuery"
}

class FindAllAllergyQuery() {
    override fun toString(): String = "LoadAllAllergyQuery"
}

data class AllergyFetchOneSummary(@Id var allergyId : UUID? = null) {
}





// -----------------------------------------
// Condition Queries 
// -----------------------------------------

data class LoadConditionFilter(val conditionId :  UUID? = null )

class FindConditionQuery(val filter: LoadConditionFilter = LoadConditionFilter()) {
    override fun toString(): String = "LoadConditionQuery"
}

class FindAllConditionQuery() {
    override fun toString(): String = "LoadAllConditionQuery"
}

data class ConditionFetchOneSummary(@Id var conditionId : UUID? = null) {
}





// -----------------------------------------
// InsurancePayer Queries 
// -----------------------------------------

data class LoadInsurancePayerFilter(val insurancePayerId :  UUID? = null )

class FindInsurancePayerQuery(val filter: LoadInsurancePayerFilter = LoadInsurancePayerFilter()) {
    override fun toString(): String = "LoadInsurancePayerQuery"
}

class FindAllInsurancePayerQuery() {
    override fun toString(): String = "LoadAllInsurancePayerQuery"
}

data class InsurancePayerFetchOneSummary(@Id var insurancePayerId : UUID? = null) {
}





// -----------------------------------------
// InsurancePlan Queries 
// -----------------------------------------

data class LoadInsurancePlanFilter(val insurancePlanId :  UUID? = null )

class FindInsurancePlanQuery(val filter: LoadInsurancePlanFilter = LoadInsurancePlanFilter()) {
    override fun toString(): String = "LoadInsurancePlanQuery"
}

class FindAllInsurancePlanQuery() {
    override fun toString(): String = "LoadAllInsurancePlanQuery"
}

data class InsurancePlanFetchOneSummary(@Id var insurancePlanId : UUID? = null) {
}





// -----------------------------------------
// Coverage Queries 
// -----------------------------------------

data class LoadCoverageFilter(val coverageId :  UUID? = null )

class FindCoverageQuery(val filter: LoadCoverageFilter = LoadCoverageFilter()) {
    override fun toString(): String = "LoadCoverageQuery"
}

class FindAllCoverageQuery() {
    override fun toString(): String = "LoadAllCoverageQuery"
}

data class CoverageFetchOneSummary(@Id var coverageId : UUID? = null) {
}





// -----------------------------------------
// Claim Queries 
// -----------------------------------------

data class LoadClaimFilter(val claimId :  UUID? = null )

class FindClaimQuery(val filter: LoadClaimFilter = LoadClaimFilter()) {
    override fun toString(): String = "LoadClaimQuery"
}

class FindAllClaimQuery() {
    override fun toString(): String = "LoadAllClaimQuery"
}

data class ClaimFetchOneSummary(@Id var claimId : UUID? = null) {
}





// -----------------------------------------
// Authorization Queries 
// -----------------------------------------

data class LoadAuthorizationFilter(val authorizationId :  UUID? = null )

class FindAuthorizationQuery(val filter: LoadAuthorizationFilter = LoadAuthorizationFilter()) {
    override fun toString(): String = "LoadAuthorizationQuery"
}

class FindAllAuthorizationQuery() {
    override fun toString(): String = "LoadAllAuthorizationQuery"
}

data class AuthorizationFetchOneSummary(@Id var authorizationId : UUID? = null) {
}





// -----------------------------------------
// Invoice Queries 
// -----------------------------------------

data class LoadInvoiceFilter(val invoiceId :  UUID? = null )

class FindInvoiceQuery(val filter: LoadInvoiceFilter = LoadInvoiceFilter()) {
    override fun toString(): String = "LoadInvoiceQuery"
}

class FindAllInvoiceQuery() {
    override fun toString(): String = "LoadAllInvoiceQuery"
}

data class InvoiceFetchOneSummary(@Id var invoiceId : UUID? = null) {
}





// -----------------------------------------
// Payment Queries 
// -----------------------------------------

data class LoadPaymentFilter(val paymentId :  UUID? = null )

class FindPaymentQuery(val filter: LoadPaymentFilter = LoadPaymentFilter()) {
    override fun toString(): String = "LoadPaymentQuery"
}

class FindAllPaymentQuery() {
    override fun toString(): String = "LoadAllPaymentQuery"
}

data class PaymentFetchOneSummary(@Id var paymentId : UUID? = null) {
}





// -----------------------------------------
// MedicalDevice Queries 
// -----------------------------------------

data class LoadMedicalDeviceFilter(val medicalDeviceId :  UUID? = null )

class FindMedicalDeviceQuery(val filter: LoadMedicalDeviceFilter = LoadMedicalDeviceFilter()) {
    override fun toString(): String = "LoadMedicalDeviceQuery"
}

class FindAllMedicalDeviceQuery() {
    override fun toString(): String = "LoadAllMedicalDeviceQuery"
}

data class MedicalDeviceFetchOneSummary(@Id var medicalDeviceId : UUID? = null) {
}





// -----------------------------------------
// SoftwareUpdate Queries 
// -----------------------------------------

data class LoadSoftwareUpdateFilter(val softwareUpdateId :  UUID? = null )

class FindSoftwareUpdateQuery(val filter: LoadSoftwareUpdateFilter = LoadSoftwareUpdateFilter()) {
    override fun toString(): String = "LoadSoftwareUpdateQuery"
}

class FindAllSoftwareUpdateQuery() {
    override fun toString(): String = "LoadAllSoftwareUpdateQuery"
}

data class SoftwareUpdateFetchOneSummary(@Id var softwareUpdateId : UUID? = null) {
}





// -----------------------------------------
// MedicalSupplier Queries 
// -----------------------------------------

data class LoadMedicalSupplierFilter(val medicalSupplierId :  UUID? = null )

class FindMedicalSupplierQuery(val filter: LoadMedicalSupplierFilter = LoadMedicalSupplierFilter()) {
    override fun toString(): String = "LoadMedicalSupplierQuery"
}

class FindAllMedicalSupplierQuery() {
    override fun toString(): String = "LoadAllMedicalSupplierQuery"
}

data class MedicalSupplierFetchOneSummary(@Id var medicalSupplierId : UUID? = null) {
}





// -----------------------------------------
// InventoryItem Queries 
// -----------------------------------------

data class LoadInventoryItemFilter(val inventoryItemId :  UUID? = null )

class FindInventoryItemQuery(val filter: LoadInventoryItemFilter = LoadInventoryItemFilter()) {
    override fun toString(): String = "LoadInventoryItemQuery"
}

class FindAllInventoryItemQuery() {
    override fun toString(): String = "LoadAllInventoryItemQuery"
}

data class InventoryItemFetchOneSummary(@Id var inventoryItemId : UUID? = null) {
}






