/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ECommerce Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>PayoutValidation</h2>
 * <p>
 * The Payout Validation  handles state validation of a Payout include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/21/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>ECommerce Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core e-commerce capabilities across catalog, pricing, cart, order, payment, fulfillment, promotions, taxation, and marketplace operations.</td></tr>
 *          <tr><td>industry</td><td>ECommerce</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreatePayoutCommand</li>
 *      <li>UpdatePayoutCommand</li>
 *      <li>DeletePayoutCommand</li>
 *set( false = false )
  *       <li>AssignSellerToPayoutCommand</li>
 *       <li>UnAssignSellerFromPayoutCommand</li>
   *       <li>AssignOrdersToPayoutCommand</li>
 *       <li>RemoveOrdersFromPayoutCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class PayoutValidator {

	/**
	 * default constructor
	 */
	protected PayoutValidator() {
	}


	/**
	 * handles creation validation for a Payout
	 */
	public void validate( CreatePayoutCommand payout )throws ValidationException {
		if ( payout == null )
		throw new ValidationException( "Payout", "validating CreatePayoutCommand" );
		if ( payout.getPayoutNumber() == null )
		throw new ValidationException( "Payout", "validating access on getPayoutNumber" );
		if ( payout.getAmount() == null )
		throw new ValidationException( "Payout", "validating access on getAmount" );
		if ( payout.getScheduledDate() == null )
		throw new ValidationException( "Payout", "validating access on getScheduledDate" );
		if ( payout.getPaidDate() == null )
		throw new ValidationException( "Payout", "validating access on getPaidDate" );
	}

	/**
	 * handles update validation for a Payout
	 */
	public void validate( UpdatePayoutCommand payout ) throws ValidationException {
		if ( payout == null )
		throw new ValidationException( "Payout", "validating UpdatePayoutCommand" );
		if ( payout.getPayoutNumber() == null )
		throw new ValidationException( "Payout", "validating method getPayoutNumber" );
		if ( payout.getAmount() == null )
		throw new ValidationException( "Payout", "validating method getAmount" );
		if ( payout.getScheduledDate() == null )
		throw new ValidationException( "Payout", "validating method getScheduledDate" );
		if ( payout.getPaidDate() == null )
		throw new ValidationException( "Payout", "validating method getPaidDate" );
	}

/**
 * handles delete validation for a Payout
 */
	public void validate( DeletePayoutCommand payout ) throws ValidationException {
		if ( payout == null )
			throw new ValidationException( "Payout", "validating DeletePayoutCommand" );
	}

/**
 * handles fetchOne validation for a Payout
 */
	public void validate( PayoutFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "Payout", "validating summary" );
	}

	/**
	 * handles assign Seller validation for a Payout
	 *
	 * @param	command AssignSellerToPayoutCommand
	 */
	public void validate( AssignSellerToPayoutCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Payout", "validating AssignSellerToPayoutCommand" );

		if ( command.getPayoutId() == null )
		throw new ValidationException( "Payout", "validating identifier on AssignSellerToPayoutCommand" );

		if ( command.getAssignment() == null )
			throw new ValidationException( "Payout", "validating assignment" );
	}

	/**
	 * handles unassign Seller validation for a Payout
	 *
	 * @param	command UnAssignSellerFromPayoutCommand
	 */
	public void validate( UnAssignSellerFromPayoutCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Payout", "validating UnAssignSellerFromPayoutCommand" );

		if ( command.getPayoutId() == null )
		throw new ValidationException( "Payout", "validating identity on UnAssignSellerFromPayoutCommand" );
	}

	/**
	 * handles add to Orders validation for a Payout
	 *
	 * @param	command AssignOrdersToPayoutCommand
	 */
	public void validate( AssignOrdersToPayoutCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "Payout", "validating AssignOrdersToPayoutCommand" );

		if ( command.getPayoutId() == null )
		throw new ValidationException( "Payout", "validating identity on AssignOrdersToPayoutCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "Payout", "validating addTo attribute on AssignOrdersToPayoutCommand" );

	}

	/**
	 * handles remove from Orders validation for a Payout
	 *
	 * @param	command RemoveOrdersFromPayoutCommand
	 */
	public void validate( RemoveOrdersFromPayoutCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("Payout", "validating RemoveOrdersFromPayoutCommand" );

		if( command.getPayoutId() == null )
			throw new ValidationException("Payout", "validating id on RemoveOrdersFromPayoutCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("Payout", "validating remove from RemoveOrdersFromPayoutCommand" );

		if( command.getRemoveFrom().getOrderId() == null )
			throw new ValidationException("Payout", "validating id on remove from RemoveOrdersFromPayoutCommand" );
	}


}
