/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Aerospace Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import org.axonframework.config.ProcessingGroup;
import org.axonframework.eventhandling.EventHandler;
import org.axonframework.queryhandling.QueryHandler;
import org.axonframework.queryhandling.QueryUpdateEmitter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>AircraftOrderProjector</h2>
 * <p>
 * The AircraftOrder Projector is responsible for maintaining the read model for
 * AircraftOrder entities. It subscribes to domain events published by the AircraftOrder
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Aerospace Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>Metadata describing this Aerospace HCIDL document.</td></tr>
 *          <tr><td>industry</td><td>Aerospace</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul><li>QueryGateway</li></ul>
 *
 * <h3>Queries Handled</h3>
 *		<ul>
 *      <li>FindAircraftOrderQuery</li>
 *      <li>FindAllAircraftOrderQuery</li>
 *		</ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
//@ProcessingGroup("aircraftOrder")
@Component("aircraftOrder-projector")
public class AircraftOrderProjector extends AircraftOrderEntityProjector {
		
	// core constructor
	public AircraftOrderProjector(ProjectorRegistry registry,
									AircraftOrderRepository repository,
									QueryUpdateEmitter queryUpdateEmitter ) {
        super(registry, repository);
        this.queryUpdateEmitter = queryUpdateEmitter;
    }	

	/*
     * @param	event CreateAircraftOrderEvent
     */
    @EventHandler( payloadType=CreateAircraftOrderEvent.class )
    public void handle( CreateAircraftOrderEvent event) {
	    LOGGER.info("handling CreateAircraftOrderEvent - " + event );
	    AircraftOrder entity = new AircraftOrder();
            entity.setAircraftOrderId( event.getAircraftOrderId() );
            entity.setOrderNumber( event.getOrderNumber() );
            entity.setTotalAmount( event.getTotalAmount() );
            entity.setStatus( event.getStatus() );
	    
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    create(entity);
        
        // ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllAircraftOrder( entity );
    }

    /*
     * @param	event UpdateAircraftOrderEvent
     */
    @EventHandler( payloadType=UpdateAircraftOrderEvent.class )
    public void handle( UpdateAircraftOrderEvent event) {
    	LOGGER.info("handling UpdateAircraftOrderEvent - " + event );
    	
	    AircraftOrder entity = new AircraftOrder();
            entity.setAircraftOrderId( event.getAircraftOrderId() );
            entity.setOrderNumber( event.getOrderNumber() );
            entity.setTotalAmount( event.getTotalAmount() );
            entity.setOperator( event.getOperator() );
            entity.setVariant( event.getVariant() );
            entity.setQuote( event.getQuote() );
            entity.setPurchaseAgreement( event.getPurchaseAgreement() );
            entity.setStatus( event.getStatus() );
 
    	// ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		update(entity);

    	// ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindAircraftOrder( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllAircraftOrder( entity );        
    }
    
    /*
     * @param	event DeleteAircraftOrderEvent
     */
    @EventHandler( payloadType=DeleteAircraftOrderEvent.class )
    public void handle( DeleteAircraftOrderEvent event) {
    	LOGGER.info("handling DeleteAircraftOrderEvent - " + event );
    	
    	// ------------------------------------------
    	// delete delegation
    	// ------------------------------------------
    	AircraftOrder entity = delete( event.getAircraftOrderId() );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllAircraftOrder( entity );

    }    

    /*
     * @param	event AssignOperatorToAircraftOrderEvent
     */
    @EventHandler( payloadType=AssignOperatorToAircraftOrderEvent.class)
    public void handle( AssignOperatorToAircraftOrderEvent event) {
	    LOGGER.info("handling AssignOperatorToAircraftOrderEvent - " + event );

	    // ------------------------------------------
	    // delegate to assignTo
	    // ------------------------------------------
	    AircraftOrder entity = assignOperator( event.getAircraftOrderId(), event.getAssignment() );

	    // ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindAircraftOrder( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllAircraftOrder( entity );
    }
    

	/*
	 * @param	event UnAssignOperatorFromAircraftOrderEvent
	 */
	@EventHandler( payloadType=UnAssignOperatorFromAircraftOrderEvent.class)
	public void handle( UnAssignOperatorFromAircraftOrderEvent event) {
	    LOGGER.info("handling UnAssignOperatorFromAircraftOrderEvent - " + event );

	    // ------------------------------------------
	    // delegate to unAssignFrom
	    // ------------------------------------------
	    AircraftOrder entity = unAssignOperator( event.getAircraftOrderId() );

		// ------------------------------------------
		// emit to subscribers that find one
		// ------------------------------------------    	
	    emitFindAircraftOrder( entity );
	
		// ------------------------------------------
		// emit to subscribers that find all
		// ------------------------------------------    	
	    emitFindAllAircraftOrder( entity );
	}

    /*
     * @param	event AssignVariantToAircraftOrderEvent
     */
    @EventHandler( payloadType=AssignVariantToAircraftOrderEvent.class)
    public void handle( AssignVariantToAircraftOrderEvent event) {
	    LOGGER.info("handling AssignVariantToAircraftOrderEvent - " + event );

	    // ------------------------------------------
	    // delegate to assignTo
	    // ------------------------------------------
	    AircraftOrder entity = assignVariant( event.getAircraftOrderId(), event.getAssignment() );

	    // ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindAircraftOrder( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllAircraftOrder( entity );
    }
    

	/*
	 * @param	event UnAssignVariantFromAircraftOrderEvent
	 */
	@EventHandler( payloadType=UnAssignVariantFromAircraftOrderEvent.class)
	public void handle( UnAssignVariantFromAircraftOrderEvent event) {
	    LOGGER.info("handling UnAssignVariantFromAircraftOrderEvent - " + event );

	    // ------------------------------------------
	    // delegate to unAssignFrom
	    // ------------------------------------------
	    AircraftOrder entity = unAssignVariant( event.getAircraftOrderId() );

		// ------------------------------------------
		// emit to subscribers that find one
		// ------------------------------------------    	
	    emitFindAircraftOrder( entity );
	
		// ------------------------------------------
		// emit to subscribers that find all
		// ------------------------------------------    	
	    emitFindAllAircraftOrder( entity );
	}

    /*
     * @param	event AssignQuoteToAircraftOrderEvent
     */
    @EventHandler( payloadType=AssignQuoteToAircraftOrderEvent.class)
    public void handle( AssignQuoteToAircraftOrderEvent event) {
	    LOGGER.info("handling AssignQuoteToAircraftOrderEvent - " + event );

	    // ------------------------------------------
	    // delegate to assignTo
	    // ------------------------------------------
	    AircraftOrder entity = assignQuote( event.getAircraftOrderId(), event.getAssignment() );

	    // ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindAircraftOrder( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllAircraftOrder( entity );
    }
    

	/*
	 * @param	event UnAssignQuoteFromAircraftOrderEvent
	 */
	@EventHandler( payloadType=UnAssignQuoteFromAircraftOrderEvent.class)
	public void handle( UnAssignQuoteFromAircraftOrderEvent event) {
	    LOGGER.info("handling UnAssignQuoteFromAircraftOrderEvent - " + event );

	    // ------------------------------------------
	    // delegate to unAssignFrom
	    // ------------------------------------------
	    AircraftOrder entity = unAssignQuote( event.getAircraftOrderId() );

		// ------------------------------------------
		// emit to subscribers that find one
		// ------------------------------------------    	
	    emitFindAircraftOrder( entity );
	
		// ------------------------------------------
		// emit to subscribers that find all
		// ------------------------------------------    	
	    emitFindAllAircraftOrder( entity );
	}

    /*
     * @param	event AssignPurchaseAgreementToAircraftOrderEvent
     */
    @EventHandler( payloadType=AssignPurchaseAgreementToAircraftOrderEvent.class)
    public void handle( AssignPurchaseAgreementToAircraftOrderEvent event) {
	    LOGGER.info("handling AssignPurchaseAgreementToAircraftOrderEvent - " + event );

	    // ------------------------------------------
	    // delegate to assignTo
	    // ------------------------------------------
	    AircraftOrder entity = assignPurchaseAgreement( event.getAircraftOrderId(), event.getAssignment() );

	    // ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindAircraftOrder( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllAircraftOrder( entity );
    }
    

	/*
	 * @param	event UnAssignPurchaseAgreementFromAircraftOrderEvent
	 */
	@EventHandler( payloadType=UnAssignPurchaseAgreementFromAircraftOrderEvent.class)
	public void handle( UnAssignPurchaseAgreementFromAircraftOrderEvent event) {
	    LOGGER.info("handling UnAssignPurchaseAgreementFromAircraftOrderEvent - " + event );

	    // ------------------------------------------
	    // delegate to unAssignFrom
	    // ------------------------------------------
	    AircraftOrder entity = unAssignPurchaseAgreement( event.getAircraftOrderId() );

		// ------------------------------------------
		// emit to subscribers that find one
		// ------------------------------------------    	
	    emitFindAircraftOrder( entity );
	
		// ------------------------------------------
		// emit to subscribers that find all
		// ------------------------------------------    	
	    emitFindAllAircraftOrder( entity );
	}




    /**
     * Method to retrieve the AircraftOrder via an AircraftOrderPrimaryKey.
     * @param 	id Long
     * @return 	AircraftOrder
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    @SuppressWarnings("unused")
    @QueryHandler
    public AircraftOrder handle( FindAircraftOrderQuery query ) 
    throws ProcessingException, IllegalArgumentException {
    	return find( query.getFilter().getAircraftOrderId() );
    }
    
    /**
     * Method to retrieve a collection of all AircraftOrders
     *
     * @param	query	FindAllAircraftOrderQuery 
     * @return 	List<AircraftOrder> 
     * @exception ProcessingException Thrown if any problems
     */
    @SuppressWarnings("unused")
    @QueryHandler
    public List<AircraftOrder> handle( FindAllAircraftOrderQuery query ) throws ProcessingException {
    	return findAll( query );
    }



/**
 * emit to subscription queries of type FindAircraftOrder,
 * but only if the id matches
 *
 * @param		entity	AircraftOrder
 */
	protected void emitFindAircraftOrder( AircraftOrder entity ) {
		LOGGER.info("handling emitFindAircraftOrder" );
		
	    queryUpdateEmitter.emit(FindAircraftOrderQuery.class,
	                            query -> query.getFilter().getAircraftOrderId().equals(entity.getAircraftOrderId()),
	                            entity);
	}
	
	/**
	 * unconditionally emit to subscription queries of type FindAllAircraftOrder
	 * 
	 * @param		entity	AircraftOrder
	 */
	protected void emitFindAllAircraftOrder( AircraftOrder entity ) {
		LOGGER.info("handling emitFindAllAircraftOrder" );
		
	    queryUpdateEmitter.emit(FindAllAircraftOrderQuery.class,
	                            query -> true,
	                            entity);
	}

	//--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
	private final QueryUpdateEmitter queryUpdateEmitter;
    private static final Logger LOGGER 	= Logger.getLogger(AircraftOrderProjector.class.getName());

}
