#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.fintechOnDjango
requirements.txt=.fintechOnDjango
admin.py=.fintechOnDjango
apps.py=.fintechOnDjango
appUrls.py=.fintechOnDjango
setup.py=.fintechOnDjango
README.rst=.fintechOnDjango
LICENSE=.fintechOnDjango
Dockerfile=.fintechOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.fintechOnDjango.mainsite
wsgi.py=.fintechOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.fintechOnDjango.models
__classes__Delegate.py=.fintechOnDjango.delegates
__classes__Test.py=.fintechOnDjango.tests
__classes__View.py=.fintechOnDjango.views
__classes__Urls.py=.fintechOnDjango.urls
__enums__.py=.fintechOnDjango.models
Exceptions.py=.fintechOnDjango.exceptions
empty.doc=.fintechOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.fintechOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.fintechOnDjango.mainsite,.fintechOnDjango.models,.fintechOnDjango.delegates,.fintechOnDjango.tests,.fintechOnDjango.views,.fintechOnDjango.urls,.fintechOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json