#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.inventoryOnDjango
requirements.txt=.inventoryOnDjango
admin.py=.inventoryOnDjango
apps.py=.inventoryOnDjango
appUrls.py=.inventoryOnDjango
setup.py=.inventoryOnDjango
README.rst=.inventoryOnDjango
LICENSE=.inventoryOnDjango
Dockerfile=.inventoryOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.inventoryOnDjango.mainsite
wsgi.py=.inventoryOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.inventoryOnDjango.models
__classes__Delegate.py=.inventoryOnDjango.delegates
__classes__Test.py=.inventoryOnDjango.tests
__classes__View.py=.inventoryOnDjango.views
__classes__Urls.py=.inventoryOnDjango.urls
__enums__.py=.inventoryOnDjango.models
Exceptions.py=.inventoryOnDjango.exceptions
empty.doc=.inventoryOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.inventoryOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.inventoryOnDjango.mainsite,.inventoryOnDjango.models,.inventoryOnDjango.delegates,.inventoryOnDjango.tests,.inventoryOnDjango.views,.inventoryOnDjango.urls,.inventoryOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json