package com.harbormaster.aggregate;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.axonframework.commandhandling.CommandHandler;
import org.axonframework.modelling.command.AggregateMember;
import org.axonframework.eventsourcing.EventSourcingHandler;
import org.axonframework.modelling.command.AggregateIdentifier;
import static org.axonframework.modelling.command.AggregateLifecycle.apply;
import org.axonframework.spring.stereotype.Aggregate;
import org.springframework.context.annotation.Profile;

/**
 * <h2>TransferOrderLineAggregate</h2>
 * <p>
 * The TransferOrderLine aggregate is the authoritative consistency boundary for all
 * branch-related operations. It validates incoming commands, enforces
 * business rules, maintains the integrity of the TransferOrderLine domain, and emits
 * immutable domain events representing state changes.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>HCIDL Inventory Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical capability model for managing inventory across warehouses, locations, items, and stock movements.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateTransferOrderLineCommand</li>
 *      <li>UpdateTransferOrderLineCommand</li>
 *      <li>DeleteTransferOrderLineCommand</li>
 *      </ul>
 *
 * <h3>Associations</h3>
 * <ul>
 *       <li>AssignTransferOrderToTransferOrderLineCommand</li>
 *       <li>UnAssignTransferOrderFromTransferOrderLineCommand</li>
 *       <li>AssignSkuToTransferOrderLineCommand</li>
 *       <li>UnAssignSkuFromTransferOrderLineCommand</li>
 *       <li>AssignLotToTransferOrderLineCommand</li>
 *       <li>UnAssignLotFromTransferOrderLineCommand</li>
 *       <li>AssignFromLocationToTransferOrderLineCommand</li>
 *       <li>UnAssignFromLocationFromTransferOrderLineCommand</li>
 *       <li>AssignToLocationToTransferOrderLineCommand</li>
 *       <li>UnAssignToLocationFromTransferOrderLineCommand</li>
 *  </ul>
 *  <ul>
 *       <li>AssignSerialNumbersToTransferOrderLineCommand</li>
 *       <li>RemoveSerialNumbersFromTransferOrderLineCommand</li>
 *   </ul>
 *
 * <p>
 * @author Harbormaster Dev Team
 * </p>
 *
 *
 * <h3>Events Emitted</h3>
 *      <ul>
 *      <li>CreateTransferOrderLineEvent</li>
 *      <li>UpdateTransferOrderLineEvent</li>
 *      <li>DeleteTransferOrderLineEvent</li>
   *       <li>AssignTransferOrderToTransferOrderLineEvent</li>
 *       <li>UnAssignTransferOrderFromTransferOrderLineEvent</li>
  *       <li>AssignSkuToTransferOrderLineEvent</li>
 *       <li>UnAssignSkuFromTransferOrderLineEvent</li>
  *       <li>AssignLotToTransferOrderLineEvent</li>
 *       <li>UnAssignLotFromTransferOrderLineEvent</li>
  *       <li>AssignFromLocationToTransferOrderLineEvent</li>
 *       <li>UnAssignFromLocationFromTransferOrderLineEvent</li>
  *       <li>AssignToLocationToTransferOrderLineEvent</li>
 *       <li>UnAssignToLocationFromTransferOrderLineEvent</li>
   *       <li>AssignSerialNumbersToTransferOrderLineEvent</li>
 *       <li>RemoveSerialNumbersFromTransferOrderLineEvent</li>
  *        </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Aggregate
public class TransferOrderLineAggregate {  

	// -----------------------------------------
	// Axon requires an empty constructor
    // -----------------------------------------
    public TransferOrderLineAggregate() {
    }

	// ----------------------------------------------
	// intrinsic command handlers
	// ----------------------------------------------
    @CommandHandler
    public TransferOrderLineAggregate(CreateTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handling command CreateTransferOrderLineCommand" );
    	CreateTransferOrderLineEvent event = new CreateTransferOrderLineEvent(command.getTransferOrderLineId(), command.getLineNumber(), command.getQuantity(), command.getUnitOfMeasure(), command.getStockStatus());
    	
        apply(event);
    }

    @CommandHandler
    public void handle(UpdateTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "handling command UpdateTransferOrderLineCommand" );
    	UpdateTransferOrderLineEvent event = new UpdateTransferOrderLineEvent(command.getTransferOrderLineId(), command.getLineNumber(), command.getQuantity(), command.getTransferOrder(), command.getSku(), command.getLot(), command.getSerialNumbers(), command.getFromLocation(), command.getToLocation(), command.getUnitOfMeasure(), command.getStockStatus());        
    	
        apply(event);
    }

    @CommandHandler
    public void handle(DeleteTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handling command DeleteTransferOrderLineCommand" );
        apply(new DeleteTransferOrderLineEvent(command.getTransferOrderLineId()));
    }

	// ----------------------------------------------
	// association command handlers
	// ----------------------------------------------

    // single association commands
    @CommandHandler
    public void handle(AssignTransferOrderToTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignTransferOrderToTransferOrderLineCommand" );
    	
    	if (  transferOrder != null && transferOrder.getTransferOrderId() == command.getAssignment().getTransferOrderId() )
    		throw new ProcessingException( "TransferOrder already assigned with id " + command.getAssignment().getTransferOrderId() );  
    		
        apply(new AssignTransferOrderToTransferOrderLineEvent(command.getTransferOrderLineId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignTransferOrderFromTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignTransferOrderFromTransferOrderLineCommand" );

    	if (  transferOrder == null )
    		throw new ProcessingException( "TransferOrder already has nothing assigned." );  

    	apply(new UnAssignTransferOrderFromTransferOrderLineEvent(command.getTransferOrderLineId()));
    }
    @CommandHandler
    public void handle(AssignSkuToTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignSkuToTransferOrderLineCommand" );
    	
    	if (  sku != null && sku.getStockKeepingUnitId() == command.getAssignment().getStockKeepingUnitId() )
    		throw new ProcessingException( "Sku already assigned with id " + command.getAssignment().getStockKeepingUnitId() );  
    		
        apply(new AssignSkuToTransferOrderLineEvent(command.getTransferOrderLineId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignSkuFromTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignSkuFromTransferOrderLineCommand" );

    	if (  sku == null )
    		throw new ProcessingException( "Sku already has nothing assigned." );  

    	apply(new UnAssignSkuFromTransferOrderLineEvent(command.getTransferOrderLineId()));
    }
    @CommandHandler
    public void handle(AssignLotToTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignLotToTransferOrderLineCommand" );
    	
    	if (  lot != null && lot.getLotId() == command.getAssignment().getLotId() )
    		throw new ProcessingException( "Lot already assigned with id " + command.getAssignment().getLotId() );  
    		
        apply(new AssignLotToTransferOrderLineEvent(command.getTransferOrderLineId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignLotFromTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignLotFromTransferOrderLineCommand" );

    	if (  lot == null )
    		throw new ProcessingException( "Lot already has nothing assigned." );  

    	apply(new UnAssignLotFromTransferOrderLineEvent(command.getTransferOrderLineId()));
    }
    @CommandHandler
    public void handle(AssignFromLocationToTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignFromLocationToTransferOrderLineCommand" );
    	
    	if (  fromLocation != null && fromLocation.getStorageLocationId() == command.getAssignment().getStorageLocationId() )
    		throw new ProcessingException( "FromLocation already assigned with id " + command.getAssignment().getStorageLocationId() );  
    		
        apply(new AssignFromLocationToTransferOrderLineEvent(command.getTransferOrderLineId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignFromLocationFromTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignFromLocationFromTransferOrderLineCommand" );

    	if (  fromLocation == null )
    		throw new ProcessingException( "FromLocation already has nothing assigned." );  

    	apply(new UnAssignFromLocationFromTransferOrderLineEvent(command.getTransferOrderLineId()));
    }
    @CommandHandler
    public void handle(AssignToLocationToTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignToLocationToTransferOrderLineCommand" );
    	
    	if (  toLocation != null && toLocation.getStorageLocationId() == command.getAssignment().getStorageLocationId() )
    		throw new ProcessingException( "ToLocation already assigned with id " + command.getAssignment().getStorageLocationId() );  
    		
        apply(new AssignToLocationToTransferOrderLineEvent(command.getTransferOrderLineId(), command.getAssignment()));
    }

    @CommandHandler
    public void handle(UnAssignToLocationFromTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handlign command UnAssignToLocationFromTransferOrderLineCommand" );

    	if (  toLocation == null )
    		throw new ProcessingException( "ToLocation already has nothing assigned." );  

    	apply(new UnAssignToLocationFromTransferOrderLineEvent(command.getTransferOrderLineId()));
    }

    // multiple association commands
    @CommandHandler
    public void handle(AssignSerialNumbersToTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handling command AssignSerialNumbersToTransferOrderLineCommand" );
    	
    	if ( serialNumbers.contains( command.getAddTo() ) )
    		throw new ProcessingException( "SerialNumbers already contains an entity with id " + command.getAddTo().getSerialNumberId() );

    	apply(new AssignSerialNumbersToTransferOrderLineEvent(command.getTransferOrderLineId(), command.getAddTo()));
    }

    @CommandHandler
    public void handle(RemoveSerialNumbersFromTransferOrderLineCommand command) throws Exception {
    	LOGGER.info( "Handling command RemoveSerialNumbersFromTransferOrderLineCommand" );
    	
    	if ( !serialNumbers.contains( command.getRemoveFrom() ) )
    		throw new ProcessingException( "SerialNumbers does not contain an entity with id " + command.getRemoveFrom().getSerialNumberId() );

        apply(new RemoveSerialNumbersFromTransferOrderLineEvent(command.getTransferOrderLineId(), command.getRemoveFrom()));
    }

	// ----------------------------------------------
	// intrinsic event source handlers
	// ----------------------------------------------
    @EventSourcingHandler
    void on(CreateTransferOrderLineEvent event) {	
    	LOGGER.info( "Event sourcing CreateTransferOrderLineEvent" );
    	this.transferOrderLineId = event.getTransferOrderLineId();
        this.lineNumber = event.getLineNumber();
        this.quantity = event.getQuantity();
        this.unitOfMeasure = event.getUnitOfMeasure();
        this.stockStatus = event.getStockStatus();
    }
    
    @EventSourcingHandler
    void on(UpdateTransferOrderLineEvent event) {
    	LOGGER.info( "Event sourcing classObject.getUpdateEventAlias()}" );
        this.lineNumber = event.getLineNumber();
        this.quantity = event.getQuantity();
        this.transferOrder = event.getTransferOrder();
        this.sku = event.getSku();
        this.lot = event.getLot();
        this.serialNumbers = event.getSerialNumbers();
        this.fromLocation = event.getFromLocation();
        this.toLocation = event.getToLocation();
        this.unitOfMeasure = event.getUnitOfMeasure();
        this.stockStatus = event.getStockStatus();
    }   

	// ----------------------------------------------
	// association event source handlers
	// ----------------------------------------------
	// single associations
    @EventSourcingHandler
    void on(AssignTransferOrderToTransferOrderLineEvent event ) {	
    	LOGGER.info( "Event sourcing AssignTransferOrderToTransferOrderLineEvent" );
    	this.transferOrder = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignTransferOrderFromTransferOrderLineEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignTransferOrderFromTransferOrderLineEvent" );
		this.transferOrder = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignSkuToTransferOrderLineEvent event ) {	
    	LOGGER.info( "Event sourcing AssignSkuToTransferOrderLineEvent" );
    	this.sku = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignSkuFromTransferOrderLineEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignSkuFromTransferOrderLineEvent" );
		this.sku = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignLotToTransferOrderLineEvent event ) {	
    	LOGGER.info( "Event sourcing AssignLotToTransferOrderLineEvent" );
    	this.lot = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignLotFromTransferOrderLineEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignLotFromTransferOrderLineEvent" );
		this.lot = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignFromLocationToTransferOrderLineEvent event ) {	
    	LOGGER.info( "Event sourcing AssignFromLocationToTransferOrderLineEvent" );
    	this.fromLocation = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignFromLocationFromTransferOrderLineEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignFromLocationFromTransferOrderLineEvent" );
		this.fromLocation = null;
	}
	// single associations
    @EventSourcingHandler
    void on(AssignToLocationToTransferOrderLineEvent event ) {	
    	LOGGER.info( "Event sourcing AssignToLocationToTransferOrderLineEvent" );
    	this.toLocation = event.getAssignment();
    }

	@EventSourcingHandler
	void on(UnAssignToLocationFromTransferOrderLineEvent event ) {	
		LOGGER.info( "Event sourcing UnAssignToLocationFromTransferOrderLineEvent" );
		this.toLocation = null;
	}

	// multiple associations
    @EventSourcingHandler
    void on(AssignSerialNumbersToTransferOrderLineEvent event ) {
    	LOGGER.info( "Event sourcing AssignSerialNumbersToTransferOrderLineEvent" );
    	this.serialNumbers.add( event.getAddTo() );
    }

	@EventSourcingHandler
	void on(RemoveSerialNumbersFromTransferOrderLineEvent event ) {	
		LOGGER.info( "Event sourcing RemoveSerialNumbersFromTransferOrderLineEvent" );
		this.serialNumbers.remove( event.getRemoveFrom() );
	}
	

    // ------------------------------------------
    // attributes
    // ------------------------------------------
	
    @AggregateIdentifier
    private UUID transferOrderLineId;
    
    private int lineNumber;
    private java.math.BigDecimal quantity;
    private UnitOfMeasure unitOfMeasure;
    private StockStatus stockStatus;
    private TransferOrder transferOrder = null;
    private StockKeepingUnit sku = null;
    private Lot lot = null;
    private Set<SerialNumber> serialNumbers = new HashSet<>();
    private StorageLocation fromLocation = null;
    private StorageLocation toLocation = null;

    private static final Logger LOGGER 	= Logger.getLogger(TransferOrderLineAggregate.class.getName());
}
