/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * HCIDL Governance Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;

/**
 * Test ControlTest_ class.
 *
 * @author Harbormaster Dev Team
 */
public class ControlTest_Test{

        // ------------------------------------
		// default constructor
	    // ------------------------------------
		public ControlTest_Test() {
			LOGGER.setUseParentHandlers(false);	// only want to output to the provided LogHandler
		}

		// test methods
		@Test
		/**
		 * Full Create-Read-Update-Delete of a ControlTest_, through a
		 * ControlTest_Test.
		 */
		public void testCRUD() throws Throwable {
			try {
				LOGGER.info("**********************************************************");
				LOGGER.info("Beginning full CRUD test on ControlTest_...");

				testCreate();
//				testRead();
//				testUpdate();
				testGetAll();
//				testDelete();

				LOGGER.info("Successfully ran a full test on ControlTest_Test...");
				LOGGER.info("**********************************************************");
				LOGGER.info("");
			} catch (Throwable e) {
				throw e;
			} finally {
				if (handler != null) {
					handler.flush();
					LOGGER.removeHandler(handler);
				}
			}
		}

		/** 
		 * Tests creating a new ControlTest_.
		 */
		public void testCreate() throws Throwable {
			LOGGER.info( "\n======== CREATE ======== ");
			LOGGER.info( "-- Attempting to create a ControlTest_");

			StringBuilder msg = new StringBuilder( "-- Failed to create a ControlTest_" );

			try {            
				ControlTest_ entity = ControlTest_Service.getControlTest_Instance().createControlTest_( generateNewEntity() );
				thePrimaryKey = entity.getControlTest_Id();
				LOGGER.info( "-- Successfully created a ControlTest_ with primary key" + thePrimaryKey );
			}
			catch (Exception e) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests reading a ControlTest_. 
		 */
		public ControlTest_ testRead() throws Throwable {
			LOGGER.info( "\n======== READ ======== ");
			LOGGER.info( "-- Reading a previously created ControlTest_" );

			ControlTest_ entity = null;
			StringBuilder msg = new StringBuilder( "-- Failed to read ControlTest_ with primary key" );
			msg.append( thePrimaryKey );
			
			ControlTest_FetchOneSummary fetchOneSummary = new ControlTest_FetchOneSummary( thePrimaryKey );

			try {
				entity = ControlTest_Service.getControlTest_Instance().getControlTest_( fetchOneSummary );

				assertNotNull( entity,msg.toString() );

				LOGGER.info( "-- Successfully found ControlTest_ " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
			
			return entity;
		}

		/** 
		 * Tests updating a ControlTest_.
		 */
		public void testUpdate() throws Throwable {
			LOGGER.info( "\n======== UPDATE ======== ");
			LOGGER.info( "-- Attempting to update a ControlTest_." );

			StringBuilder msg = new StringBuilder( "Failed to update a ControlTest_ : " );        
			ControlTest_ entity = null;

			try {            
				entity = testRead();

				assertNotNull( entity, msg.toString() );

				LOGGER.info( "-- Now updating the created ControlTest_." );

				// for use later on...
				thePrimaryKey = entity.getControlTest_Id();

				ControlTest_Service proxy = ControlTest_Service.getControlTest_Instance();            
				proxy.updateControlTest_( entity );   

				LOGGER.info( "-- Successfully saved ControlTest_ - " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : primarykey = " + thePrimaryKey + " : entity-" +  entity + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests deleting a ControlTest_.
		 */
		public void testDelete() throws Throwable {
			LOGGER.info( "\n======== DELETE ======== ");
			LOGGER.info( "-- Deleting a previously created ControlTest_." );

			try{
			    ControlTest_ entity = testRead(); 
				ControlTest_Service.getControlTest_Instance().delete( entity );

				LOGGER.info( "-- Successfully deleted ControlTest_ with primary key " + thePrimaryKey );            
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( "-- Failed to delete ControlTest_ with primary key " + thePrimaryKey );

				throw e;
			}
		}

		/**
		 * Tests getting all ControlTest_s.
		 */
		public void testGetAll() throws Throwable {    
			LOGGER.info( "======== GETALL ======== ");
			LOGGER.info( "-- Retrieving Collection of ControlTest_s:" );

			StringBuilder msg = new StringBuilder( "-- Failed to get all ControlTest_ : " );        
			List<ControlTest_> collection  = null;

			try {
				// call the static get method on the ControlTest_Service
				collection = ControlTest_Service.getControlTest_Instance().getAllControlTest_();

				if ( collection == null || collection.size() == 0 ) {
					LOGGER.warning( unexpectedErrorMsg );
					LOGGER.warning( msg.toString() + " Empty collection returned."  );
				}
				else {
					// Now print out the values
					ControlTest_ entity = null;            
					Iterator<ControlTest_> iter = collection.iterator();
					int index = 1;

					while( iter.hasNext() ) {
						// Retrieve the entity   
						entity = iter.next();

						assertNotNull( entity,"-- null entity in Collection." );
						assertNotNull( entity.getControlTest_Id(), "-- entity in Collection has a null primary key" );        

						LOGGER.info( " - " + String.valueOf(index) + ". " + entity.toString() );
						index++;
					}
				}
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/**
		 * Assigns a common log handler for each test class in the suite
		 * @param		handler	Handler
		 * @return		ControlTest_Test
		 */
		public ControlTest_Test setHandler(Handler handler) {
			this.handler = handler;
			LOGGER.addHandler(handler); // assign so the LOGGER can only output results to the Handler
			return this;
		}

		/**
		 * Returns a new populated ControlTest_
		 * 
		 * @return ControlTest_
		 */
		protected ControlTest_ generateNewEntity() {
			ControlTest_ entity = new ControlTest_( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),   new Date(),   new Date(),  0,  null,  new HashSet<>(),  null,  TestType.values()[0],  ControlEffectiveness.values()[0],  TestStatus.values()[0] );
			
			return( entity );
		}

		//-----------------------------------------------------
		// attributes 
		//-----------------------------------------------------
		protected UUID thePrimaryKey 						= null;
		private final Logger LOGGER 						= Logger.getLogger(ControlTest_Test.class.getName());
		private Handler handler 							= null;
		private String unexpectedErrorMsg 					= ":::::::::::::: Unexpected Error :::::::::::::::::";
	}
