/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * HCIDL Inventory Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;

/**
 * Test OutboundAllocation class.
 *
 * @author Harbormaster Dev Team
 */
public class OutboundAllocationTest{

        // ------------------------------------
		// default constructor
	    // ------------------------------------
		public OutboundAllocationTest() {
			LOGGER.setUseParentHandlers(false);	// only want to output to the provided LogHandler
		}

		// test methods
		@Test
		/**
		 * Full Create-Read-Update-Delete of a OutboundAllocation, through a
		 * OutboundAllocationTest.
		 */
		public void testCRUD() throws Throwable {
			try {
				LOGGER.info("**********************************************************");
				LOGGER.info("Beginning full CRUD test on OutboundAllocation...");

				testCreate();
//				testRead();
//				testUpdate();
				testGetAll();
//				testDelete();

				LOGGER.info("Successfully ran a full test on OutboundAllocationTest...");
				LOGGER.info("**********************************************************");
				LOGGER.info("");
			} catch (Throwable e) {
				throw e;
			} finally {
				if (handler != null) {
					handler.flush();
					LOGGER.removeHandler(handler);
				}
			}
		}

		/** 
		 * Tests creating a new OutboundAllocation.
		 */
		public void testCreate() throws Throwable {
			LOGGER.info( "\n======== CREATE ======== ");
			LOGGER.info( "-- Attempting to create a OutboundAllocation");

			StringBuilder msg = new StringBuilder( "-- Failed to create a OutboundAllocation" );

			try {            
				OutboundAllocation entity = OutboundAllocationService.getOutboundAllocationInstance().createOutboundAllocation( generateNewEntity() );
				thePrimaryKey = entity.getOutboundAllocationId();
				LOGGER.info( "-- Successfully created a OutboundAllocation with primary key" + thePrimaryKey );
			}
			catch (Exception e) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests reading a OutboundAllocation. 
		 */
		public OutboundAllocation testRead() throws Throwable {
			LOGGER.info( "\n======== READ ======== ");
			LOGGER.info( "-- Reading a previously created OutboundAllocation" );

			OutboundAllocation entity = null;
			StringBuilder msg = new StringBuilder( "-- Failed to read OutboundAllocation with primary key" );
			msg.append( thePrimaryKey );
			
			OutboundAllocationFetchOneSummary fetchOneSummary = new OutboundAllocationFetchOneSummary( thePrimaryKey );

			try {
				entity = OutboundAllocationService.getOutboundAllocationInstance().getOutboundAllocation( fetchOneSummary );

				assertNotNull( entity,msg.toString() );

				LOGGER.info( "-- Successfully found OutboundAllocation " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
			
			return entity;
		}

		/** 
		 * Tests updating a OutboundAllocation.
		 */
		public void testUpdate() throws Throwable {
			LOGGER.info( "\n======== UPDATE ======== ");
			LOGGER.info( "-- Attempting to update a OutboundAllocation." );

			StringBuilder msg = new StringBuilder( "Failed to update a OutboundAllocation : " );        
			OutboundAllocation entity = null;

			try {            
				entity = testRead();

				assertNotNull( entity, msg.toString() );

				LOGGER.info( "-- Now updating the created OutboundAllocation." );

				// for use later on...
				thePrimaryKey = entity.getOutboundAllocationId();

				OutboundAllocationService proxy = OutboundAllocationService.getOutboundAllocationInstance();            
				proxy.updateOutboundAllocation( entity );   

				LOGGER.info( "-- Successfully saved OutboundAllocation - " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : primarykey = " + thePrimaryKey + " : entity-" +  entity + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests deleting a OutboundAllocation.
		 */
		public void testDelete() throws Throwable {
			LOGGER.info( "\n======== DELETE ======== ");
			LOGGER.info( "-- Deleting a previously created OutboundAllocation." );

			try{
			    OutboundAllocation entity = testRead(); 
				OutboundAllocationService.getOutboundAllocationInstance().delete( entity );

				LOGGER.info( "-- Successfully deleted OutboundAllocation with primary key " + thePrimaryKey );            
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( "-- Failed to delete OutboundAllocation with primary key " + thePrimaryKey );

				throw e;
			}
		}

		/**
		 * Tests getting all OutboundAllocations.
		 */
		public void testGetAll() throws Throwable {    
			LOGGER.info( "======== GETALL ======== ");
			LOGGER.info( "-- Retrieving Collection of OutboundAllocations:" );

			StringBuilder msg = new StringBuilder( "-- Failed to get all OutboundAllocation : " );        
			List<OutboundAllocation> collection  = null;

			try {
				// call the static get method on the OutboundAllocationService
				collection = OutboundAllocationService.getOutboundAllocationInstance().getAllOutboundAllocation();

				if ( collection == null || collection.size() == 0 ) {
					LOGGER.warning( unexpectedErrorMsg );
					LOGGER.warning( msg.toString() + " Empty collection returned."  );
				}
				else {
					// Now print out the values
					OutboundAllocation entity = null;            
					Iterator<OutboundAllocation> iter = collection.iterator();
					int index = 1;

					while( iter.hasNext() ) {
						// Retrieve the entity   
						entity = iter.next();

						assertNotNull( entity,"-- null entity in Collection." );
						assertNotNull( entity.getOutboundAllocationId(), "-- entity in Collection has a null primary key" );        

						LOGGER.info( " - " + String.valueOf(index) + ". " + entity.toString() );
						index++;
					}
				}
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/**
		 * Assigns a common log handler for each test class in the suite
		 * @param		handler	Handler
		 * @return		OutboundAllocationTest
		 */
		public OutboundAllocationTest setHandler(Handler handler) {
			this.handler = handler;
			LOGGER.addHandler(handler); // assign so the LOGGER can only output results to the Handler
			return this;
		}

		/**
		 * Returns a new populated OutboundAllocation
		 * 
		 * @return OutboundAllocation
		 */
		protected OutboundAllocation generateNewEntity() {
			OutboundAllocation entity = new OutboundAllocation( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  java.math.BigDecimal.ZERO,   new Date(),  null,  null,  null,  null,  null,  new HashSet<>(),  null,  AllocationStatus.values()[0] );
			
			return( entity );
		}

		//-----------------------------------------------------
		// attributes 
		//-----------------------------------------------------
		protected UUID thePrimaryKey 						= null;
		private final Logger LOGGER 						= Logger.getLogger(OutboundAllocationTest.class.getName());
		private Handler handler 							= null;
		private String unexpectedErrorMsg 					= ":::::::::::::: Unexpected Error :::::::::::::::::";
	}
