#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.crmOnDjango
requirements.txt=.crmOnDjango
admin.py=.crmOnDjango
apps.py=.crmOnDjango
appUrls.py=.crmOnDjango
setup.py=.crmOnDjango
README.rst=.crmOnDjango
LICENSE=.crmOnDjango
Dockerfile=.crmOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.crmOnDjango.mainsite
wsgi.py=.crmOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.crmOnDjango.models
__classes__Delegate.py=.crmOnDjango.delegates
__classes__Test.py=.crmOnDjango.tests
__classes__View.py=.crmOnDjango.views
__classes__Urls.py=.crmOnDjango.urls
__enums__.py=.crmOnDjango.models
Exceptions.py=.crmOnDjango.exceptions
empty.doc=.crmOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.crmOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.crmOnDjango.mainsite,.crmOnDjango.models,.crmOnDjango.delegates,.crmOnDjango.tests,.crmOnDjango.views,.crmOnDjango.urls,.crmOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json