#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.healthcareOnDjango
requirements.txt=.healthcareOnDjango
admin.py=.healthcareOnDjango
apps.py=.healthcareOnDjango
appUrls.py=.healthcareOnDjango
setup.py=.healthcareOnDjango
README.rst=.healthcareOnDjango
LICENSE=.healthcareOnDjango
Dockerfile=.healthcareOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.healthcareOnDjango.mainsite
wsgi.py=.healthcareOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.healthcareOnDjango.models
__classes__Delegate.py=.healthcareOnDjango.delegates
__classes__Test.py=.healthcareOnDjango.tests
__classes__View.py=.healthcareOnDjango.views
__classes__Urls.py=.healthcareOnDjango.urls
__enums__.py=.healthcareOnDjango.models
Exceptions.py=.healthcareOnDjango.exceptions
empty.doc=.healthcareOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.healthcareOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.healthcareOnDjango.mainsite,.healthcareOnDjango.models,.healthcareOnDjango.delegates,.healthcareOnDjango.tests,.healthcareOnDjango.views,.healthcareOnDjango.urls,.healthcareOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json