/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Analytics Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;

import org.axonframework.config.ProcessingGroup;
import org.axonframework.eventhandling.EventHandler;
import org.axonframework.queryhandling.QueryHandler;
import org.axonframework.queryhandling.QueryUpdateEmitter;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>EvaluationMetricProjector</h2>
 * <p>
 * The EvaluationMetric Projector is responsible for maintaining the read model for
 * EvaluationMetric entities. It subscribes to domain events published by the EvaluationMetric
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul><li>QueryGateway</li></ul>
 *
 * <h3>Queries Handled</h3>
 *		<ul>
 *      <li>FindEvaluationMetricQuery</li>
 *      <li>FindAllEvaluationMetricQuery</li>
 *		</ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
//@ProcessingGroup("evaluationMetric")
@Component("evaluationMetric-projector")
public class EvaluationMetricProjector extends EvaluationMetricEntityProjector {
		
	// core constructor
	public EvaluationMetricProjector(ProjectorRegistry registry,
									EvaluationMetricRepository repository,
									QueryUpdateEmitter queryUpdateEmitter ) {
        super(registry, repository);
        this.queryUpdateEmitter = queryUpdateEmitter;
    }	

	/*
     * @param	event CreateEvaluationMetricEvent
     */
    @EventHandler( payloadType=CreateEvaluationMetricEvent.class )
    public void handle( CreateEvaluationMetricEvent event) {
	    LOGGER.info("handling CreateEvaluationMetricEvent - " + event );
	    EvaluationMetric entity = new EvaluationMetric();
            entity.setEvaluationMetricId( event.getEvaluationMetricId() );
            entity.setName( event.getName() );
            entity.setValue( event.getValue() );
	    
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    create(entity);
        
        // ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllEvaluationMetric( entity );
    }

    /*
     * @param	event UpdateEvaluationMetricEvent
     */
    @EventHandler( payloadType=UpdateEvaluationMetricEvent.class )
    public void handle( UpdateEvaluationMetricEvent event) {
    	LOGGER.info("handling UpdateEvaluationMetricEvent - " + event );
    	
	    EvaluationMetric entity = new EvaluationMetric();
            entity.setEvaluationMetricId( event.getEvaluationMetricId() );
            entity.setName( event.getName() );
            entity.setValue( event.getValue() );
            entity.setModelVersion( event.getModelVersion() );
            entity.setMetric( event.getMetric() );
            entity.setDataset( event.getDataset() );
 
    	// ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		update(entity);

    	// ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindEvaluationMetric( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllEvaluationMetric( entity );        
    }
    
    /*
     * @param	event DeleteEvaluationMetricEvent
     */
    @EventHandler( payloadType=DeleteEvaluationMetricEvent.class )
    public void handle( DeleteEvaluationMetricEvent event) {
    	LOGGER.info("handling DeleteEvaluationMetricEvent - " + event );
    	
    	// ------------------------------------------
    	// delete delegation
    	// ------------------------------------------
    	EvaluationMetric entity = delete( event.getEvaluationMetricId() );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllEvaluationMetric( entity );

    }    

    /*
     * @param	event AssignModelVersionToEvaluationMetricEvent
     */
    @EventHandler( payloadType=AssignModelVersionToEvaluationMetricEvent.class)
    public void handle( AssignModelVersionToEvaluationMetricEvent event) {
	    LOGGER.info("handling AssignModelVersionToEvaluationMetricEvent - " + event );

	    // ------------------------------------------
	    // delegate to assignTo
	    // ------------------------------------------
	    EvaluationMetric entity = assignModelVersion( event.getEvaluationMetricId(), event.getAssignment() );

	    // ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindEvaluationMetric( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllEvaluationMetric( entity );
    }
    

	/*
	 * @param	event UnAssignModelVersionFromEvaluationMetricEvent
	 */
	@EventHandler( payloadType=UnAssignModelVersionFromEvaluationMetricEvent.class)
	public void handle( UnAssignModelVersionFromEvaluationMetricEvent event) {
	    LOGGER.info("handling UnAssignModelVersionFromEvaluationMetricEvent - " + event );

	    // ------------------------------------------
	    // delegate to unAssignFrom
	    // ------------------------------------------
	    EvaluationMetric entity = unAssignModelVersion( event.getEvaluationMetricId() );

		// ------------------------------------------
		// emit to subscribers that find one
		// ------------------------------------------    	
	    emitFindEvaluationMetric( entity );
	
		// ------------------------------------------
		// emit to subscribers that find all
		// ------------------------------------------    	
	    emitFindAllEvaluationMetric( entity );
	}

    /*
     * @param	event AssignMetricToEvaluationMetricEvent
     */
    @EventHandler( payloadType=AssignMetricToEvaluationMetricEvent.class)
    public void handle( AssignMetricToEvaluationMetricEvent event) {
	    LOGGER.info("handling AssignMetricToEvaluationMetricEvent - " + event );

	    // ------------------------------------------
	    // delegate to assignTo
	    // ------------------------------------------
	    EvaluationMetric entity = assignMetric( event.getEvaluationMetricId(), event.getAssignment() );

	    // ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindEvaluationMetric( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllEvaluationMetric( entity );
    }
    

	/*
	 * @param	event UnAssignMetricFromEvaluationMetricEvent
	 */
	@EventHandler( payloadType=UnAssignMetricFromEvaluationMetricEvent.class)
	public void handle( UnAssignMetricFromEvaluationMetricEvent event) {
	    LOGGER.info("handling UnAssignMetricFromEvaluationMetricEvent - " + event );

	    // ------------------------------------------
	    // delegate to unAssignFrom
	    // ------------------------------------------
	    EvaluationMetric entity = unAssignMetric( event.getEvaluationMetricId() );

		// ------------------------------------------
		// emit to subscribers that find one
		// ------------------------------------------    	
	    emitFindEvaluationMetric( entity );
	
		// ------------------------------------------
		// emit to subscribers that find all
		// ------------------------------------------    	
	    emitFindAllEvaluationMetric( entity );
	}

    /*
     * @param	event AssignDatasetToEvaluationMetricEvent
     */
    @EventHandler( payloadType=AssignDatasetToEvaluationMetricEvent.class)
    public void handle( AssignDatasetToEvaluationMetricEvent event) {
	    LOGGER.info("handling AssignDatasetToEvaluationMetricEvent - " + event );

	    // ------------------------------------------
	    // delegate to assignTo
	    // ------------------------------------------
	    EvaluationMetric entity = assignDataset( event.getEvaluationMetricId(), event.getAssignment() );

	    // ------------------------------------------
    	// emit to subscribers that find one
    	// ------------------------------------------    	
        emitFindEvaluationMetric( entity );

    	// ------------------------------------------
    	// emit to subscribers that find all
    	// ------------------------------------------    	
        emitFindAllEvaluationMetric( entity );
    }
    

	/*
	 * @param	event UnAssignDatasetFromEvaluationMetricEvent
	 */
	@EventHandler( payloadType=UnAssignDatasetFromEvaluationMetricEvent.class)
	public void handle( UnAssignDatasetFromEvaluationMetricEvent event) {
	    LOGGER.info("handling UnAssignDatasetFromEvaluationMetricEvent - " + event );

	    // ------------------------------------------
	    // delegate to unAssignFrom
	    // ------------------------------------------
	    EvaluationMetric entity = unAssignDataset( event.getEvaluationMetricId() );

		// ------------------------------------------
		// emit to subscribers that find one
		// ------------------------------------------    	
	    emitFindEvaluationMetric( entity );
	
		// ------------------------------------------
		// emit to subscribers that find all
		// ------------------------------------------    	
	    emitFindAllEvaluationMetric( entity );
	}




    /**
     * Method to retrieve the EvaluationMetric via an EvaluationMetricPrimaryKey.
     * @param 	id Long
     * @return 	EvaluationMetric
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    @SuppressWarnings("unused")
    @QueryHandler
    public EvaluationMetric handle( FindEvaluationMetricQuery query ) 
    throws ProcessingException, IllegalArgumentException {
    	return find( query.getFilter().getEvaluationMetricId() );
    }
    
    /**
     * Method to retrieve a collection of all EvaluationMetrics
     *
     * @param	query	FindAllEvaluationMetricQuery 
     * @return 	List<EvaluationMetric> 
     * @exception ProcessingException Thrown if any problems
     */
    @SuppressWarnings("unused")
    @QueryHandler
    public List<EvaluationMetric> handle( FindAllEvaluationMetricQuery query ) throws ProcessingException {
    	return findAll( query );
    }



/**
 * emit to subscription queries of type FindEvaluationMetric,
 * but only if the id matches
 *
 * @param		entity	EvaluationMetric
 */
	protected void emitFindEvaluationMetric( EvaluationMetric entity ) {
		LOGGER.info("handling emitFindEvaluationMetric" );
		
	    queryUpdateEmitter.emit(FindEvaluationMetricQuery.class,
	                            query -> query.getFilter().getEvaluationMetricId().equals(entity.getEvaluationMetricId()),
	                            entity);
	}
	
	/**
	 * unconditionally emit to subscription queries of type FindAllEvaluationMetric
	 * 
	 * @param		entity	EvaluationMetric
	 */
	protected void emitFindAllEvaluationMetric( EvaluationMetric entity ) {
		LOGGER.info("handling emitFindAllEvaluationMetric" );
		
	    queryUpdateEmitter.emit(FindAllEvaluationMetricQuery.class,
	                            query -> true,
	                            entity);
	}

	//--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
	private final QueryUpdateEmitter queryUpdateEmitter;
    private static final Logger LOGGER 	= Logger.getLogger(EvaluationMetricProjector.class.getName());

}
