#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------

#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
#()
#------------------------------------------------------------------------------
# app level inclusions
#------------------------------------------------------------------------------
main.go=.advertising-on-golang
Dockerfile=.
.env=.advertising-on-golang,.internal.test

#------------------------------------------------------------------------------
# api level inclusions
#------------------------------------------------------------------------------
utils.go=.advertising-on-golang.internal.utils
__classes__.go=.advertising-on-golang.internal.model
enums.go=.advertising-on-golang.internal.model
router.go=.advertising-on-golang.internal.router
__classes__DAO.go=.advertising-on-golang.internal.dao
__classes__Controller.go=.advertising-on-golang.internal.controller
PulseIndicatorController__.go=.advertising-on-golang.internal.controller
Tester_test.go=.advertising-on-golang.internal.test
json.go=.advertising-on-golang.internal.response
jsonResponseFormatter.go=.advertising-on-golang.internal.response

#------------------------------------------------------------------------------
# CI/CD Platforms
#------------------------------------------------------------------------------
#buddy.yml=

#------------------------------------------------------------------------------
# exclusions
#------------------------------------------------------------------------------ 
exclusions=mappings.properties,options.json,blueprint.json