/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Healthcare Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;

/**
 * Test InsurancePlan class.
 *
 * @author Harbormaster Dev Team
 */
public class InsurancePlanTest{

        // ------------------------------------
		// default constructor
	    // ------------------------------------
		public InsurancePlanTest() {
			LOGGER.setUseParentHandlers(false);	// only want to output to the provided LogHandler
		}

		// test methods
		@Test
		/**
		 * Full Create-Read-Update-Delete of a InsurancePlan, through a
		 * InsurancePlanTest.
		 */
		public void testCRUD() throws Throwable {
			try {
				LOGGER.info("**********************************************************");
				LOGGER.info("Beginning full CRUD test on InsurancePlan...");

				testCreate();
//				testRead();
//				testUpdate();
				testGetAll();
//				testDelete();

				LOGGER.info("Successfully ran a full test on InsurancePlanTest...");
				LOGGER.info("**********************************************************");
				LOGGER.info("");
			} catch (Throwable e) {
				throw e;
			} finally {
				if (handler != null) {
					handler.flush();
					LOGGER.removeHandler(handler);
				}
			}
		}

		/** 
		 * Tests creating a new InsurancePlan.
		 */
		public void testCreate() throws Throwable {
			LOGGER.info( "\n======== CREATE ======== ");
			LOGGER.info( "-- Attempting to create a InsurancePlan");

			StringBuilder msg = new StringBuilder( "-- Failed to create a InsurancePlan" );

			try {            
				InsurancePlan entity = InsurancePlanService.getInsurancePlanInstance().createInsurancePlan( generateNewEntity() );
				thePrimaryKey = entity.getInsurancePlanId();
				LOGGER.info( "-- Successfully created a InsurancePlan with primary key" + thePrimaryKey );
			}
			catch (Exception e) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests reading a InsurancePlan. 
		 */
		public InsurancePlan testRead() throws Throwable {
			LOGGER.info( "\n======== READ ======== ");
			LOGGER.info( "-- Reading a previously created InsurancePlan" );

			InsurancePlan entity = null;
			StringBuilder msg = new StringBuilder( "-- Failed to read InsurancePlan with primary key" );
			msg.append( thePrimaryKey );
			
			InsurancePlanFetchOneSummary fetchOneSummary = new InsurancePlanFetchOneSummary( thePrimaryKey );

			try {
				entity = InsurancePlanService.getInsurancePlanInstance().getInsurancePlan( fetchOneSummary );

				assertNotNull( entity,msg.toString() );

				LOGGER.info( "-- Successfully found InsurancePlan " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
			
			return entity;
		}

		/** 
		 * Tests updating a InsurancePlan.
		 */
		public void testUpdate() throws Throwable {
			LOGGER.info( "\n======== UPDATE ======== ");
			LOGGER.info( "-- Attempting to update a InsurancePlan." );

			StringBuilder msg = new StringBuilder( "Failed to update a InsurancePlan : " );        
			InsurancePlan entity = null;

			try {            
				entity = testRead();

				assertNotNull( entity, msg.toString() );

				LOGGER.info( "-- Now updating the created InsurancePlan." );

				// for use later on...
				thePrimaryKey = entity.getInsurancePlanId();

				InsurancePlanService proxy = InsurancePlanService.getInsurancePlanInstance();            
				proxy.updateInsurancePlan( entity );   

				LOGGER.info( "-- Successfully saved InsurancePlan - " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : primarykey = " + thePrimaryKey + " : entity-" +  entity + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests deleting a InsurancePlan.
		 */
		public void testDelete() throws Throwable {
			LOGGER.info( "\n======== DELETE ======== ");
			LOGGER.info( "-- Deleting a previously created InsurancePlan." );

			try{
			    InsurancePlan entity = testRead(); 
				InsurancePlanService.getInsurancePlanInstance().delete( entity );

				LOGGER.info( "-- Successfully deleted InsurancePlan with primary key " + thePrimaryKey );            
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( "-- Failed to delete InsurancePlan with primary key " + thePrimaryKey );

				throw e;
			}
		}

		/**
		 * Tests getting all InsurancePlans.
		 */
		public void testGetAll() throws Throwable {    
			LOGGER.info( "======== GETALL ======== ");
			LOGGER.info( "-- Retrieving Collection of InsurancePlans:" );

			StringBuilder msg = new StringBuilder( "-- Failed to get all InsurancePlan : " );        
			List<InsurancePlan> collection  = null;

			try {
				// call the static get method on the InsurancePlanService
				collection = InsurancePlanService.getInsurancePlanInstance().getAllInsurancePlan();

				if ( collection == null || collection.size() == 0 ) {
					LOGGER.warning( unexpectedErrorMsg );
					LOGGER.warning( msg.toString() + " Empty collection returned."  );
				}
				else {
					// Now print out the values
					InsurancePlan entity = null;            
					Iterator<InsurancePlan> iter = collection.iterator();
					int index = 1;

					while( iter.hasNext() ) {
						// Retrieve the entity   
						entity = iter.next();

						assertNotNull( entity,"-- null entity in Collection." );
						assertNotNull( entity.getInsurancePlanId(), "-- entity in Collection has a null primary key" );        

						LOGGER.info( " - " + String.valueOf(index) + ". " + entity.toString() );
						index++;
					}
				}
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/**
		 * Assigns a common log handler for each test class in the suite
		 * @param		handler	Handler
		 * @return		InsurancePlanTest
		 */
		public InsurancePlanTest setHandler(Handler handler) {
			this.handler = handler;
			LOGGER.addHandler(handler); // assign so the LOGGER can only output results to the Handler
			return this;
		}

		/**
		 * Returns a new populated InsurancePlan
		 * 
		 * @return InsurancePlan
		 */
		protected InsurancePlan generateNewEntity() {
			InsurancePlan entity = new InsurancePlan( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  null,  new HashSet<>(),  InsurancePlanType.values()[0] );
			
			return( entity );
		}

		//-----------------------------------------------------
		// attributes 
		//-----------------------------------------------------
		protected UUID thePrimaryKey 						= null;
		private final Logger LOGGER 						= Logger.getLogger(InsurancePlanTest.class.getName());
		private Handler handler 							= null;
		private String unexpectedErrorMsg 					= ":::::::::::::: Unexpected Error :::::::::::::::::";
	}
