#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.manufacturingOnDjango
requirements.txt=.manufacturingOnDjango
admin.py=.manufacturingOnDjango
apps.py=.manufacturingOnDjango
appUrls.py=.manufacturingOnDjango
setup.py=.manufacturingOnDjango
README.rst=.manufacturingOnDjango
LICENSE=.manufacturingOnDjango
Dockerfile=.manufacturingOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.manufacturingOnDjango.mainsite
wsgi.py=.manufacturingOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.manufacturingOnDjango.models
__classes__Delegate.py=.manufacturingOnDjango.delegates
__classes__Test.py=.manufacturingOnDjango.tests
__classes__View.py=.manufacturingOnDjango.views
__classes__Urls.py=.manufacturingOnDjango.urls
__enums__.py=.manufacturingOnDjango.models
Exceptions.py=.manufacturingOnDjango.exceptions
empty.doc=.manufacturingOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.manufacturingOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.manufacturingOnDjango.mainsite,.manufacturingOnDjango.models,.manufacturingOnDjango.delegates,.manufacturingOnDjango.tests,.manufacturingOnDjango.views,.manufacturingOnDjango.urls,.manufacturingOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json