/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * CRM Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>CampaignMember business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of CampaignMember related services in the case of a CampaignMember business related service failing.</li>
 * <li>Exposes a simpler, uniform CampaignMember interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill CampaignMember business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/21/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>CRM Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core CRM capabilities across accounts, contacts, leads, opportunities, pricing, quotes, orders, service cases, activities, and campaigns.</td></tr>
 *          <tr><td>industry</td><td>CRM</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class CampaignMemberService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public CampaignMemberService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new CampaignMemberEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(CampaignMemberRepository.class) );
		this.validator		= applicationContext.getBean(CampaignMemberValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		CampaignMember
	 */
		public CampaignMember createCampaignMember( CreateCampaignMemberCommand command ) {

		CampaignMember entity = new CampaignMember();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setCampaignMemberId( command.getCampaignMemberId() );
            entity.setResponded( command.getResponded() );
            entity.setStatus( command.getStatus() );
            entity.setMemberType( command.getMemberType() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of CampaignMember {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateCampaignMemberCommand
	 * @return		CampaignMember
	 */
	public CampaignMember updateCampaignMember( UpdateCampaignMemberCommand command ) {

		CampaignMember entity = new CampaignMember();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setCampaignMemberId( command.getCampaignMemberId() );
            entity.setResponded( command.getResponded() );
            entity.setCampaign( command.getCampaign() );
            entity.setLead( command.getLead() );
            entity.setContact( command.getContact() );
            entity.setStatus( command.getStatus() );
            entity.setMemberType( command.getMemberType() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of CampaignMember {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteCampaignMemberCommand
	 */
	public void delete( DeleteCampaignMemberCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getCampaignMemberId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of CampaignMember {0} ", id );

	}

	/**
	 * Method to retrieve the CampaignMember via CampaignMemberFetchOneSummary
	 * @param 	summary CampaignMemberFetchOneSummary
	 * @return 	CampaignMemberFetchOneResponse
	 */
	public CampaignMember getCampaignMember( CampaignMemberFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "CampaignMemberFetchOneSummary arg cannot be null" );

		CampaignMember entity = null;
		UUID id = summary.getCampaignMemberId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a CampaignMember using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all CampaignMembers
	 *
	 * @return 	List<CampaignMember>
	 */
    public List<CampaignMember> getAllCampaignMember() {
		List<CampaignMember> list = projector.findAll( new FindAllCampaignMemberQuery() );
		return list;
	}

	/**
	 * assign Campaign on CampaignMember
	 * @param		command AssignCampaignToCampaignMemberCommand
	 */
	public void assignCampaign( AssignCampaignToCampaignMemberCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignCampaign(command.getCampaignMemberId(), command.getAssignment());

	}

	/**
	 * unAssign Campaign on CampaignMember
	 * @param		command UnAssignCampaignFromCampaignMemberCommand
	 */
	public void unAssignCampaign( UnAssignCampaignFromCampaignMemberCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignCampaign(command.getCampaignMemberId());
	}
	
	/**
	 * assign Lead on CampaignMember
	 * @param		command AssignLeadToCampaignMemberCommand
	 */
	public void assignLead( AssignLeadToCampaignMemberCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignLead(command.getCampaignMemberId(), command.getAssignment());

	}

	/**
	 * unAssign Lead on CampaignMember
	 * @param		command UnAssignLeadFromCampaignMemberCommand
	 */
	public void unAssignLead( UnAssignLeadFromCampaignMemberCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignLead(command.getCampaignMemberId());
	}
	
	/**
	 * assign Contact on CampaignMember
	 * @param		command AssignContactToCampaignMemberCommand
	 */
	public void assignContact( AssignContactToCampaignMemberCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignContact(command.getCampaignMemberId(), command.getAssignment());

	}

	/**
	 * unAssign Contact on CampaignMember
	 * @param		command UnAssignContactFromCampaignMemberCommand
	 */
	public void unAssignContact( UnAssignContactFromCampaignMemberCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignContact(command.getCampaignMemberId());
	}
	




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final CampaignMemberEntityProjector projector;
	private final CampaignMemberValidator validator;
	private CampaignMember campaignMember 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(CampaignMemberService.class);
}
