from django.urls import path
from crmOnDjango.views import AccountView

urlpatterns = [
    path('', AccountView.index, name='index'),
	path('create', AccountView.get, name='create'),
	path('get/<int:accountId>/', AccountView.get, name='get'),
	path('save', AccountView.save, name='save'),
	path('getAll', AccountView.getAll, name='getAll'),
	path('delete/<int:accountId>/', AccountView.delete, name='delete'),
	path('assignOrganization/<int:accountId>/<int:OrganizationId>/', AccountView.assignOrganization, name='assignOrganization'),
	path('unassignOrganization/<int:accountId>/', AccountView.unassignOrganization, name='unassignOrganization'),
	path('assignParentAccount/<int:accountId>/<int:ParentAccountId>/', AccountView.assignParentAccount, name='assignParentAccount'),
	path('unassignParentAccount/<int:accountId>/', AccountView.unassignParentAccount, name='unassignParentAccount'),
	path('assignOwner/<int:accountId>/<int:OwnerId>/', AccountView.assignOwner, name='assignOwner'),
	path('unassignOwner/<int:accountId>/', AccountView.unassignOwner, name='unassignOwner'),
	path('assignTerritory/<int:accountId>/<int:TerritoryId>/', AccountView.assignTerritory, name='assignTerritory'),
	path('unassignTerritory/<int:accountId>/', AccountView.unassignTerritory, name='unassignTerritory'),
	path('addChildAccounts/<int:accountId>/<ChildAccountsIds>/', AccountView.addChildAccounts, name='addChildAccounts'),
	path('removeChildAccounts/<int:accountId>/<ChildAccountsIds>/', AccountView.removeChildAccounts, name='removeChildAccounts'),
	path('addContacts/<int:accountId>/<ContactsIds>/', AccountView.addContacts, name='addContacts'),
	path('removeContacts/<int:accountId>/<ContactsIds>/', AccountView.removeContacts, name='removeContacts'),
	path('addOpportunities/<int:accountId>/<OpportunitiesIds>/', AccountView.addOpportunities, name='addOpportunities'),
	path('removeOpportunities/<int:accountId>/<OpportunitiesIds>/', AccountView.removeOpportunities, name='removeOpportunities'),
	path('addCases/<int:accountId>/<CasesIds>/', AccountView.addCases, name='addCases'),
	path('removeCases/<int:accountId>/<CasesIds>/', AccountView.removeCases, name='removeCases'),
	path('addActivities/<int:accountId>/<ActivitiesIds>/', AccountView.addActivities, name='addActivities'),
	path('removeActivities/<int:accountId>/<ActivitiesIds>/', AccountView.removeActivities, name='removeActivities'),
	path('addCampaigns/<int:accountId>/<CampaignsIds>/', AccountView.addCampaigns, name='addCampaigns'),
	path('removeCampaigns/<int:accountId>/<CampaignsIds>/', AccountView.removeCampaigns, name='removeCampaigns'),
	path('addQuotes/<int:accountId>/<QuotesIds>/', AccountView.addQuotes, name='addQuotes'),
	path('removeQuotes/<int:accountId>/<QuotesIds>/', AccountView.removeQuotes, name='removeQuotes'),
	path('addOrders/<int:accountId>/<OrdersIds>/', AccountView.addOrders, name='addOrders'),
	path('removeOrders/<int:accountId>/<OrdersIds>/', AccountView.removeOrders, name='removeOrders'),
	path('addContracts/<int:accountId>/<ContractsIds>/', AccountView.addContracts, name='addContracts'),
	path('removeContracts/<int:accountId>/<ContractsIds>/', AccountView.removeContracts, name='removeContracts'),
	path('addNotes/<int:accountId>/<NotesIds>/', AccountView.addNotes, name='addNotes'),
	path('removeNotes/<int:accountId>/<NotesIds>/', AccountView.removeNotes, name='removeNotes'),
	path('addEmailMessages/<int:accountId>/<EmailMessagesIds>/', AccountView.addEmailMessages, name='addEmailMessages'),
	path('removeEmailMessages/<int:accountId>/<EmailMessagesIds>/', AccountView.removeEmailMessages, name='removeEmailMessages'),
]
