/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Insurance Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.test;

import java.util.logging.*;

/**
 * Base class for application Test classes.
 *
 * @author    Harbormaster Dev Team
 */
public class BaseTest
{
	/**
	 * hidden
	 */
	protected BaseTest() {
	}
	
	public static void runTheTest( Handler logHandler ) 
    {
         try {
		    new InsurerTest().setHandler(logHandler).testCRUD();
		    new InsuranceProductTest().setHandler(logHandler).testCRUD();
		    new CoverageDefinitionTest().setHandler(logHandler).testCRUD();
		    new DistributorTest().setHandler(logHandler).testCRUD();
		    new AgentTest().setHandler(logHandler).testCRUD();
		    new CustomerTest().setHandler(logHandler).testCRUD();
		    new ApplicationTest().setHandler(logHandler).testCRUD();
		    new QuoteTest().setHandler(logHandler).testCRUD();
		    new UnderwritingDecisionTest().setHandler(logHandler).testCRUD();
		    new UnderwriterTest().setHandler(logHandler).testCRUD();
		    new PolicyTest().setHandler(logHandler).testCRUD();
		    new EndorsementTest().setHandler(logHandler).testCRUD();
		    new PolicyCoverageTest().setHandler(logHandler).testCRUD();
		    new InsuredObjectTest().setHandler(logHandler).testCRUD();
		    new BeneficiaryTest().setHandler(logHandler).testCRUD();
		    new BillingAccountTest().setHandler(logHandler).testCRUD();
		    new InvoiceTest().setHandler(logHandler).testCRUD();
		    new PaymentTest().setHandler(logHandler).testCRUD();
		    new ClaimTest().setHandler(logHandler).testCRUD();
		    new IncidentTest().setHandler(logHandler).testCRUD();
		    new ExposureTest().setHandler(logHandler).testCRUD();
		    new AdjusterTest().setHandler(logHandler).testCRUD();
		    new ClaimReserveTest().setHandler(logHandler).testCRUD();
		    new ClaimPaymentTest().setHandler(logHandler).testCRUD();
		    new ServiceProviderTest().setHandler(logHandler).testCRUD();
		    new ReinsuranceAgreementTest().setHandler(logHandler).testCRUD();
		    new SubrogationRecoveryTest().setHandler(logHandler).testCRUD();
		    new ThirdPartyTest().setHandler(logHandler).testCRUD();
		    new DocumentTest().setHandler(logHandler).testCRUD();
        } catch( Throwable exc ) {
        	exc.printStackTrace();
        }
    }
	
}
