/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Insurance Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.test;

import java.io.*;
import java.util.*;
import java.util.logging.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.api.*;

/**
 * Test ServiceProvider class.
 *
 * @author Harbormaster Dev Team
 */
public class ServiceProviderTest{

        // ------------------------------------
		// default constructor
	    // ------------------------------------
		public ServiceProviderTest() {
			LOGGER.setUseParentHandlers(false);	// only want to output to the provided LogHandler
		}

		// test methods
		@Test
		/**
		 * Full Create-Read-Update-Delete of a ServiceProvider, through a
		 * ServiceProviderTest.
		 */
		public void testCRUD() throws Throwable {
			try {
				LOGGER.info("**********************************************************");
				LOGGER.info("Beginning full CRUD test on ServiceProvider...");

				testCreate();
//				testRead();
//				testUpdate();
				testGetAll();
//				testDelete();

				LOGGER.info("Successfully ran a full test on ServiceProviderTest...");
				LOGGER.info("**********************************************************");
				LOGGER.info("");
			} catch (Throwable e) {
				throw e;
			} finally {
				if (handler != null) {
					handler.flush();
					LOGGER.removeHandler(handler);
				}
			}
		}

		/** 
		 * Tests creating a new ServiceProvider.
		 */
		public void testCreate() throws Throwable {
			LOGGER.info( "\n======== CREATE ======== ");
			LOGGER.info( "-- Attempting to create a ServiceProvider");

			StringBuilder msg = new StringBuilder( "-- Failed to create a ServiceProvider" );

			try {            
				ServiceProvider entity = ServiceProviderService.getServiceProviderInstance().createServiceProvider( generateNewEntity() );
				thePrimaryKey = entity.getServiceProviderId();
				LOGGER.info( "-- Successfully created a ServiceProvider with primary key" + thePrimaryKey );
			}
			catch (Exception e) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests reading a ServiceProvider. 
		 */
		public ServiceProvider testRead() throws Throwable {
			LOGGER.info( "\n======== READ ======== ");
			LOGGER.info( "-- Reading a previously created ServiceProvider" );

			ServiceProvider entity = null;
			StringBuilder msg = new StringBuilder( "-- Failed to read ServiceProvider with primary key" );
			msg.append( thePrimaryKey );
			
			ServiceProviderFetchOneSummary fetchOneSummary = new ServiceProviderFetchOneSummary( thePrimaryKey );

			try {
				entity = ServiceProviderService.getServiceProviderInstance().getServiceProvider( fetchOneSummary );

				assertNotNull( entity,msg.toString() );

				LOGGER.info( "-- Successfully found ServiceProvider " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
			
			return entity;
		}

		/** 
		 * Tests updating a ServiceProvider.
		 */
		public void testUpdate() throws Throwable {
			LOGGER.info( "\n======== UPDATE ======== ");
			LOGGER.info( "-- Attempting to update a ServiceProvider." );

			StringBuilder msg = new StringBuilder( "Failed to update a ServiceProvider : " );        
			ServiceProvider entity = null;

			try {            
				entity = testRead();

				assertNotNull( entity, msg.toString() );

				LOGGER.info( "-- Now updating the created ServiceProvider." );

				// for use later on...
				thePrimaryKey = entity.getServiceProviderId();

				ServiceProviderService proxy = ServiceProviderService.getServiceProviderInstance();            
				proxy.updateServiceProvider( entity );   

				LOGGER.info( "-- Successfully saved ServiceProvider - " + entity.toString() );
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : primarykey = " + thePrimaryKey + " : entity-" +  entity + " : " + e );

				throw e;
			}
		}

		/** 
		 * Tests deleting a ServiceProvider.
		 */
		public void testDelete() throws Throwable {
			LOGGER.info( "\n======== DELETE ======== ");
			LOGGER.info( "-- Deleting a previously created ServiceProvider." );

			try{
			    ServiceProvider entity = testRead(); 
				ServiceProviderService.getServiceProviderInstance().delete( entity );

				LOGGER.info( "-- Successfully deleted ServiceProvider with primary key " + thePrimaryKey );            
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( "-- Failed to delete ServiceProvider with primary key " + thePrimaryKey );

				throw e;
			}
		}

		/**
		 * Tests getting all ServiceProviders.
		 */
		public void testGetAll() throws Throwable {    
			LOGGER.info( "======== GETALL ======== ");
			LOGGER.info( "-- Retrieving Collection of ServiceProviders:" );

			StringBuilder msg = new StringBuilder( "-- Failed to get all ServiceProvider : " );        
			List<ServiceProvider> collection  = null;

			try {
				// call the static get method on the ServiceProviderService
				collection = ServiceProviderService.getServiceProviderInstance().getAllServiceProvider();

				if ( collection == null || collection.size() == 0 ) {
					LOGGER.warning( unexpectedErrorMsg );
					LOGGER.warning( msg.toString() + " Empty collection returned."  );
				}
				else {
					// Now print out the values
					ServiceProvider entity = null;            
					Iterator<ServiceProvider> iter = collection.iterator();
					int index = 1;

					while( iter.hasNext() ) {
						// Retrieve the entity   
						entity = iter.next();

						assertNotNull( entity,"-- null entity in Collection." );
						assertNotNull( entity.getServiceProviderId(), "-- entity in Collection has a null primary key" );        

						LOGGER.info( " - " + String.valueOf(index) + ". " + entity.toString() );
						index++;
					}
				}
			}
			catch ( Throwable e ) {
				LOGGER.warning( unexpectedErrorMsg );
				LOGGER.warning( msg.toString() + " : " + e );

				throw e;
			}
		}

		/**
		 * Assigns a common log handler for each test class in the suite
		 * @param		handler	Handler
		 * @return		ServiceProviderTest
		 */
		public ServiceProviderTest setHandler(Handler handler) {
			this.handler = handler;
			LOGGER.addHandler(handler); // assign so the LOGGER can only output results to the Handler
			return this;
		}

		/**
		 * Returns a new populated ServiceProvider
		 * 
		 * @return ServiceProvider
		 */
		protected ServiceProvider generateNewEntity() {
			ServiceProvider entity = new ServiceProvider( null,  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric(16),  new HashSet<>(),  ServiceProviderType.values()[0],  NetworkStatus.values()[0] );
			
			return( entity );
		}

		//-----------------------------------------------------
		// attributes 
		//-----------------------------------------------------
		protected UUID thePrimaryKey 						= null;
		private final Logger LOGGER 						= Logger.getLogger(ServiceProviderTest.class.getName());
		private Handler handler 							= null;
		private String unexpectedErrorMsg 					= ":::::::::::::: Unexpected Error :::::::::::::::::";
	}
