/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * HCIDL Inventory Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;

import org.axonframework.commandhandling.gateway.CommandGateway;
import org.axonframework.queryhandling.QueryGateway;
import org.axonframework.queryhandling.QueryUpdateEmitter;
import org.axonframework.messaging.responsetypes.ResponseTypes;
import org.springframework.stereotype.Service;
import org.springframework.beans.BeansException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.validator.*;

/**
 *
 * <h2>Warehouse business service</h2>
 *
 * <p>
 * This class implements the Service design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Warehouse related services in the case of a Warehouse business related service failing.</li>
 * <li>Exposes a simpler, uniform Warehouse interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Warehouse business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>HCIDL Inventory Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical capability model for managing inventory across warehouses, locations, items, and stock movements.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class WarehouseService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public WarehouseService()  {
	}

	@Override
	public void setApplicationContext(ApplicationContext ctx) throws BeansException {
		super.setApplicationContext(ctx);

		queryGateway 		= ctx.getBean(QueryGateway.class);
		commandGateway 		= ctx.getBean(CommandGateway.class);
		queryUpdateEmitter  = ctx.getBean(QueryUpdateEmitter.class);
		validator			= ctx.getBean(WarehouseValidator.class);
	}


   /**
	* Warehouse Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	WarehouseService
	*/
	public static WarehouseService getWarehouseInstance() {
		return( new WarehouseService() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		CompletableFuture<UUID>
    */
	public CompletableFuture<UUID> createWarehouse( CreateWarehouseCommand command )
    throws ProcessingException, IllegalArgumentException {

		CompletableFuture<UUID> completableFuture = null;
				
		try {
			// --------------------------------------
        	// assign identity now if none
        	// -------------------------------------- 
			if ( command.getWarehouseId() == null )
				command.setWarehouseId( UUID.randomUUID() );
				
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    

    		// ---------------------------------------
    		// issue the CreateWarehouseCommand - by convention the future return value for a create command
        	// that is handled by the constructor of an aggregate will return the UUID 
    		// ---------------------------------------
        	completableFuture = commandGateway.send( command );
        	
			LOGGER.log( Level.INFO, "return from Command Gateway for CreateWarehouseCommand of Warehouse is " + command );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create Warehouse - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return completableFuture;
    }

   /**
    * Update the provided command.
    * @param		command UpdateWarehouseCommand
    * @return		CompletableFuture<Void>
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    */
    public CompletableFuture<Void> updateWarehouse( UpdateWarehouseCommand command ) 
    throws ProcessingException, IllegalArgumentException {
    	CompletableFuture<Void> completableFuture = null;
    	
    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	validator.validate( command );    

        	// --------------------------------------
        	// issue the UpdateWarehouseCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save Warehouse - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        
    	return completableFuture;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteWarehouseCommand
    * @return		CompletableFuture<Void>
    * @exception 	ProcessingException
    */
    public CompletableFuture<Void> delete( DeleteWarehouseCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
    	
    	CompletableFuture<Void> completableFuture = null;
    	
        try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	validator.validate( command );    
        	
        	// --------------------------------------
        	// issue the DeleteWarehouseCommand and return right away
        	// --------------------------------------    	
        	completableFuture = commandGateway.send( command );
        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete Warehouse using Id = "  + command.getWarehouseId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
        
        return completableFuture;
    }

    /**
     * Method to retrieve the Warehouse via WarehouseFetchOneSummary
     * @param 	summary WarehouseFetchOneSummary 
     * @return 	WarehouseFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public Warehouse getWarehouse( WarehouseFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "WarehouseFetchOneSummary arg cannot be null" );
    	
    	Warehouse entity = null;
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	validator.validate( summary );    
        	
        	// --------------------------------------
        	// use queryGateway to send request to Find a Warehouse
        	// --------------------------------------
        	CompletableFuture<Warehouse> futureEntity = queryGateway.query(new FindWarehouseQuery( new LoadWarehouseFilter( summary.getWarehouseId() ) ), ResponseTypes.instanceOf(Warehouse.class));
        	
        	entity = futureEntity.get();
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate Warehouse with id " + summary.getWarehouseId();
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all Warehouses
     *
     * @return 	List<Warehouse> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<Warehouse> getAllWarehouse() 
    throws ProcessingException {
        List<Warehouse> list = null;

        try {
        	CompletableFuture<List<Warehouse>> futureList = queryGateway.query(new FindAllWarehouseQuery(), ResponseTypes.multipleInstancesOf(Warehouse.class));
        	
        	list = futureList.get();
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all Warehouse";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }


    /**
     * add StorageLocation to StorageLocations 
     * @param		command AssignStorageLocationsToWarehouseCommand
     * @exception	ProcessingException
     */     
	public void addToStorageLocations( AssignStorageLocationsToWarehouseCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getWarehouseId() );

		StorageLocationService childDelegate 	= StorageLocationService.getStorageLocationInstance();
		WarehouseService parentDelegate = WarehouseService.getWarehouseInstance();		
		UUID childId = command.getAddTo().getStorageLocationId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a StorageLocation as StorageLocations to Warehouse" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove StorageLocation from StorageLocations
     * @param		command RemoveStorageLocationsFromWarehouseCommand
     * @exception	ProcessingException
     */     	
	public void removeFromStorageLocations( RemoveStorageLocationsFromWarehouseCommand command ) throws ProcessingException {		
		
		StorageLocationService childDelegate 	= StorageLocationService.getStorageLocationInstance();
		UUID childId = command.getRemoveFrom().getStorageLocationId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add InventoryItem to InventoryItems 
     * @param		command AssignInventoryItemsToWarehouseCommand
     * @exception	ProcessingException
     */     
	public void addToInventoryItems( AssignInventoryItemsToWarehouseCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getWarehouseId() );

		InventoryItemService childDelegate 	= InventoryItemService.getInventoryItemInstance();
		WarehouseService parentDelegate = WarehouseService.getWarehouseInstance();		
		UUID childId = command.getAddTo().getInventoryItemId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a InventoryItem as InventoryItems to Warehouse" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove InventoryItem from InventoryItems
     * @param		command RemoveInventoryItemsFromWarehouseCommand
     * @exception	ProcessingException
     */     	
	public void removeFromInventoryItems( RemoveInventoryItemsFromWarehouseCommand command ) throws ProcessingException {		
		
		InventoryItemService childDelegate 	= InventoryItemService.getInventoryItemInstance();
		UUID childId = command.getRemoveFrom().getInventoryItemId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add InboundShipment to InboundShipments 
     * @param		command AssignInboundShipmentsToWarehouseCommand
     * @exception	ProcessingException
     */     
	public void addToInboundShipments( AssignInboundShipmentsToWarehouseCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getWarehouseId() );

		InboundShipmentService childDelegate 	= InboundShipmentService.getInboundShipmentInstance();
		WarehouseService parentDelegate = WarehouseService.getWarehouseInstance();		
		UUID childId = command.getAddTo().getInboundShipmentId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a InboundShipment as InboundShipments to Warehouse" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove InboundShipment from InboundShipments
     * @param		command RemoveInboundShipmentsFromWarehouseCommand
     * @exception	ProcessingException
     */     	
	public void removeFromInboundShipments( RemoveInboundShipmentsFromWarehouseCommand command ) throws ProcessingException {		
		
		InboundShipmentService childDelegate 	= InboundShipmentService.getInboundShipmentInstance();
		UUID childId = command.getRemoveFrom().getInboundShipmentId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add OutboundAllocation to OutboundAllocations 
     * @param		command AssignOutboundAllocationsToWarehouseCommand
     * @exception	ProcessingException
     */     
	public void addToOutboundAllocations( AssignOutboundAllocationsToWarehouseCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getWarehouseId() );

		OutboundAllocationService childDelegate 	= OutboundAllocationService.getOutboundAllocationInstance();
		WarehouseService parentDelegate = WarehouseService.getWarehouseInstance();		
		UUID childId = command.getAddTo().getOutboundAllocationId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a OutboundAllocation as OutboundAllocations to Warehouse" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove OutboundAllocation from OutboundAllocations
     * @param		command RemoveOutboundAllocationsFromWarehouseCommand
     * @exception	ProcessingException
     */     	
	public void removeFromOutboundAllocations( RemoveOutboundAllocationsFromWarehouseCommand command ) throws ProcessingException {		
		
		OutboundAllocationService childDelegate 	= OutboundAllocationService.getOutboundAllocationInstance();
		UUID childId = command.getRemoveFrom().getOutboundAllocationId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add TransferOrder to OriginTransfers 
     * @param		command AssignOriginTransfersToWarehouseCommand
     * @exception	ProcessingException
     */     
	public void addToOriginTransfers( AssignOriginTransfersToWarehouseCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getWarehouseId() );

		TransferOrderService childDelegate 	= TransferOrderService.getTransferOrderInstance();
		WarehouseService parentDelegate = WarehouseService.getWarehouseInstance();		
		UUID childId = command.getAddTo().getTransferOrderId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a TransferOrder as OriginTransfers to Warehouse" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove TransferOrder from OriginTransfers
     * @param		command RemoveOriginTransfersFromWarehouseCommand
     * @exception	ProcessingException
     */     	
	public void removeFromOriginTransfers( RemoveOriginTransfersFromWarehouseCommand command ) throws ProcessingException {		
		
		TransferOrderService childDelegate 	= TransferOrderService.getTransferOrderInstance();
		UUID childId = command.getRemoveFrom().getTransferOrderId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add TransferOrder to DestinationTransfers 
     * @param		command AssignDestinationTransfersToWarehouseCommand
     * @exception	ProcessingException
     */     
	public void addToDestinationTransfers( AssignDestinationTransfersToWarehouseCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getWarehouseId() );

		TransferOrderService childDelegate 	= TransferOrderService.getTransferOrderInstance();
		WarehouseService parentDelegate = WarehouseService.getWarehouseInstance();		
		UUID childId = command.getAddTo().getTransferOrderId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a TransferOrder as DestinationTransfers to Warehouse" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove TransferOrder from DestinationTransfers
     * @param		command RemoveDestinationTransfersFromWarehouseCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDestinationTransfers( RemoveDestinationTransfersFromWarehouseCommand command ) throws ProcessingException {		
		
		TransferOrderService childDelegate 	= TransferOrderService.getTransferOrderInstance();
		UUID childId = command.getRemoveFrom().getTransferOrderId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add CycleCount to CycleCounts 
     * @param		command AssignCycleCountsToWarehouseCommand
     * @exception	ProcessingException
     */     
	public void addToCycleCounts( AssignCycleCountsToWarehouseCommand command ) throws ProcessingException {
		
		
		// -------------------------------------------
		// load the parent
		// -------------------------------------------
		load( command.getWarehouseId() );

		CycleCountService childDelegate 	= CycleCountService.getCycleCountInstance();
		WarehouseService parentDelegate = WarehouseService.getWarehouseInstance();		
		UUID childId = command.getAddTo().getCycleCountId();
		
		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
        	// issue the command
        	// --------------------------------------    	
    		commandGateway.sendAndWait( command );			
		}
		catch( Exception exc ) {
			final String msg = "Failed to add a CycleCount as CycleCounts to Warehouse" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove CycleCount from CycleCounts
     * @param		command RemoveCycleCountsFromWarehouseCommand
     * @exception	ProcessingException
     */     	
	public void removeFromCycleCounts( RemoveCycleCountsFromWarehouseCommand command ) throws ProcessingException {		
		
		CycleCountService childDelegate 	= CycleCountService.getCycleCountInstance();
		UUID childId = command.getRemoveFrom().getCycleCountId();

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	validator.validate( command );    

	    	// --------------------------------------
	    	// issue the command
	    	// --------------------------------------    	
			commandGateway.sendAndWait( command );

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + childId; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}



	/**
	 * Internal helper method to load the root 
	 * 
	 * @param		id	UUID
	 * @return		Warehouse
	 */
	protected Warehouse load( UUID id ) throws ProcessingException {
		warehouse = WarehouseService.getWarehouseInstance().getWarehouse( new WarehouseFetchOneSummary(id) );	
		return warehouse;
	}


//************************************************************************
// Attributes
//************************************************************************
	private QueryGateway queryGateway;
	private CommandGateway commandGateway;
	private QueryUpdateEmitter queryUpdateEmitter;
	private WarehouseValidator validator;
	private Warehouse warehouse 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(WarehouseService.class.getName());
    
}
