#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.governanceOnDjango
requirements.txt=.governanceOnDjango
admin.py=.governanceOnDjango
apps.py=.governanceOnDjango
appUrls.py=.governanceOnDjango
setup.py=.governanceOnDjango
README.rst=.governanceOnDjango
LICENSE=.governanceOnDjango
Dockerfile=.governanceOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.governanceOnDjango.mainsite
wsgi.py=.governanceOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.governanceOnDjango.models
__classes__Delegate.py=.governanceOnDjango.delegates
__classes__Test.py=.governanceOnDjango.tests
__classes__View.py=.governanceOnDjango.views
__classes__Urls.py=.governanceOnDjango.urls
__enums__.py=.governanceOnDjango.models
Exceptions.py=.governanceOnDjango.exceptions
empty.doc=.governanceOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.governanceOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.governanceOnDjango.mainsite,.governanceOnDjango.models,.governanceOnDjango.delegates,.governanceOnDjango.tests,.governanceOnDjango.views,.governanceOnDjango.urls,.governanceOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json