/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Analytics Capabilities Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>TimeSeriesValidation</h2>
 * <p>
 * The TimeSeries Validation  handles state validation of a TimeSeries include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/21/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Analytics Capabilities Model</td></tr>
 *          <tr><td>description</td><td>A comprehensive capabilities model for analytics, business intelligence, machine learning, forecasting, data quality, and data lineage across the analytics lifecycle.</td></tr>
 *          <tr><td>industry</td><td>Cross-Industry</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateTimeSeriesCommand</li>
 *      <li>UpdateTimeSeriesCommand</li>
 *      <li>DeleteTimeSeriesCommand</li>
 *set( false = false )
   *       <li>AssignDatasetsToTimeSeriesCommand</li>
 *       <li>RemoveDatasetsFromTimeSeriesCommand</li>
 *   </ul>
 *
  *       <li>AssignForecastsToTimeSeriesCommand</li>
 *       <li>RemoveForecastsFromTimeSeriesCommand</li>
 *   </ul>
 *
  *       <li>AssignAnomaliesToTimeSeriesCommand</li>
 *       <li>RemoveAnomaliesFromTimeSeriesCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class TimeSeriesValidator {

	/**
	 * default constructor
	 */
	protected TimeSeriesValidator() {
	}


	/**
	 * handles creation validation for a TimeSeries
	 */
	public void validate( CreateTimeSeriesCommand timeSeries )throws ValidationException {
		if ( timeSeries == null )
		throw new ValidationException( "TimeSeries", "validating CreateTimeSeriesCommand" );
		if ( timeSeries.getName() == null )
		throw new ValidationException( "TimeSeries", "validating access on getName" );
		if ( timeSeries.getTimezone() == null )
		throw new ValidationException( "TimeSeries", "validating access on getTimezone" );
	}

	/**
	 * handles update validation for a TimeSeries
	 */
	public void validate( UpdateTimeSeriesCommand timeSeries ) throws ValidationException {
		if ( timeSeries == null )
		throw new ValidationException( "TimeSeries", "validating UpdateTimeSeriesCommand" );
		if ( timeSeries.getName() == null )
		throw new ValidationException( "TimeSeries", "validating method getName" );
		if ( timeSeries.getTimezone() == null )
		throw new ValidationException( "TimeSeries", "validating method getTimezone" );
	}

/**
 * handles delete validation for a TimeSeries
 */
	public void validate( DeleteTimeSeriesCommand timeSeries ) throws ValidationException {
		if ( timeSeries == null )
			throw new ValidationException( "TimeSeries", "validating DeleteTimeSeriesCommand" );
	}

/**
 * handles fetchOne validation for a TimeSeries
 */
	public void validate( TimeSeriesFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "TimeSeries", "validating summary" );
	}


	/**
	 * handles add to Datasets validation for a TimeSeries
	 *
	 * @param	command AssignDatasetsToTimeSeriesCommand
	 */
	public void validate( AssignDatasetsToTimeSeriesCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "TimeSeries", "validating AssignDatasetsToTimeSeriesCommand" );

		if ( command.getTimeSeriesId() == null )
		throw new ValidationException( "TimeSeries", "validating identity on AssignDatasetsToTimeSeriesCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "TimeSeries", "validating addTo attribute on AssignDatasetsToTimeSeriesCommand" );

	}

	/**
	 * handles remove from Datasets validation for a TimeSeries
	 *
	 * @param	command RemoveDatasetsFromTimeSeriesCommand
	 */
	public void validate( RemoveDatasetsFromTimeSeriesCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("TimeSeries", "validating RemoveDatasetsFromTimeSeriesCommand" );

		if( command.getTimeSeriesId() == null )
			throw new ValidationException("TimeSeries", "validating id on RemoveDatasetsFromTimeSeriesCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("TimeSeries", "validating remove from RemoveDatasetsFromTimeSeriesCommand" );

		if( command.getRemoveFrom().getDataSetId() == null )
			throw new ValidationException("TimeSeries", "validating id on remove from RemoveDatasetsFromTimeSeriesCommand" );
	}

	/**
	 * handles add to Forecasts validation for a TimeSeries
	 *
	 * @param	command AssignForecastsToTimeSeriesCommand
	 */
	public void validate( AssignForecastsToTimeSeriesCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "TimeSeries", "validating AssignForecastsToTimeSeriesCommand" );

		if ( command.getTimeSeriesId() == null )
		throw new ValidationException( "TimeSeries", "validating identity on AssignForecastsToTimeSeriesCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "TimeSeries", "validating addTo attribute on AssignForecastsToTimeSeriesCommand" );

	}

	/**
	 * handles remove from Forecasts validation for a TimeSeries
	 *
	 * @param	command RemoveForecastsFromTimeSeriesCommand
	 */
	public void validate( RemoveForecastsFromTimeSeriesCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("TimeSeries", "validating RemoveForecastsFromTimeSeriesCommand" );

		if( command.getTimeSeriesId() == null )
			throw new ValidationException("TimeSeries", "validating id on RemoveForecastsFromTimeSeriesCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("TimeSeries", "validating remove from RemoveForecastsFromTimeSeriesCommand" );

		if( command.getRemoveFrom().getForecastId() == null )
			throw new ValidationException("TimeSeries", "validating id on remove from RemoveForecastsFromTimeSeriesCommand" );
	}

	/**
	 * handles add to Anomalies validation for a TimeSeries
	 *
	 * @param	command AssignAnomaliesToTimeSeriesCommand
	 */
	public void validate( AssignAnomaliesToTimeSeriesCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "TimeSeries", "validating AssignAnomaliesToTimeSeriesCommand" );

		if ( command.getTimeSeriesId() == null )
		throw new ValidationException( "TimeSeries", "validating identity on AssignAnomaliesToTimeSeriesCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "TimeSeries", "validating addTo attribute on AssignAnomaliesToTimeSeriesCommand" );

	}

	/**
	 * handles remove from Anomalies validation for a TimeSeries
	 *
	 * @param	command RemoveAnomaliesFromTimeSeriesCommand
	 */
	public void validate( RemoveAnomaliesFromTimeSeriesCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("TimeSeries", "validating RemoveAnomaliesFromTimeSeriesCommand" );

		if( command.getTimeSeriesId() == null )
			throw new ValidationException("TimeSeries", "validating id on RemoveAnomaliesFromTimeSeriesCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("TimeSeries", "validating remove from RemoveAnomaliesFromTimeSeriesCommand" );

		if( command.getRemoveFrom().getAnomalyId() == null )
			throw new ValidationException("TimeSeries", "validating id on remove from RemoveAnomaliesFromTimeSeriesCommand" );
	}


}
