/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * Aerospace Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>ProductionLine business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of ProductionLine related services in the case of a ProductionLine business related service failing.</li>
 * <li>Exposes a simpler, uniform ProductionLine interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill ProductionLine business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/21/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Aerospace Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>Metadata describing this Aerospace HCIDL document.</td></tr>
 *          <tr><td>industry</td><td>Aerospace</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class ProductionLineService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
	/**
	 * Default Constructor
	 */
    public ProductionLineService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity		= identity;
		this.projector 		= new ProductionLineEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
										applicationContext.getBean(ProductionLineRepository.class) );
		this.validator		= applicationContext.getBean(ProductionLineValidator.class) ;
	}


	/**
	 * Creates the provided command.
	 *
	 * @param		command ${class.getCreateCommandAlias()}
	 * @return		ProductionLine
	 */
		public ProductionLine createProductionLine( CreateProductionLineCommand command ) {

		ProductionLine entity = new ProductionLine();

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

            entity.setProductionLineId( command.getProductionLineId() );
            entity.setName( command.getName() );
            entity.setLineType( command.getLineType() );

		// ------------------------------------------
		// persist a new one
		// ------------------------------------------
		entity = projector.create(entity);

		LOGGER.info( "done creating of ProductionLine {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Update the provided command.
	 * @param		command UpdateProductionLineCommand
	 * @return		ProductionLine
	 */
	public ProductionLine updateProductionLine( UpdateProductionLineCommand command ) {

		ProductionLine entity = new ProductionLine();

		// --------------------------------------
		// validate
		// --------------------------------------
		validator.validate( command );

            entity.setProductionLineId( command.getProductionLineId() );
            entity.setName( command.getName() );
            entity.setPlant( command.getPlant() );
            entity.setWorkCenters( command.getWorkCenters() );
            entity.setLineType( command.getLineType() );

		// ------------------------------------------
		// persist an existing one
		// ------------------------------------------
		entity = projector.update(entity);

		LOGGER.info( "done saving of ProductionLine {0} ", entity.toString() );

		return entity;
	}

	/**
	 * Deletes the associatied value object
	 * @param		command DeleteProductionLineCommand
	 */
	public void delete( DeleteProductionLineCommand command ) {
		UUID id = null;

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		id = command.getProductionLineId();

		// ------------------------------------------
		// delete the entity
		// ------------------------------------------
		projector.delete(id);

		LOGGER.info( "done deleting of ProductionLine {0} ", id );

	}

	/**
	 * Method to retrieve the ProductionLine via ProductionLineFetchOneSummary
	 * @param 	summary ProductionLineFetchOneSummary
	 * @return 	ProductionLineFetchOneResponse
	 */
	public ProductionLine getProductionLine( ProductionLineFetchOneSummary summary ) {

		if( summary == null )
			throw new IllegalStateException( "ProductionLineFetchOneSummary arg cannot be null" );

		ProductionLine entity = null;
		UUID id = summary.getProductionLineId();

		// --------------------------------------
		// validate the fetch one summary
		// --------------------------------------
		validator.validate( summary );

		// --------------------------------------
		// find a ProductionLine using the provided id
		// --------------------------------------
		entity = projector.find( id );

		return entity;
	}


	/**
	 * Method to retrieve a collection of all ProductionLines
	 *
	 * @return 	List<ProductionLine>
	 */
    public List<ProductionLine> getAllProductionLine() {
		List<ProductionLine> list = projector.findAll( new FindAllProductionLineQuery() );
		return list;
	}

	/**
	 * assign Plant on ProductionLine
	 * @param		command AssignPlantToProductionLineCommand
	 */
	public void assignPlant( AssignPlantToProductionLineCommand command ) {
		// --------------------------------------
		// best to validate the command now
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.assignPlant(command.getProductionLineId(), command.getAssignment());

	}

	/**
	 * unAssign Plant on ProductionLine
	 * @param		command UnAssignPlantFromProductionLineCommand
	 */
	public void unAssignPlant( UnAssignPlantFromProductionLineCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.unAssignPlant(command.getProductionLineId());
	}
	

	/**
	 * add WorkCenter to WorkCenters
	 * @param		command AssignWorkCentersToProductionLineCommand
	 */
	public void addToWorkCenters( AssignWorkCentersToProductionLineCommand command ) {

		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.addToWorkCenters(command.getProductionLineId(), command.getAddTo());
	}

	/**
	 * remove WorkCenter from WorkCenters
	 * @param		command RemoveWorkCentersFromProductionLineCommand
	 */
	public void removeFromWorkCenters( RemoveWorkCentersFromProductionLineCommand command )  {
		// --------------------------------------
		// validate the command
		// --------------------------------------
		validator.validate( command );

		// --------------------------------------
		// delegate to the projector
		// --------------------------------------
		projector.removeFromWorkCenters(command.getProductionLineId(), command.getRemoveFrom());
	}




//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final ProductionLineEntityProjector projector;
	private final ProductionLineValidator validator;
	private ProductionLine productionLine 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(ProductionLineService.class);
}
