#------------------------------------------------------------------------------
# Harbormaster
# 2021 Harbormaster, Inc.
# All Rights Reserved.
# 
# This file is subject to the terms and conditions defined in
# file 'license.txt', which is part of this source code package.
#  
# Contributors :
#       Harbormaster Dev Team - General Release
#-------------------------------------------------------------------------------




#------------------------------------------------------------------------------
# django root related
#------------------------------------------------------------------------------
manage.py=.advertisingOnDjango
requirements.txt=.advertisingOnDjango
admin.py=.advertisingOnDjango
apps.py=.advertisingOnDjango
appUrls.py=.advertisingOnDjango
setup.py=.advertisingOnDjango
README.rst=.advertisingOnDjango
LICENSE=.advertisingOnDjango
Dockerfile=.advertisingOnDjango

#------------------------------------------------------------------------------
# django mainsite related
#------------------------------------------------------------------------------
settings.py=.advertisingOnDjango.mainsite
wsgi.py=.advertisingOnDjango.mainsite

#------------------------------------------------------------------------------
# django app related
#------------------------------------------------------------------------------
__classes__.py=.advertisingOnDjango.models
__classes__Delegate.py=.advertisingOnDjango.delegates
__classes__Test.py=.advertisingOnDjango.tests
__classes__View.py=.advertisingOnDjango.views
__classes__Urls.py=.advertisingOnDjango.urls
__enums__.py=.advertisingOnDjango.models
Exceptions.py=.advertisingOnDjango.exceptions
empty.doc=.advertisingOnDjango.docs

#------------------------------------------------------------------------------
# django test related
#------------------------------------------------------------------------------
pytest.ini=.advertisingOnDjango.tests
 
# django mainsite and app related...all django directories need an __init__.py to treat contents as Python
__init__.py=.advertisingOnDjango.mainsite,.advertisingOnDjango.models,.advertisingOnDjango.delegates,.advertisingOnDjango.tests,.advertisingOnDjango.views,.advertisingOnDjango.urls,.advertisingOnDjango.exceptions

exclusions=mappings.properties,options.json,blueprint.json