/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Healthcare Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * FacilityRestController as REST API
 *
 * <p>Exposes REST endpoints for the Facility entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Healthcare Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core provider, patient, clinical, diagnostics, pharmacy, financial, and device-management capabilities.</td></tr>
 *          <tr><td>industry</td><td>Healthcare</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	FacilityBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateFacilityCommand</li>
 *      <li></li>UpdateFacilityCommand</li>
 *      <liDeleteFacilityCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Facility")
public class FacilityRestController extends BaseSpringRestController {

	public FacilityRestController( FacilityService service ) {
		this.service = service;
	}
	
    /**
     * Handles create a Facility.  if not key provided, calls create, otherwise calls save
     * @param		Facility	facility
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateFacilityCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = service.createFacility( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a Facility.  if no key provided, calls create, otherwise calls save
     * @param		Facility facility
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateFacilityCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateFacilityCommand
			// -----------------------------------------------
			completableFuture = service.updateFacility(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "FacilityController:update() - successfully update Facility - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a Facility entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteFacilityCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	FacilityService delegate = service;

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Facility with key " + command.getFacilityId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a Facility using a UUID
     * @param		UUID uuid 
     * @return		Facility
     */    
    @GetMapping("/load")
    public Facility load( @RequestParam(required=true) UUID uuid ) {    	
    	Facility entity = null;

    	try {  
    		entity = service.getFacility( new FacilityFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Facility using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Facility business objects
     * @return		Set<Facility>
     */
    @GetMapping("/")
    public List<Facility> loadAll() {                
    	List<Facility> facilityList = null;
        
    	try {
            // load the Facility
            facilityList = service.getAllFacility();
            
            if ( facilityList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Facilitys" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Facilitys ", exc );
        	return null;
        }

        return facilityList;
                            
    }

    /**
     * save HealthSystem on Facility
     * @param		command AssignHealthSystemToFacilityCommand
     */     
	@PutMapping("/assignHealthSystem")
	public void assignHealthSystem( @RequestBody AssignHealthSystemToFacilityCommand command ) {
		try {
			service.assignHealthSystem( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign HealthSystem", exc );
        }
	}

    /**
     * unassign HealthSystem on Facility
     * @param		 command UnAssignHealthSystemFromFacilityCommand
     */     
	@PutMapping("/unAssignHealthSystem")
	public void unAssignHealthSystem( @RequestBody(required=true)  UnAssignHealthSystemFromFacilityCommand command ) {
		try {
			service.unAssignHealthSystem( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign HealthSystem", exc );
		}
	}
	

    /**
     * save Departments on Facility
     * @param		command AssignDepartmentsToFacilityCommand
     */     
	@PutMapping("/addToDepartments")
	public void addToDepartments( @RequestBody(required=true) AssignDepartmentsToFacilityCommand command ) {
		try {
			service.addToDepartments( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Departments", exc );
		}
	}

    /**
     * remove Departments on Facility
     * @param		command RemoveDepartmentsFromFacilityCommand
     */     	
	@PutMapping("/removeFromDepartments")
	public void removeFromDepartments( 	@RequestBody(required=true) RemoveDepartmentsFromFacilityCommand command )
	{		
		try {
			service.removeFromDepartments( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Departments", exc );
		}
	}

    /**
     * save CareTeams on Facility
     * @param		command AssignCareTeamsToFacilityCommand
     */     
	@PutMapping("/addToCareTeams")
	public void addToCareTeams( @RequestBody(required=true) AssignCareTeamsToFacilityCommand command ) {
		try {
			service.addToCareTeams( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set CareTeams", exc );
		}
	}

    /**
     * remove CareTeams on Facility
     * @param		command RemoveCareTeamsFromFacilityCommand
     */     	
	@PutMapping("/removeFromCareTeams")
	public void removeFromCareTeams( 	@RequestBody(required=true) RemoveCareTeamsFromFacilityCommand command )
	{		
		try {
			service.removeFromCareTeams( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set CareTeams", exc );
		}
	}

    /**
     * save Laboratories on Facility
     * @param		command AssignLaboratoriesToFacilityCommand
     */     
	@PutMapping("/addToLaboratories")
	public void addToLaboratories( @RequestBody(required=true) AssignLaboratoriesToFacilityCommand command ) {
		try {
			service.addToLaboratories( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Laboratories", exc );
		}
	}

    /**
     * remove Laboratories on Facility
     * @param		command RemoveLaboratoriesFromFacilityCommand
     */     	
	@PutMapping("/removeFromLaboratories")
	public void removeFromLaboratories( 	@RequestBody(required=true) RemoveLaboratoriesFromFacilityCommand command )
	{		
		try {
			service.removeFromLaboratories( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Laboratories", exc );
		}
	}

    /**
     * save ImagingCenters on Facility
     * @param		command AssignImagingCentersToFacilityCommand
     */     
	@PutMapping("/addToImagingCenters")
	public void addToImagingCenters( @RequestBody(required=true) AssignImagingCentersToFacilityCommand command ) {
		try {
			service.addToImagingCenters( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set ImagingCenters", exc );
		}
	}

    /**
     * remove ImagingCenters on Facility
     * @param		command RemoveImagingCentersFromFacilityCommand
     */     	
	@PutMapping("/removeFromImagingCenters")
	public void removeFromImagingCenters( 	@RequestBody(required=true) RemoveImagingCentersFromFacilityCommand command )
	{		
		try {
			service.removeFromImagingCenters( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set ImagingCenters", exc );
		}
	}

    /**
     * save Pharmacies on Facility
     * @param		command AssignPharmaciesToFacilityCommand
     */     
	@PutMapping("/addToPharmacies")
	public void addToPharmacies( @RequestBody(required=true) AssignPharmaciesToFacilityCommand command ) {
		try {
			service.addToPharmacies( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Pharmacies", exc );
		}
	}

    /**
     * remove Pharmacies on Facility
     * @param		command RemovePharmaciesFromFacilityCommand
     */     	
	@PutMapping("/removeFromPharmacies")
	public void removeFromPharmacies( 	@RequestBody(required=true) RemovePharmaciesFromFacilityCommand command )
	{		
		try {
			service.removeFromPharmacies( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Pharmacies", exc );
		}
	}

    /**
     * save InventoryItems on Facility
     * @param		command AssignInventoryItemsToFacilityCommand
     */     
	@PutMapping("/addToInventoryItems")
	public void addToInventoryItems( @RequestBody(required=true) AssignInventoryItemsToFacilityCommand command ) {
		try {
			service.addToInventoryItems( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set InventoryItems", exc );
		}
	}

    /**
     * remove InventoryItems on Facility
     * @param		command RemoveInventoryItemsFromFacilityCommand
     */     	
	@PutMapping("/removeFromInventoryItems")
	public void removeFromInventoryItems( 	@RequestBody(required=true) RemoveInventoryItemsFromFacilityCommand command )
	{		
		try {
			service.removeFromInventoryItems( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set InventoryItems", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Facility facility = null;
	protected FacilityService service = null;
	private static final Logger LOGGER = Logger.getLogger(FacilityRestController.class.getName());
    
}
