/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * CRM Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * AccountRestController as REST API
 *
 * <p>Exposes REST endpoints for the Account entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>CRM Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core CRM capabilities across accounts, contacts, leads, opportunities, pricing, quotes, orders, service cases, activities, and campaigns.</td></tr>
 *          <tr><td>industry</td><td>CRM</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	AccountBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateAccountCommand</li>
 *      <li></li>UpdateAccountCommand</li>
 *      <liDeleteAccountCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Account")
public class AccountRestController extends BaseSpringRestController {

	public AccountRestController( AccountService service ) {
		this.service = service;
	}
	
    /**
     * Handles create a Account.  if not key provided, calls create, otherwise calls save
     * @param		Account	account
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateAccountCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = service.createAccount( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a Account.  if no key provided, calls create, otherwise calls save
     * @param		Account account
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateAccountCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateAccountCommand
			// -----------------------------------------------
			completableFuture = service.updateAccount(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "AccountController:update() - successfully update Account - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a Account entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteAccountCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	AccountService delegate = service;

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Account with key " + command.getAccountId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a Account using a UUID
     * @param		UUID uuid 
     * @return		Account
     */    
    @GetMapping("/load")
    public Account load( @RequestParam(required=true) UUID uuid ) {    	
    	Account entity = null;

    	try {  
    		entity = service.getAccount( new AccountFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Account using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Account business objects
     * @return		Set<Account>
     */
    @GetMapping("/")
    public List<Account> loadAll() {                
    	List<Account> accountList = null;
        
    	try {
            // load the Account
            accountList = service.getAllAccount();
            
            if ( accountList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Accounts" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Accounts ", exc );
        	return null;
        }

        return accountList;
                            
    }

    /**
     * save Organization on Account
     * @param		command AssignOrganizationToAccountCommand
     */     
	@PutMapping("/assignOrganization")
	public void assignOrganization( @RequestBody AssignOrganizationToAccountCommand command ) {
		try {
			service.assignOrganization( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Organization", exc );
        }
	}

    /**
     * unassign Organization on Account
     * @param		 command UnAssignOrganizationFromAccountCommand
     */     
	@PutMapping("/unAssignOrganization")
	public void unAssignOrganization( @RequestBody(required=true)  UnAssignOrganizationFromAccountCommand command ) {
		try {
			service.unAssignOrganization( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Organization", exc );
		}
	}
	
    /**
     * save ParentAccount on Account
     * @param		command AssignParentAccountToAccountCommand
     */     
	@PutMapping("/assignParentAccount")
	public void assignParentAccount( @RequestBody AssignParentAccountToAccountCommand command ) {
		try {
			service.assignParentAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign ParentAccount", exc );
        }
	}

    /**
     * unassign ParentAccount on Account
     * @param		 command UnAssignParentAccountFromAccountCommand
     */     
	@PutMapping("/unAssignParentAccount")
	public void unAssignParentAccount( @RequestBody(required=true)  UnAssignParentAccountFromAccountCommand command ) {
		try {
			service.unAssignParentAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign ParentAccount", exc );
		}
	}
	
    /**
     * save Owner on Account
     * @param		command AssignOwnerToAccountCommand
     */     
	@PutMapping("/assignOwner")
	public void assignOwner( @RequestBody AssignOwnerToAccountCommand command ) {
		try {
			service.assignOwner( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Owner", exc );
        }
	}

    /**
     * unassign Owner on Account
     * @param		 command UnAssignOwnerFromAccountCommand
     */     
	@PutMapping("/unAssignOwner")
	public void unAssignOwner( @RequestBody(required=true)  UnAssignOwnerFromAccountCommand command ) {
		try {
			service.unAssignOwner( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Owner", exc );
		}
	}
	
    /**
     * save Territory on Account
     * @param		command AssignTerritoryToAccountCommand
     */     
	@PutMapping("/assignTerritory")
	public void assignTerritory( @RequestBody AssignTerritoryToAccountCommand command ) {
		try {
			service.assignTerritory( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Territory", exc );
        }
	}

    /**
     * unassign Territory on Account
     * @param		 command UnAssignTerritoryFromAccountCommand
     */     
	@PutMapping("/unAssignTerritory")
	public void unAssignTerritory( @RequestBody(required=true)  UnAssignTerritoryFromAccountCommand command ) {
		try {
			service.unAssignTerritory( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Territory", exc );
		}
	}
	

    /**
     * save ChildAccounts on Account
     * @param		command AssignChildAccountsToAccountCommand
     */     
	@PutMapping("/addToChildAccounts")
	public void addToChildAccounts( @RequestBody(required=true) AssignChildAccountsToAccountCommand command ) {
		try {
			service.addToChildAccounts( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set ChildAccounts", exc );
		}
	}

    /**
     * remove ChildAccounts on Account
     * @param		command RemoveChildAccountsFromAccountCommand
     */     	
	@PutMapping("/removeFromChildAccounts")
	public void removeFromChildAccounts( 	@RequestBody(required=true) RemoveChildAccountsFromAccountCommand command )
	{		
		try {
			service.removeFromChildAccounts( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set ChildAccounts", exc );
		}
	}

    /**
     * save Contacts on Account
     * @param		command AssignContactsToAccountCommand
     */     
	@PutMapping("/addToContacts")
	public void addToContacts( @RequestBody(required=true) AssignContactsToAccountCommand command ) {
		try {
			service.addToContacts( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Contacts", exc );
		}
	}

    /**
     * remove Contacts on Account
     * @param		command RemoveContactsFromAccountCommand
     */     	
	@PutMapping("/removeFromContacts")
	public void removeFromContacts( 	@RequestBody(required=true) RemoveContactsFromAccountCommand command )
	{		
		try {
			service.removeFromContacts( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Contacts", exc );
		}
	}

    /**
     * save Opportunities on Account
     * @param		command AssignOpportunitiesToAccountCommand
     */     
	@PutMapping("/addToOpportunities")
	public void addToOpportunities( @RequestBody(required=true) AssignOpportunitiesToAccountCommand command ) {
		try {
			service.addToOpportunities( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Opportunities", exc );
		}
	}

    /**
     * remove Opportunities on Account
     * @param		command RemoveOpportunitiesFromAccountCommand
     */     	
	@PutMapping("/removeFromOpportunities")
	public void removeFromOpportunities( 	@RequestBody(required=true) RemoveOpportunitiesFromAccountCommand command )
	{		
		try {
			service.removeFromOpportunities( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Opportunities", exc );
		}
	}

    /**
     * save Cases on Account
     * @param		command AssignCasesToAccountCommand
     */     
	@PutMapping("/addToCases")
	public void addToCases( @RequestBody(required=true) AssignCasesToAccountCommand command ) {
		try {
			service.addToCases( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Cases", exc );
		}
	}

    /**
     * remove Cases on Account
     * @param		command RemoveCasesFromAccountCommand
     */     	
	@PutMapping("/removeFromCases")
	public void removeFromCases( 	@RequestBody(required=true) RemoveCasesFromAccountCommand command )
	{		
		try {
			service.removeFromCases( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Cases", exc );
		}
	}

    /**
     * save Activities on Account
     * @param		command AssignActivitiesToAccountCommand
     */     
	@PutMapping("/addToActivities")
	public void addToActivities( @RequestBody(required=true) AssignActivitiesToAccountCommand command ) {
		try {
			service.addToActivities( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Activities", exc );
		}
	}

    /**
     * remove Activities on Account
     * @param		command RemoveActivitiesFromAccountCommand
     */     	
	@PutMapping("/removeFromActivities")
	public void removeFromActivities( 	@RequestBody(required=true) RemoveActivitiesFromAccountCommand command )
	{		
		try {
			service.removeFromActivities( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Activities", exc );
		}
	}

    /**
     * save Campaigns on Account
     * @param		command AssignCampaignsToAccountCommand
     */     
	@PutMapping("/addToCampaigns")
	public void addToCampaigns( @RequestBody(required=true) AssignCampaignsToAccountCommand command ) {
		try {
			service.addToCampaigns( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Campaigns", exc );
		}
	}

    /**
     * remove Campaigns on Account
     * @param		command RemoveCampaignsFromAccountCommand
     */     	
	@PutMapping("/removeFromCampaigns")
	public void removeFromCampaigns( 	@RequestBody(required=true) RemoveCampaignsFromAccountCommand command )
	{		
		try {
			service.removeFromCampaigns( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Campaigns", exc );
		}
	}

    /**
     * save Quotes on Account
     * @param		command AssignQuotesToAccountCommand
     */     
	@PutMapping("/addToQuotes")
	public void addToQuotes( @RequestBody(required=true) AssignQuotesToAccountCommand command ) {
		try {
			service.addToQuotes( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Quotes", exc );
		}
	}

    /**
     * remove Quotes on Account
     * @param		command RemoveQuotesFromAccountCommand
     */     	
	@PutMapping("/removeFromQuotes")
	public void removeFromQuotes( 	@RequestBody(required=true) RemoveQuotesFromAccountCommand command )
	{		
		try {
			service.removeFromQuotes( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Quotes", exc );
		}
	}

    /**
     * save Orders on Account
     * @param		command AssignOrdersToAccountCommand
     */     
	@PutMapping("/addToOrders")
	public void addToOrders( @RequestBody(required=true) AssignOrdersToAccountCommand command ) {
		try {
			service.addToOrders( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Orders", exc );
		}
	}

    /**
     * remove Orders on Account
     * @param		command RemoveOrdersFromAccountCommand
     */     	
	@PutMapping("/removeFromOrders")
	public void removeFromOrders( 	@RequestBody(required=true) RemoveOrdersFromAccountCommand command )
	{		
		try {
			service.removeFromOrders( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Orders", exc );
		}
	}

    /**
     * save Contracts on Account
     * @param		command AssignContractsToAccountCommand
     */     
	@PutMapping("/addToContracts")
	public void addToContracts( @RequestBody(required=true) AssignContractsToAccountCommand command ) {
		try {
			service.addToContracts( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Contracts", exc );
		}
	}

    /**
     * remove Contracts on Account
     * @param		command RemoveContractsFromAccountCommand
     */     	
	@PutMapping("/removeFromContracts")
	public void removeFromContracts( 	@RequestBody(required=true) RemoveContractsFromAccountCommand command )
	{		
		try {
			service.removeFromContracts( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Contracts", exc );
		}
	}

    /**
     * save Notes on Account
     * @param		command AssignNotesToAccountCommand
     */     
	@PutMapping("/addToNotes")
	public void addToNotes( @RequestBody(required=true) AssignNotesToAccountCommand command ) {
		try {
			service.addToNotes( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Notes", exc );
		}
	}

    /**
     * remove Notes on Account
     * @param		command RemoveNotesFromAccountCommand
     */     	
	@PutMapping("/removeFromNotes")
	public void removeFromNotes( 	@RequestBody(required=true) RemoveNotesFromAccountCommand command )
	{		
		try {
			service.removeFromNotes( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Notes", exc );
		}
	}

    /**
     * save EmailMessages on Account
     * @param		command AssignEmailMessagesToAccountCommand
     */     
	@PutMapping("/addToEmailMessages")
	public void addToEmailMessages( @RequestBody(required=true) AssignEmailMessagesToAccountCommand command ) {
		try {
			service.addToEmailMessages( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set EmailMessages", exc );
		}
	}

    /**
     * remove EmailMessages on Account
     * @param		command RemoveEmailMessagesFromAccountCommand
     */     	
	@PutMapping("/removeFromEmailMessages")
	public void removeFromEmailMessages( 	@RequestBody(required=true) RemoveEmailMessagesFromAccountCommand command )
	{		
		try {
			service.removeFromEmailMessages( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set EmailMessages", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Account account = null;
	protected AccountService service = null;
	private static final Logger LOGGER = Logger.getLogger(AccountRestController.class.getName());
    
}
